### ISSUE TITLE
GO:0031588 AMP-activated protein kinase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12069] opened 2015-09-21 07:51 UTC
S. cerevisiae Snf1 kinase complex proteins SNF1, SNF4 and SIP1/SIP2/GAL83 are annotated to GO:0031588 AMP-activated protein kinase complex, but they are actually activated by ADP (PMID: 22019086). 

Do we need a sister complexes, "ADP-activated protein kinase complex" for these proteins (and the related IntAct complex!), or should the annotations be shifted to the parent term, GO:1902554 serine/threonine protein kinase complex?

Thanks,
Birgit

**Comment by paolaroncaglia** [comment] 2015-09-21 09:46
Sounds like the activating molecule could (should?) be captured by an annotation extension. If that's correct, I would not create a new term for "ADP-activated protein kinase complex". Regardless of this decision, which you may want to discuss with the relevant protein complex working group, the S. cerevisiae annotations should not sit under GO:0031588 "AMP-activated protein kinase complex". I'm tagging Rama @rbalakri to comment from SGD's point of view. 

BTW, looks like the S. pombe homolog is indeed activated by AMP (PMID:17289942), so those annotations should be fine.

Thanks,
Paola

**Comment by ValWood** [comment] 2015-09-21 10:37
Is that for sure as it is also described as an AMP kinase at SGD?

Historically, we are trying to model the conserved nature of the complex  GO (i.e this complex seems to have 3 subunits with analogous members in each species). This might have changed, but if not, this should be a single complex term in GO, and the challenge is then to identify a  relatively uncontroversial species agnostic name for this complex...For example "SNF1/AMPK protein kinase complex"  (named after cerevisiae and human) with  "ADP-activated protein kinase complex" and "AMP-activated protein kinase complex" as related synonyms. 

The pombe/ cerevisiae members are conserved 1:1, so even though  there are small changes in  mechanism (and most likely targets too), this is still the same complex from an  evolutionary viewpoint, and we would want to annotate to the same GO term. Human has 3 paralogs for each subunit, so, if I have understood the discussions correctly, these would use the parent GO complex and  then use Intact  complexes IDs for the specific-specific variants (which will most likely be cell type of developmental phase specific?).

This would be a great example for the working group......

**Comment by bmeldal** [comment] 2015-09-21 11:19
Thanks, Val. 

Sandra curated the complex and the papers she read all showed ADP as the activator.

As for the structure, yes, I agree with Val, if we can make the actual term just "nucleotide-activated..." and and use narrow synonyms, that would work. And the specific complexes can/already do live in the CP.

I will make a list of examples for the WG!

**Comment by rbalakri** [comment] 2015-09-21 23:07
The structure suggested by Val works. I will check and update the yeast annotations (so far I haven't seen evidence for AMP-activation). The yeast SNF1 is a homolog of the mammalian AMPK. I think that is the cause for the confusion.

Rama


Rama

**Comment by bmeldal** [comment] 2015-09-22 09:52
Melanie, @mcourtot 

Excellent example for the distinction between sequence conservation and functional divergence! I have it on top of my list of examples for the WG! I wonder if we might need that extra ECO code I suggested this morning...

Birgit

**Comment by paolaroncaglia** [comment] 2015-09-22 12:58
Thanks all for your feedback.
So Rama will take care of correcting SGD's annotations.
As for the ontology, looks like there still isn't full agreement on the parent term name ("SNF1/AMPK protein kinase complex", "nucleotide-activated..."), so I'd leave this ticket open, and will come back to it after the working group has resolved on this.
Thanks,
Paola

**Comment by bmeldal** [comment] 2015-09-22 14:18
I think in the short term, we just have to come up with a name and list of synonyms and change the def to:

"A protein complex that possesses nucleotide-dependent protein kinase activity. The nucleotide can be AMP (in pombe and human) or ADP (in S.c.)."

If Val and Rama would like to come up with a name, then we can change that accordingly, close the ticket and release Sandra's 3 complexes :)

Thanks,
Birgit

**Comment by ValWood** [comment] 2015-09-22 14:44
lets use "nucleotide-activated protein kinase complex" for now and we can change later if anything better comes up.
val

**Comment by rbalakri** [comment] 2015-09-22 17:34
Fine by me.

R

**Comment by paolaroncaglia** [comment] 2015-10-01 10:09
Edited GO:0031588 ‘AMP-activated protein kinase complex’ as follows:

 [Term]
 id: GO:0031588
-name: AMP-activated protein kinase complex
+name: nucleotide-activated protein kinase complex
 namespace: cellular_component
-def: "A protein complex that possesses AMP-dependent protein kinase activity." [GOC:mah]
-synonym: "5'-AMP-activated protein kinase complex" EXACT []
+def: "A protein complex that possesses nucleotide-dependent protein kinase activity. The nucleotide can be AMP (in S. pombe and human) or ADP (in S. cerevisiae)." [GOC:bhm, GOC:mah, GOC:vw]
+synonym: "5'-AMP-activated protein kinase complex" NARROW []
+synonym: "ADP-activated protein kinase complex" NARROW []
+synonym: "AMP-activated protein kinase complex" NARROW []
 synonym: "AMPK complex" RELATED []
 synonym: "Snf1 kinase complex" NARROW []
 synonym: "Snf1 serine/threonine protein kinase complex" NARROW []
+synonym: "SNF1/AMPK protein kinase complex" NARROW []
 is_a: GO:0044424 ! intracellular part
 is_a: GO:1902554 {is_inferred="true"} ! serine/threonine protein kinase complex
-intersection_of: GO:0043234 ! protein complex
-intersection_of: capable_of GO:0004679 ! AMP-activated protein kinase activity

Thanks,
Paola

**Comment by bmeldal** [comment] 2015-10-01 10:16
Is
-intersection_of: capable_of GO:0004679 ! AMP-activated protein kinase activity
correct, if it's either by AMP or ADP?
Should it be 
GO:0004674 protein serine/threonine kinase activity?
or use the original intersection plus GO:NEW ADP-activated protein kinase activity?

Birgit

**Comment by paolaroncaglia** [comment] 2015-10-01 10:24
Hi Birgit,

The minus signs along the ontology stanza mean that those aspects have been removed.
I did that because AMP alone would have been incorrect (exactly).
If I gave the term an intersection for 'protein serine/threonine kinase activity' that would generate an error because the term would look the same as its parent to a reasoner. 
We would need a new term for 'nucleotide-activated protein kinase activity'. I can add that if you wish, but given that the complex term is under discussion, I was unsure it'd be needed.

Cheers,
Paola

**Comment by bmeldal** [comment] 2015-10-01 10:39
Doh! Yes, of course, you took it out! I must read more carefully...

As for the alternative activity, it would be nice to have the intersection, otherwise you don't have the link - or does it have the intersection through the parents anyway?

We are discussing the complex branch this afternoon, so might know more about how we should handle it all in principle.

**Comment by paolaroncaglia** [comment] 2015-10-01 10:48
The parent 'serine/threonine protein kinase complex' is capable_of protein serine/threonine kinase activity. But annotations don't propagate over capable_of, if that's what you're asking.
I need to work on other tasks for the rest of today, but if you add a comment after your complex meeting this afternoon (where 'complex' is the right word I believe :-D), I'll add the activity term and the link in the next few days.

Thanks,
Paola

**Comment by bmeldal** [comment] 2015-10-01 10:49
Thanks, Paula.

Yes, "complex"!!!

**Comment by paolaroncaglia** [comment] 2016-12-22 08:04
Hi @bmeldal ,
I noticed you didn't comment further on this ticket, so may I close it please? Or if there's any request you wished to add, please let me know, thanks. And happy holidays!

**Comment by bmeldal** [comment] 2016-12-22 11:37
It's missing 
is_a: GO:1902554 {is_inferred="true"} ! serine/threonine protein kinase complex
and
capable of GO:0004674 protein serine/threonine kinase activity

Birgit

**Comment by paolaroncaglia** [comment] 2016-12-22 17:56
Thanks @bmeldal - ok I'll look into this in January. Cheers.

**Comment by paolaroncaglia** [comment] 2017-01-12 12:10
Hi @bmeldal,
I went back to this but am confused. Here’s the current stanza:

[Term]
id: GO:0031588
name: nucleotide-activated protein kinase complex
namespace: cellular_component
def: "A protein complex that possesses nucleotide-dependent protein kinase activity. The nucleotide can be AMP (in S. pombe and human) or ADP (in S. cerevisiae)." [GOC:bhm, GOC:mah, GOC:vw]
synonym: "5'-AMP-activated protein kinase complex" NARROW []
synonym: "ADP-activated protein kinase complex" NARROW []
synonym: "AMP-activated protein kinase complex" NARROW []
synonym: "AMPK complex" RELATED []
synonym: "Snf1 kinase complex" NARROW []
synonym: "Snf1 serine/threonine protein kinase complex" NARROW []
synonym: "SNF1/AMPK protein kinase complex" NARROW []
is_a: GO:0043234 ! protein complex
is_a: GO:0044424 ! intracellular part
relationship: capable_of GO:0004672 ! protein kinase activity

If we added the links 
is_a GO:1902554 serine/threonine protein kinase complex
and
capable of GO:0004674 protein serine/threonine kinase activity
we’d be saying that *all* generic nucleotide-activated protein kinase complexes were specifically serine/threonine protein kinase complex and had protein serine/threonine kinase activity. It seems to me that those may not always hold true, and should therefore be captured by annotations instead, where appropriate. Also, at this stage (limited resources + pending discussion on protein complexes…), I’d rather not add more specific children either. I’ll close this ticket now, but if you think that the existing term violates any path or would otherwise cause errors, feel free to re-open. Thanks.

**Closed** 2017-01-12 12:10 UTC
Labels: Other term-related request, protein complex, time low (<2h), wrapping up

**Comment by bmeldal** [comment] 2017-01-13 16:56
Hi Paola,

The stanza from 1/10/15 included 
"is_a: GO:1902554 {is_inferred="true"} ! serine/threonine protein kinase complex"
which has since disappeared (acc to the QuickGO log on 21/11/15). I agree with your argument that, unless we know they are all serine/threonine protein kinases, we shouldn't have that intersection. I guess I looked at the stanza from October when I asked for the extra relationships.

So, let's keep it as it is :)
Birgit
