### ISSUE TITLE
NTR: estrogen 16-alpha-hydroxylase activity

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12576] opened 2016-08-11 13:42 UTC
NTR: estrogen 16-alpha-hydroxylase activity
Is_a child of GO:0008395 steroid hydroxylase activity (sibling to GO:0008390 testosterone 16-alpha-hydroxylase activity)

For annotation of PMID:14559847. Table 1 shows estrogen 16α-hydroxylation for human CYP isoforms.

Thanks,
Rachael.

Note to self: for Fiona's annotation.

**Comment by mcourtot** [comment] 2016-08-11 14:25
[Term]
id: GO:0101020
name: estrogen 16-alpha-hydroxylase activity

**Comment by RLovering** [comment] 2016-08-22 09:51
please add BHF-UCL tag to this request so that we can include this in our metrics

**Comment by mcourtot** [comment] 2016-08-22 09:54
Hi @RLovering 

There is already a BHF-UCL tag on this request? Did you mean something else?

![screen shot 2016-08-22 at 10 53 01](https://cloud.githubusercontent.com/assets/2214135/17850775/ac2072ba-6856-11e6-8553-45633ba14f50.png)

**Comment by RLovering** [comment] 2016-08-22 12:28
Hi Melanie
I don't know where the tag has to go but if you look in QuickGO at these two records ([http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0086019]) and [http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0101020#term=info] you will see one has the BHF logo on it and the other doesn't. All annotations UCL request's should have either the BHF or Parkinson's UK logos visible in QuickGO. This also means that when I generate stats of terms created through these funding sources  using this link [http://amigo.geneontology.org/amigo/search/ontology?q=definition_xref:GOC:BHF&sfq=document_category:%22ontology_class%22] then the terms will be included. 
I don't know how the labels above are translated into dbxrefs, whether this is a manual process or something that happens automatically, but it does not appear to have happened. In AmiGO the only source listed for this term is  Source: GOC:men, [http://amigo.geneontology.org/amigo/term/GO:0101020] whereas for the other term, [http://amigo.geneontology.org/amigo/term/GO:0086065], the source is listed as: Source: GOC:mtg_cardiac_conduct_nov11, **GOC:BHF** 

Please could you find out where the problem is and how many terms this may have affected

Best

Ruth

**Comment by mcourtot** [comment] 2016-08-22 12:42
HI @RLovering 
Quick check on the links you sent and with @tonysawfordebi tells me that everything that has a definition ref to GOC:BHF will get the logo (and shows up for stats etc).
I have updated done the update for this term; this will gradually become visible in QuickGO/AmiGO as new version fo the files are loaded. Any other problem please let me know.

Cheers,
Melanie

**Closed by mcourtot** 2016-08-22 12:42 UTC
Labels: BHF-UCL, New term request

**Comment by RLovering** [comment] 2016-08-22 15:05
Hi Melanie

many thanks

Ruth
