### ISSUE TITLE
Add terms to gocheck_obsoletion_candidate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28580] opened 2024-07-24 13:57 UTC
Hey ontobot! apply:

- add GO:0000079 to subset gocheck_obsoletion_candidate
- add GO:0006469to subset gocheck_obsoletion_candidate

**Comment by ValWood** [comment] 2024-08-07 13:23
duplicate of https://github.com/geneontology/go-ontology/issues/28581

**Closed by ValWood** 2024-08-07 13:23 UTC
