### ISSUE TITLE
Merge 'drug transmembrane transporter' into 'xenobiotic transmembrane transporter' (and the corresponding processes)

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16962] opened 2019-02-26 23:47 UTC
This is a splitting out of a single action from #14626 

The proposal is to obsolete drug transmembrane transporter. The rationale is that this does reflect a particular mechanism, add the distinction between whether a particular case of transmembrane transport for a chemical constitutes a non-drug or drug transport is either difficult to determine or does not reflect a mechanistic difference. The use of the term drug may have been a proxy for a more mechanistic description: xenobiotic, efflux pump, ...

However, obsoletion of a high level term should be done with consideration to end-users and curators.

I suspect many people search on this term. A clinical or basic researcher may want to search GO for genes involved in drug resistance. We should think through these use cases and determine (a) is GO the appropriate resource for answering this in whole or part and (b) how can we best satisfy this use case? This may involve trying to intuit the intent behind these queries and redirecting them (e.g. via synonyms).

If we agree to obsolete then we should decide if it is (a) a merge or (b) obsolete + replace/consider. I would strongly favor the latter, as I think we want to have clear information for people who do search on this and other drug concepts (e.g. "this terms was obsoleted because ... you may want to consider ..."). I think non-exact synonyms to the alternate terms may be justified.

We have >80 experimental annotations to this. There may be more information in these than simply "chemical transport". The curator may have used "drug transporter" even though a more appropriate mechanistic term was available.

Here is a sample of some existing annotated publications and my non-expert non-curator perspective:

This paper "involvement of an active efflux system in the natural resistance of Pseudomonas aeruginosa to aminoglycosides"
http://amigo.geneontology.org/amigo/reference/PMID:10543738

resulted in 4 annotations directly to drug transmembrane transport(er).

I think the role here is toxin, not drug. The evolved function/mechanism is efflux I think? We have GO:0015562 ! efflux transmembrane transporter activity, is this a better choice of term? (Amelia made this term, so it predated the annotations which were made in 2016!)

Similar for these candida annotations in 2014
http://amigo.geneontology.org/amigo/reference/PMID:8031026

I think the BENr gene is a pump so again seems like the function is pumping stuff harmful to the organism outside the cell? We should also think of the end user here, what kinds of queries would they ask that should meaningfully lead to this gene? E,g searches for "drug resistance" or "drug transport" than "efflux" or "pump". This could be handled with synonyms.

These annotations seem to be annotating to the name of the gene family rather than the function?
http://amigo.geneontology.org/amigo/reference/PMID:9483795

**Comment by ValWood** [comment] 2019-02-27 06:17
Definitely obsolete and reannotation (80 is a small number to fix, especially spread across resources), all can likely be annotated better, or fixed, and as you say many are toxins. It's more important to know influx or efflux in this situation!

We could, after obsoletion make these labels related  (or narrow) synonyms to "transmembrane 
transporter" for searching, on the basis that it is practically impossible to determine 
a) which compounds could be classed as drugs and 
b) which transporters could function as drug transporters. 
Users looking for this role should find *everything* and use their judgment to narrow down based on the substrate specificity of interest.

**Comment by pgaudet** [comment] 2019-02-27 14:35
In #15379 we mentioned merging into the parent; would that be OK for you @cmungall @ValWood ? 

- GO:0015238 drug transmembrane transporter activity -> GO:0022857 transmembrane transporter activity
- GO:0015893 drug transport -> transport (I'll try to make this TM transport if annotations are consistent) 
- GO:0006855 drug transmembrane transport ->

**Comment by cmungall** [comment] 2019-03-19 14:50
@pgaudet:
> In 15379 we mentioned merging into the parent,

My response is in my original comment above:

> If we agree to obsolete then we should decide if it is (a) a merge or (b) obsolete + replace/consider. I would strongly favor the latter, as I think we want to have clear information for people who do search on this and other drug concepts (e.g. "this terms was obsoleted because ... you may want to consider ..."). I think non-exact synonyms to the alternate terms may be justified.

And val said:

> Definitely obsolete and reannotation

**Comment by pgaudet** [comment] 2019-03-19 15:22
I thought the plan was to remove the CheBI 'role' of drug, which would get rid of all children, and people could annotate to 'drug transmembrane transporter' with a CHEBI term if they want to. 

For example these terms would not be under 'drug transporter activity': 
- GO:1901235 (R)-carnitine transmembrane transporter activity
-  GO:1903089 5-amino-1-ribofuranosylimidazole-4-carboxamide transmembrane transporter activity
- GO:0005277 acetylcholine transmembrane transporter activity 

Thanks, Pascale

**Comment by cmungall** [comment] 2019-03-21 02:36
> I thought the plan was to remove the CheBI 'role' of drug

yes, the plan is to never axiomatize using this ChEBI class, and to examine all GO classes that reference this class, likely obsoleting them. This ticket is about drug transmembrane transporter

> which would get rid of all children

not sure what you mean exactly

> and people could annotate to 'drug transmembrane transporter' with a CHEBI term if they want to

the proposal is to obsolete 'drug transmembrane transporter'

> For example these terms would not be under 'drug transporter activity':

Correct, because it would be obsolete

**Comment by pgaudet** [comment] 2019-03-25 14:36
Some annotations that would need to be rehoused if we obsoleted 

* GO:0015238 | drug transmembrane transporter activity
* GO:0015893 | drug   transport
* GO:0006855 | drug transmembrane transport
* GO:0046618 | drug   export
* GO:0061772 | drug transport across blood-nerve barrier 
* GO:1990962 | drug transport across blood-brain barrier
* GO:1905699 regulation of drug transmembrane export
* GO:1905700 negative regulation of drug transmembrane export
* GO:1905701 positive regulation of drug transmembrane export 

https://docs.google.com/spreadsheets/d/1hynVdp5Gh93lXxDa-pJx0qyDEH59IeW8ADY4njiuhmo/edit#gid=0

It's 227 annotations by the following groups: 

Contributor   (Assigned by) | Number of annotations
--
AspGD | 4
CGD | 67
EcoCyc | 33
EcoliWiki | 3
Ensembl | 1
GeneDB | 14
GOC | 4
MGI | 1
MTBBASE | 1
PomBase | 1
PseudoCAP | 23
RGD | 26
SGD | 31
TAIR | 3
UniProt | 14
UniProtKB | 1

**Comment by pgaudet** [comment] 2019-03-25 14:39
Most impacted groups are 
CGD 
EcoCyc @keseler 
Pseudocap @glwinsor 
RGD @slaulederkind 
SGD @srengel 
UniProt @milarolo

**Comment by srengel** [comment] 2019-03-25 15:14
Hi @pgaudet what are the suggested replacement terms?  that is, rehouse these annotations how?

**Comment by pgaudet** [comment] 2019-03-25 15:43
The proposal is to rehouse the annotations directly to the substrate being transported.

**Comment by pgaudet** [comment] 2019-03-25 16:24
Any term with a logical definition that refers to a 'role', we would remove that logical definition.

**Comment by dsiegele** [comment] 2019-03-25 22:00
"The proposal is to rehouse the annotations directly to the substrate being transported."

Many of the E. coli proteins annotated to drug transmembrane transport or drug transmembrane transporter activity are efflux pumps with multiple substrates. Does that create a problem for the proposal is to rehouse the annotations directly to the substrate being transported?"

EcoCyc@keseler

**Comment by pgaudet** [comment] 2019-03-26 07:20
An alternative proposal (that I think @ukemi also supports) would be to simply remove all children from the 'drug' terms, stop inferring what compounds are drugs, and encourage co-annotation to the substrate AND to drug transport when appropriate. 

Any preference ? (and why?) 

Thanks, Pascale

**Comment by ValWood** [comment] 2019-03-26 09:09
Leaving the term sounds a sensible solution. We just can't define what constitutes a drug. My main concern is that at present all of our amino acid transporters, and others are inferred as drug transporters due to chebi role. I would be happy if this was fixed.

**Comment by pgaudet** [comment] 2019-03-26 10:03
I could commit an intermediate version that looks like this

<img width="547" alt="image" src="https://user-images.githubusercontent.com/4782928/54988100-0e0ebd80-4fb6-11e9-8e59-124b6fc08af8.png">
 
As opposed to the current version: 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/4782928/54988303-72ca1800-4fb6-11e9-8ff0-81a44805be14.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/4782928/54988329-807f9d80-4fb6-11e9-826c-819aed5a42d4.png">


(and doing the same on the BP terms above). 

The remaining classes are asserted, we can decide what to do with them in a second step, but I think they are 'real' drugs. 

Does that sound like a reasonable first step @ukemi @cmungall @ValWood @srengel @dsiegele ?

**Comment by ukemi** [comment] 2019-03-26 12:20
The alternative proposal isn't mine. It's the one the consortium agreed upon many years ago. I suspect there are some children of the drug terms that are not chemicals, but are drug roles. For example, in your list above, drug:proton antiporter activity. I notice we also have antibiotic terms. We should spec out how the co-annotation would look in a GO-CAM model.

**Comment by srengel** [comment] 2019-03-26 13:32
The alternative definitely looks better than the current.

**Comment by pgaudet** [comment] 2019-03-26 14:22
> For example, in your list above, drug:proton antiporter activity. I notice we also have antibiotic terms.
All classes that I kept in this version are asserted. We should look one by one which ones to remove (I would personally do this as a separate ticket to avoid too many changes at once).

**Comment by thomaspd** [comment] 2019-03-27 17:54
GO-CAM model with two classes for an activity:
http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00002220

**Comment by cmungall** [comment] 2019-03-27 18:33
My original proposal was to obsolete this altogether. My proposal was not to universally replace it with the substrate (although that is fine in some situations), but to replace it with a term that reflects what the function of the gene product is.


Regarding @dsiegele's question, see my analysis at the top of the ticket, in this case I believe your replacement term would be:

```
id: GO:0015562
name: efflux transmembrane transporter activity
def: "Enables the transfer of a specific substance or related group of substances from the inside of the cell to the outside of the cell across a membrane." [GOC:ai, GOC:mtg_transport, ISBN:0815340729]
synonym: "efflux permease activity" EXACT []
synonym: "monocarboxylate (lactate, pyruvate, mevalonate) uptake/efflux porter activity" RELATED []
is_a: GO:0022857 ! transmembrane transporter activity
```

If people prefer to simply have a hardcoded list of chemicals that are considered drugs and for us to take on the burden of maintaining this, we can do this but we will need to allocate more resources, and it seems unsatisfactory.

**Comment by thomaspd** [comment] 2019-03-27 19:26
Sorry, didn't mean to confuse multiple issues-- I wasn't commenting on the drug transporter term, I was just trying to show how to co-annotate two terms to the same activity.  Look at http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00002220 again.  

I agree with Chris that we need to consider the (evolved) function.  I also favor removing "drug" from the terms.  If we want to specify an evolved function, in many cases it would be appropriate to use the more general "xenobiotic "(with drug as a narrow/inexact synonym for searching) to describe a class of molecules of exogenous origin.  So curators could annotate to "xenobiotic transporter activity", for instance.  Xenobiotic will of course be defined relative to the species of the gene product being annotated, which we would not try to encode in any way but leave up to curators.

**Comment by cmungall** [comment] 2019-03-27 19:34
Yes, I think many existing annotations would be better served by an annotation to xenobiotic TM transport plus a separate indication of the compound if known

**Comment by ValWood** [comment] 2019-03-28 07:52
Backtracking, I agree. It would be more consistent
For xenobiotics should the compound always be specified as a CHEBI extension?

If so, could we remove terms like
GO:0015240    amiloride transmembrane transporter activity (0 annotations)
GO:0015350 methotrexate transmembrane transporter activity (6 annotations)
to encourage consistency and best practice?

**Comment by ukemi** [comment] 2019-03-28 08:49
I agree with the obsoletion.

**Comment by pgaudet** [comment] 2019-04-04 09:24
Decisions ontology call: 

 - [x] Merge 'drug transmembrane transporter' into 'xenobiotic transmembrane transporter'
 - [ ] Merge 'drug transmembrane transport' into 'xenobiotic transmembrane transport'

**Comment by milarolo** [comment] 2019-04-25 14:44
SWIE done

**Comment by paolaroncaglia** [comment] 2019-11-27 17:27
Hi,
I've only had time to skim this thread quickly. I've noticed that GO:0015893 'drug transport' has lots of children that I wouldn't necessarily expect, e.g. 'oxygen transport'. So I searched the issue tracker for GO:0015893. Is the work that you plan to carry out for this ticket going to fix/modify that situation? :-) Thanks!
Paola

**Comment by ValWood** [comment] 2019-11-27 17:53
Hi @paolaroncaglia 
Reasoning over CHEBI roles ticket will fix this:
https://github.com/geneontology/go-ontology/issues/14626

**Comment by ValWood** [comment] 2020-02-05 07:52
I thought that stopping reasoning over CHEBI roles was implemented  recently? but I still have 39 random  inferred transporter annotations to "drug transport".

**Comment by krchristie** [comment] 2020-02-05 14:57
It hasn't been implemented yet. We are still discussing what the full resolution should be once we stop reasoning over roles. It is a big task.

**Comment by deustp01** [comment] 2020-02-05 15:09
Naive question: will this merge risk reviving the problem caused by roles when a molecule (like some estrogens) is both a normally occurring metabolite and a drug? Now will they be seen as xenobiotics because xenobiotic transporters mediate their movement?

**Comment by ValWood** [comment] 2020-02-05 15:47
Yes I don't know why I thought it was done.

**Comment by ValWood** [comment] 2020-02-05 15:49
I'm not sure that the problem here is entirely due to reasoning over roles.

I have "drug transporter" annotations for things like
L-methionine
uracil
pyridoxal
uridine
succinate....
are there *really* classified as drugs by CHEBI?

**Comment by ValWood** [comment] 2020-02-05 15:52
I don't see this:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:30031
under roles

**Comment by ValWood** [comment] 2020-02-05 15:53
succinate doesn't appear to be related to "drug" at all.
https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:26806
odd...

**Comment by mah11** [comment] 2020-02-05 16:06
Yes, the things on your list really do all have paths to "drug" or "drug metabolite" in CHEBI. Not all of the paths are entirely has_role+is_a; for example, for succinate it includes traversing a couple of "is conjugate base of" links to reach succinic acid.

**Comment by ValWood** [comment] 2020-02-05 16:51
AH OK, I could not see 'drug'  in the CHEBI  graph I looked at. So isn't it just a case of ignoring some relationships . Am I being naive?

**Comment by mah11** [comment] 2020-02-05 16:55
I think there's probably also something to do with the way GO lumps some CHEBI terms so we don't have to worry too much about the conjugate acid/conjugate base business. If so, then yeah, one consequence is that it's not easy to see enough of the CHEBI paths at once to understand where all of the "drug" inferences are coming from.

**Comment by pgaudet** [comment] 2020-02-06 11:22
We cannot resolve all 'roles' here but we can avoid using the term 'drug', which we have agreed multiple times to do. 

To do to close this ticket:
- [ ] merge GO:0015893  drug transport into GO:0042908 xenobiotic transport
(annotations have been reviewed in https://github.com/geneontology/go-annotation/issues/2332
- [ ] merge GO:0046618 drug export into GO:0140330 xenobiotic detoxification by transmembrane export across the cell outer membrane (see https://github.com/geneontology/go-annotation/issues/2334)
- [ ] GO:0006855 drug transmembrane transport merge into GO:0042908 xenobiotic transport 
- [ ]  GO:0042908 xenobiotic transport : change label to 'xenobiotic transmembrane transport'

Thanks, Pascale

**Comment by krchristie** [comment] 2020-02-06 15:49
Perhaps worth noting that 'xenobiotic' and 'drug' are both ChEBI roles and not completely overlapping. Depending on how we decide to deal with ChEBI roles, it might not make sense to merge drug into xenobiotic. I do agree that we should stop coding specific compounds as 'drugs' in the ontology, but the same flaw might also apply to 'xenobiotic'.

**Comment by pgaudet** [comment] 2020-02-06 15:53
Sure, but 'xenobiotic' is more general than drug. It's just a band aid but it would be good to remove all instances of 'drug' in the ontology.

**Comment by deustp01** [comment] 2020-02-06 15:56
> 'xenobiotic' is more general

But perhaps not general enough. To me penicillin and colchicine are xenobiotics, but to the fungus and plant that make them?

**Comment by krchristie** [comment] 2020-02-06 15:57
> Sure, but 'xenobiotic' is more general than drug. It's just a band aid but it would be good to remove all instances of 'drug' in the ontology.

I agree that what we are currently doing with 'drug' is a problem, but the more I look at ChEBI roles, I am starting to think that merging 'drug' terms into 'xenobiotic' terms will just be keeping the problem with a different name.

**Comment by pgaudet** [comment] 2020-02-07 13:02
Sure - the point was that all annotations to the dugs terms have been reviewed, so we reduce the number of terms we need to deal with later on. 

It would be good if no *new* annotations were made to drug terms, and the only way I see is to merge with a term we at least plan to keep. 

Up to you, of course. 

Thanks, Pascale

**Comment by krchristie** [comment] 2020-05-18 22:05
As discussed in the ticket: **handling terms for xenobiotic role and removing drug role** #19460, we have decided on these actions. For more detail about specific terms, go the the ticket linked above.
* MF terms ("drug binding" & 2 xenobiotic transporter activity terms) - will be made OBSOLETE as it doesn't make sense to describe a molecular function based on the context a chemical is being used in. Annotations will need to be reviewed and transferred to an appropriate MF term based on chemical specificity if possible.
* BP terms (transport terms, metabolic terms, response terms) - "drug" terms will be merged into the corresponding "xenobiotic" terms if one exists, or renamed from "drug" to "xenobiotic" if not.  
* regulation BP terms - There only a few of these all variations of "regulation of response to drug", so we will request for these to be reviewed and then decide if they should be converted to "xenobiotic" terms or Obsoleted.

As the new ticket comprehensively covers the plan for all of the drug and xenobiotic terms, I'm going to close this ticket.

**Closed by krchristie** 2020-05-18 22:05 UTC
