### ISSUE TITLE
relationship between  adenylate cyclase and  cAMP biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12890] opened 2017-01-02 19:29 UTC
In Amigo many annotations to
GO:0006171 cAMP biosynthetic process

http://amigo.geneontology.org/amigo/term/GO:0006171

have  a "NOT"  from PAINT.

But adenylate cyclase  GO:0004016  has a F-P link to  cAMP biosynthetic process
Should this relationship be removed?

What would we use this term for?
It only seems to be used for "adenylate cyclase"  is this one of those terms which isn't really "metabolism" its only "interconversion"

@pgaudet   is this the basis for the "NOTs"?

**Comment by mah11** [comment] 2017-01-03 14:05
I don't have any trouble believing that every time adenylate cyclase activity is executed, cyclic AMP is formed, and I think that's all that GO:0004016 part_of GO:0006171 means. It seems more likely the problem is with how AmiGO and/or PAINT is (or isn't) handling NOT.

Is everything annotated as "NOT GO:0006171" also annotated to GO:0004016, or are there other MFs represented?

**Comment by ValWood** [comment] 2017-01-03 14:13
The NOTS I saw were GO:0004016 .

But isn't this similar to not wanting to  annotate protein kinases to ADP synthesis?
or GTPase to GDP biosynthesis?

**Comment by ValWood** [comment] 2017-01-10 12:24
re metabolism, see @deustp01 recent comment here:
https://github.com/geneontology/go-ontology/issues/11890#issuecomment-271318991

"Wasn’t the big insight (for me, anyway) from David’s and my discussion with Jim Hu at the GOC meeting in November, that “catabolism” and “anabolism” terms are to be used only in connection with metabolic processes whose purpose is the storage and production of energy? I know the upshot was to narrow the range of reactions that get these labels; not sure I’ve remembered the exact narrowing right."

This seems like "one of these examples"

**Comment by ukemi** [comment] 2017-01-10 13:39
But the function-process link here is a part of relationship. It isn't saying that the function is a biosynthesis, it is saying it is part of it. It seems that this would be correct if you take the process all the way to the point of the final product.

**Comment by ukemi** [comment] 2017-01-10 13:59
So I guess another question that comes up here is that is the formation of cAMP considered just a step in signaling, similar to the phosphorylation of a protein? I don't think we would want to make protein kinase activity a part_of phosphoprotein biosynthesis. If cAMP (or any cyclic nucleotide) is used exclusively as a second messenger, then maybe it doesn't make sense to even think about its 'biosynthesis'. Is this what you are trying to distinguish?

@hdrabkin @deustp01 @jimhu-tamu   comments?

**Comment by ValWood** [comment] 2017-01-10 14:01
Yes ;) @pgaudet input would also be useful as to why the NOTs were established in PAINT annotation.

**Comment by pgaudet** [comment] 2017-01-10 14:36
Hello, 

Do you have examples where there are positive annotations to adenylate cyclase activity and NOT to cAMP biosynthesis ? The NOTs that I am aware of are for example guanylate cyclases that are in the same tree as adenylate cyclases. It is also 

Thanks, 
Pascale

**Comment by ValWood** [comment] 2017-01-10 14:47
Oh yes sorry, I was reading GO class as product name here
http://amigo.geneontology.org/amigo/term/GO:0004016
So do you think it makes sense to consider "adenylate cyclase"  as
GO:0006171 cAMP biosynthetic process ? or just "signalling"

**Comment by pgaudet** [comment] 2017-01-10 14:53
I personally think that the cAMP is formed as a signaling molecule, not as some 'metabolism', but it is consistent with how GO defines metabolism. 
- Pascale

**Comment by ukemi** [comment] 2017-01-17 14:59
Can we close this one?

**Comment by jimhu-tamu** [comment] 2017-01-17 16:09
My comment at the GO meeting was more specifically about anabolism and catabolism. I agree with Pascale that it seems consistent with metabolism. Val's protein kinase example seems like a different question that should be a different issue if people think it should be changed.

OK with me to close, but I only got the notice because of being mentioned.

**Comment by ukemi** [comment] 2017-01-17 16:22
Thanks @jimhu-tamu. I agree that I think this should be considered metabolism, but I'm not certain about biosynthesis based on the meeting discussion. We will discuss it on this week's editors call. In general, we really need to try to narrow down how biosynthetic and catabolic pathways are defined and where they begin and end.

**Comment by pgaudet** [comment] 2017-01-18 08:56
Hi, Just for the record: @jimhu-tamu @ukemi you write that I was arguing *in favor* of metabolism, while I was saying it should rather be signaling. 
https://en.wikipedia.org/wiki/Cyclic_adenosine_monophosphate
"Cyclic adenosine monophosphate (cAMP, cyclic AMP, or 3',5'-cyclic adenosine monophosphate) is a second messenger important in many biological processes. cAMP is a derivative of adenosine triphosphate (ATP) and used for intracellular signal transduction in many different organisms, conveying the cAMP-dependent pathway."

I would be in favor of having 'metabolism' (production and degradation of cellular molecules) and 'signaling' as two distinct branches of GO. The formation of cAMP could be considered a PTM on AMP rather than a biosynthetic process. 

- Pascale

**Comment by ValWood** [comment] 2017-01-18 15:59
Yes, this is what I was trying to get at. Is this metabolism? or  signalling only?

**Comment by pgaudet** [comment] 2017-01-19 10:34
I cannot think of an example where this would not be signaling.

**Comment by pgaudet** [comment] 2018-05-14 15:54
cAMP biosynthetic process is being obsoleted, so this ticket is not relevant anymore. 

#14718

**Closed by pgaudet** 2018-05-14 15:54 UTC
Labels: PomBase, editors-discussion, matrix, signaling
