### ISSUE TITLE
NTR: 7SK snRNP

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19981] opened 2020-09-11 12:15 UTC
Could I request a new complex term:
7SK snRNP

is_a small nuclear ribonucleoprotein complex

https://en.wikipedia.org/wiki/7SK_RNA

Def: A complex composed of the 7SK small nuclear RNA (7SK snRNA) and protein. The 7SK snRNP plays a central role in RNA polymerase II elongation control by regulating the availability of active P-TEFb.

PMID:28431135, PMID:18249148
GOC:ha

**Comment by ValWood** [comment] 2020-09-11 12:30
Is this the same as RNASE P or is it something else. What are the proteins then I can check....

**Comment by hattrill** [comment] 2020-09-11 12:32
LARP, MEPCE, HEXIM1

**Comment by hattrill** [comment] 2020-09-11 12:33
Not the same as RNase P. Doesn't have ribozyme function.

**Comment by ValWood** [comment] 2020-09-11 12:37
OK thanks. We have LARP, MEPCE,  but I don't think we have the RNA annotated. I'll look into that...

**Comment by krchristie** [comment] 2020-09-15 22:00
@ValWood - Let me know if you see evidence for 7SK in pombe. Otherwise, it might be good to put taxon constraints on this term as the Wikipedia page for  [7SK RNA](https://en.wikipedia.org/wiki/7SK_RNA) says the following, which is consistent with my recollection from SGD days about the snRNAs present in metazoans that are not present in yeast (admittedly my view of yeast is often limited to cerevisiae): 

> 7SK is an abundant small nuclear RNA found in metazoans.[1] It plays a role in regulating transcription by controlling the positive transcription elongation factor P-TEFb.[2] 7SK is found in a small nuclear ribonucleoprotein complex (snRNP) with a number of other proteins that regulate the stability and function of the complex.

**Comment by hattrill** [comment] 2020-09-16 07:46
Don't think that it is a yeast thing. 

Wasn't that long ago that they found it in D.mel!

**Comment by ValWood** [comment] 2020-09-16 08:20
I reckon it will likely be conserved, because we have 2 of the 3 proteins and the RNA probably preceded the proteins. The problem is that  divergent RNAs are even more difficult to detect than divergent proteins.

I'll put this  on a list  to search in our ncRNAs for candidates.... so add the taxon restriction for now It can be removed if we discover it.

**Comment by hattrill** [comment] 2020-09-16 08:23
It stayed hidden in D.mel for quite sometime and it is pretty important in the regulation of transcription elongation, so you're prob correct :-)

**Comment by ValWood** [comment] 2020-09-16 11:41
Somebody in the RNA world now lookin'  ;)

**Comment by krchristie** [comment] 2020-09-16 17:34
It seems that P-TEFb, as such, does not exist in cerevisiae: 

[Wood A, Shilatifard A. 2006. **Bur1/Bur2 and the Ctk complex in yeast: the split personality of mammalian P-TEFb.** Cell Cycle. 5(10):1066-1068. ](https://pubmed-ncbi-nlm-nih-gov.ezproxy.jax.org/16721054/)

> Not  only  can  P-TEFb  target  the  Pol  II  CTD,  but  it  also  inhibits transcriptional repression by DSIF (DRB sensitivity-inducing factor) and NELF (Negative Elongation Factor; 9-12) Thus, P-TEFb has separate functions to promote transcription, one by blocking the action of transcriptional repressors and another by mediating phosphorylation of the CTD during the productive phase of transcription elongation. **While P-TEFb activity is typically localized to one complex in higher eukaryotes, there are two homologues that  recapitulate  the  activities  in  Saccharomyces  cerevisiae**:  the  Bur1/Bur2  and  the  Ctk kinase complexes (consisting of Ctk1, Ctk2 and Ctk3) (Fig. 1).

Here are a couple papers that talk about the distribution of 7SK and the fact that it was originally identified due to its abundance, so I agree it's appropriate to add the taxon constraint at this time and it can be removed if we learn otherwise.

[Peterlin BM, et al. 2012. **7SK snRNA: a noncoding RNA that plays a major role in regulating eukaryotic transcription.** Wiley Interdiscip Rev RNA. 3(1):92-103.](https://pubmed-ncbi-nlm-nih-gov.ezproxy.jax.org/21853533/) 
> The human 7SK small nuclear RNA (snRNA) is an abundant noncoding RNA whose function has been conserved in evolution from invertebrates to humans.


[Yazbeck AM, Tout KR, Stadler PF. 2018. **Detailed secondary structure models of invertebrate 7SK RNAs.** RNA Biol. 15(2):158-164.](https://pubmed-ncbi-nlm-nih-gov.ezproxy.jax.org/29219696/)

> The 7SK snRNA is a Pol-III transcript in animals with a typical length of about 330nt [1,2]. Its sequence is very well conserved in vertebrates [3,4], but shows a high level of variability in invertebrates [5,6]. Due to its abundance it has been known since the 1960s.

**Comment by krchristie** [comment] 2020-09-16 20:44
reopened until I confirm that taxon constraint propagates like I expect

**Comment by krchristie** [comment] 2020-09-17 20:05
Taxon constraint looks good so closing.

**Closed by krchristie** 2020-09-17 20:05 UTC
Labels: FlyBase, New term request, taxon constraints

**Comment by hattrill** [comment] 2020-09-18 06:51
Thanks, @krchristie 👍
