### ISSUE TITLE
add parent to establishment of ER localization

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16825] opened 2018-12-21 09:32 UTC
Hi 

please would you add the parent term  GO:0046907 intracellular transport to GO:0051686 establishment of ER localization and to  GO:0036465
synaptic vesicle recycling. These would be is_a relations.

GO:0046907 intracellular transport 
> is a child GO:0051686 establishment of ER localization
> is a child GO:0036465 synaptic vesicle recycling

for GO:0036465 synaptic vesicle recycling the current parent term  GO:0006810 transport would then be redundant and would need to be removed.

This would be helpful for the SynGO project

Thanks
Ruth

**Comment by ValWood** [comment] 2018-12-21 11:16
GO:0051686 establishment of ER localization
shouldn't have the transport parent, because it refers also to retention, which is only localization, not transport 9directed movement).


v

**Comment by RLovering** [comment] 2018-12-21 11:31
Of course
thanks for spotting that, 

OK so I am just asking for
GO:0046907 intracellular transport
>    is a child GO:0036465 synaptic vesicle recycling

for GO:0036465 synaptic vesicle recycling the current parent term GO:0006810 transport would then be redundant and would need to be removed.

Thanks
Ruth

**Comment by ValWood** [comment] 2018-12-21 11:34
Yeah, tried that one once myself ;)

**Comment by vanaukenk** [comment] 2019-01-02 16:47
@RLovering 
Is 'synaptic vesicle recycling' considered a type of 'synaptic vesicle transport'?
If so, we could add the latter as a new parent and then 'synaptic vesicle recycling' would inherit the 'intracellular transport' parent.

![image](https://user-images.githubusercontent.com/1730534/50601897-a6981480-0e83-11e9-91d1-1c002a7725f0.png)

I guess one question is whether a synaptic vesicle minus neurotransmitter is still considered a synaptic vesicle.

**Comment by RLovering** [comment] 2019-01-02 17:10
Hi Kimberly

this is a good point. I will forward this ticket to SynGO

Ruth

**Comment by RLovering** [comment] 2019-01-02 18:22
email sent to Frank, Guus and Matthijs on 2 Jan 2019

Dear Frank, Guus and Matthijs

The GO now has the terms:

GO:0099504 synaptic vesicle cycle
A biological process in which synaptic vesicles are loaded with neurotransmitters, move to the active zone, exocytose and are then recycled via endocytosis, ultimately leading to reloading with neurotransmitters. PMID:15217342 

GO:0036465 synaptic vesicle recycling 
The trafficking of synaptic vesicles from the pre-synaptic membrane so the vesicle can dock and prime for another round of exocytosis and neurotransmitter release. Recycling occurs after synaptic vesicle exocytosis, and is necessary to replenish presynaptic vesicle pools, sustain transmitter release and preserve the structural integrity of the presynaptic membrane. Recycling can occur following transient fusion with the presynaptic membrane (kiss and run), or via endocytosis of presynaptic membrane. PMID:15217342 PMID:22026965 PMID:23245563 

both terms have the same reference PMID:15217342 see last entries in https://github.com/geneontology/go-ontology/issues/16825  

Please would you confirm whether these two terms are actually the same process, or whether one of these terms could be considered a child of the other. I noticed that the SynGO ontology only has GO:0099504 synaptic vesicle cycle.

Also, we were wondering whether ‘a synaptic vesicle minus neurotransmitter is still considered a synaptic vesicle’, your thoughts on this would also be appreciated.

Many thanks

Ruth

**Comment by RLovering** [comment] 2019-01-07 12:56
Email from Frank:
On 07/01/2019, 08:52, "Koopmans, F.T.W." <frank.koopmans@vu.nl> wrote:

    Hi Ruth and Kimberly,
    
    'synaptic vesicle recycling' is not the same as 'synaptic vesicle cycle'. From the definition for 'synaptic vesicle recycling' it seems like this is a child term of 'synaptic vesicle cycle' since the exocytosis process is not included in the former. We use the cycle term as a grouping term for SV related processes within the SynGO goslim and are happy to keep things this way (within our goslim).
    
    It may be difficult to differentiate between both terms experimentally btw; what type of experimental evidence does one encounter in literature that justifies annotating against 'synaptic vesicle recycling' where 'synaptic vesicle cycle' and more specific child terms are not applicable? We found no use-cases thereof and excluded this term in our goslim.
    
    > I guess one question is whether a synaptic vesicle minus neurotransmitter is still considered a synaptic vesicle.
    
    Within SynGO, we do consider SVs without neurotransmitter as SVs. In our current CC model we do not differentiate between the many states a SV can be in.
    
    Best,
    Frank

**Comment by RLovering** [comment] 2019-01-08 13:55
Hi Frank

One more question. I think there is a problem with the 'cellular' parent terms for GO:0099504 synaptic vesicle cycle because exocytosis and endocytosis involve extracellular peptides. The GO term GO:0032940 secretion by cell does not have any 'cellular' parent terms (https://www.ebi.ac.uk/QuickGO/term/GO:0032940). Consequently, I think we should remove the parent term GO:0051649 establishment of localization in cell from GO:0099504 synaptic vesicle cycle. 

GO:0099504 synaptic vesicle cycle would still have the parent term GO:0051234 establishment of localization
But it would also lose the parent term: GO:0051641 cellular localization

Would this be OK with SynGO?

Thanks

Ruth

**Comment by BarbaraCzub** [comment] 2019-01-14 12:34
Frank (SynGO team) confirmed that this would be a suitable solution (email to Ruth, 14/01/2019). @vanaukenk, I will go ahead and make the changes suggested by @RLovering unless you have any further comments or suggestions?
Thanks,
Barbara

**Comment by BarbaraCzub** [comment] 2019-01-15 14:54
https://github.com/geneontology/go-ontology/issues/15990

**Comment by BarbaraCzub** [comment] 2019-02-04 18:00
Hi Ruth, 

I have spent this afternoon working on the #15990 ticket and have been making a few changes. The reference (PMID:15217342) provided for those terms provides a really good overview, and Figure 1 together with Figure 3 (more detailed) in this reference show how synaptic vesicle recycling is a part of synaptic vesicle cycle. 

Based on this review, I would keep the term 'GO:0051649 establishment of localization in cell' as a parent of 'GO:0099504 synaptic vesicle cycle'. I think it is automatically inferred from the process occurring in the presynapse, because I cannot see it as a parent in Protege (screenshot below):

![screenshot 2019-02-04 at 17 52 28](https://user-images.githubusercontent.com/16541096/52226728-ad141480-28a5-11e9-812d-ced6523d6b2e.png)

However, following the same logic, based on this presynaptic localisation, both 'GO:0099504 synaptic vesicle cycle' and 'GO:0036465 synaptic vesicle recycling' should probably be descendants of 'intracellular transport' (like 'GO:0036466 synaptic vesicle recycling via endosome' is) and not 'transport'. This also appears to be in agreement with PMID:15217342. However, the probable reason why this has not be done is that 'GO:0099504 synaptic vesicle cycle' will include endocytosis and exocytosis, which, as you pointed out, involve extracellular aspects.

Therefore, I am going to close this ticket now, because a larger endocytosis/exocytosis project would be required to resolve this.

Thanks,
Barbara

**Closed by BarbaraCzub** 2019-02-04 18:00 UTC
Labels: Other term-related request, quick fix
