### ISSUE TITLE
Taxon constraint: post-transcriptional gene silencing by RNA

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22988] opened 2022-03-08 10:28 UTC
Please provide as much information as you can: 

* **GO term ID label:**

https://www.ebi.ac.uk/QuickGO/term/GO:0035194
post-transcriptional gene silencing by RNA

* **Request to add a taxon constraint:**

Please add taxon constraints:

Never in S . pombe
Never in S. cerevisiae.

(we can't add never in fission yeast, (I.e all Schizosaccharomyces, because the pathway is present in S . japonicus
[Separable roles for RNAi in regulation of transposable elements and viability in the fission yeast Schizosaccharomyces japonicus.](https://pubmed.ncbi.nlm.nih.gov/35226668/)
Chapman E, Taglini F, Bayne EH.
PMID: 35226668

**Comment by pgaudet** [comment] 2022-03-09 07:06
Duplicate of #22771 - this is done.

**Closed by pgaudet** 2022-03-09 07:06 UTC
Labels: transcription, taxon constraints
