### ISSUE TITLE
Small fixes GO:0097278 complement-dependent cytotoxicity into GO:0006956 complement activation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18715] opened 2020-01-31 14:43 UTC
Hello, 

GO:0097278 complement-dependent cytotoxicity 
is the readout of GO:0006956 complement activation, according to the respective definition: 

* GO:0097278 complement-dependent cytotoxicity: Lysis of a cell resulting from triggering of the complement cascade. An example can be seen with complement activation and subsequent lysis of a bacterial cell as a result of the binding of IgM to the cell surface followed by the binding of complement proteins to that antibody.
Has about 25 EXP annotations
 
* GO:0006956 complement activation: Any process involved in the activation of any of the steps of the complement cascade, which allows for the direct killing of microbes, the disposal of immune complexes, and the regulation of other immune processes; the initial steps of complement activation involve one of three pathways, the classical pathway, the alternative pathway, and the lectin pathway, all of which lead to the terminal complement pathway.
Has about 125 EXP annotations

@addiehl Is that OK with you ? 

Thanks, Pascale

**Comment by addiehl** [comment] 2020-01-31 15:53
Complement-dependent cytotoxicity is one possible outcome of complement activation.  It does not occur in all cases, and other outcomes, such as opsonization of target cells by complement fragments, may occur instead or co-occur.

But I am not sure of what question you are asking or if you are proposing a change here?

**Comment by ValWood** [comment] 2020-01-31 20:14
"outcomes of a set of processes" - this sounds more like a phenotype than a process?

**Comment by addiehl** [comment] 2020-01-31 20:26
Pascale chose the word outcome, not me.  I didn't realize it was some kind of trick question!

Complement-dependent cytotoxicity is definitely a distinct biological process, mediated by the membrane attack complex, which has a distinct set of proteins associated with it separate from complement activation.

These terms should definitely not be merged.  I am willing to provide a different definition for GO:0097278 if needed.

**Comment by ValWood** [comment] 2020-01-31 22:18
probably a clearer definition is required.

Current co-occurring terms for "membrane attack complex"

Co-occurring Term	PR	S%	#Together	#Compared
GO:0005579    membrane attack complex	53,922.63	100.00	2,348	2,348
GO:0006956    complement activation	19,333.53	29.30	1,446	4,033

GO:0005579    membrane attack complex co-annotation with GO:0097278  = 0

**Comment by pgaudet** [comment] 2020-02-03 15:13
@addiehl If you have a better definition that'd be great. 

Thanks, Pascale

**Comment by addiehl** [comment] 2020-02-03 18:44
Give me a few days, unfortunately I have some other more pressing obligations for the rest of the day.

**Comment by addiehl** [comment] 2020-02-06 17:38
Proposed new definition for complement-dependent cytotoxicity:
Cell killing caused by the membrane attack complex formed following complement activation.

The proposed definition matches the existing logical definition, though we could add the MAC as a participant.

existing logical definition
cell killing
 and 'has part' some 'complement activation'

proposed new logical definition
cell killing
 and 'has part' some 'complement activation'
 and 'has participant' some 'membrane attack complex'

The original request and definition for this term came from Randi Vita of the Immune Epitope Database @rvita #9440 and thus I want to make sure these textual and logical definitions is okay by her.

**Comment by rvita** [comment] 2020-03-02 18:49
I agree with Alex that those terms should definitely not be merged. We use them in the IEDB as distinct processes. I agree with the proposed definition edits by @addiehl  Thanks

**Comment by pgaudet** [comment] 2020-03-05 18:31
Thanks for the feedback ! 

Is GO:0097278 complement-dependent cytotoxicity
always 'killing of other organism' ?

**Comment by pgaudet** [comment] 2020-03-05 18:37
> cell killing
and 'has part' some 'complement activation'
and 'has participant' some 'membrane attack complex'

Those are not logical definitions - they are subclasses. I am not sure they fit the 'necessary and sufficient' criteria for being logical definitions, so I will leave them as subclasses.

**Comment by addiehl** [comment] 2020-03-05 18:58
Is GO:0097278 complement-dependent cytotoxicity
always 'killing of other organism' ?

No, the data is complicated but it seems that the same mechanism is sometimes deployed for killing of certain types of autologous tumor cells: PMID:28920587

**Comment by deustp01** [comment] 2020-03-05 19:04
And aren't there some autoimmune phenomena that involve complement-dependent killing of self? But does the restriction of GO to normal processes put these cases out of scope?

**Comment by addiehl** [comment] 2020-03-05 19:18
Killing of tumors by the immune system is a normal, evolutionarily selected, function of the immune system.  And some auto-immune phenomena are important parts of self-regulation of the immune system.

**Comment by pgaudet** [comment] 2020-03-05 19:42
OK thanks, I've added the reference.

**Closed** 2020-03-05 19:50 UTC
Labels: multi-species process

**Comment by ukemi** [comment] 2020-03-05 19:52
> Killing of tumors by the immune system is a normal, evolutionarily selected, function of the immune system.

Thank goodness.
