### ISSUE TITLE
Roles issue: Remove L-glumatate from logical definitions of GO:0015813 L-glutamate transmembrane transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19182] opened 2020-03-28 07:01 UTC
This is a test to address the issue reported here https://github.com/geneontology/go-site/issues/1426 (and elsewhere!) 

ChEBI considers L-glumatate a neurotransmitter. I will remove L-glumatate from logical definitions of GO:0015813 L-glutamate transmembrane transport, and check in snapshot if it is still failing taxon checks for E. coli. 
Pascale

**Comment by pgaudet** [comment] 2020-03-28 07:06
Removed logical definition: 

-intersection_of: GO:0015800 ! acidic amino acid transport
-intersection_of: results_in_transport_across GO:0016020 ! membrane
-intersection_of: transports_or_maintains_localization_of CHEBI:29985 ! L-glutamate(1-)

Added subclass: 
+is_a: GO:0055085 ! transmembrane transport

**Comment by alanbridge** [comment] 2020-03-29 13:55
You don't plan to remove these permanently do you? The issue is really the ChEBI role, which lacks any of the necessary context and shouldn't be used to routinely make inferences. 

Terms like GO:0015813 L-glutamate transmembrane transport (and many more enzyme functions) will have corresponding Rhea xrefs too. You might even use Rhea to construct logical definitions for these, but the roles of the ChEBIs that participate in those Rhea reactions won't necessarily apply in any particular system where the reaction occurs either. 

Like for GO:0015813 L-glutamate transmembrane transport 
https://www.rhea-db.org/reaction?id=29027
2 H(+)(in) + L-glutamate(in) = 2 H(+)(out) + L-glutamate(out)

Can't you just ignore the role ontology of ChEBI completely?

**Comment by ValWood** [comment] 2020-03-29 15:07
> Can't you just ignore the role ontology of ChEBI completely?

That's what I don't understand either.  That will fix all the problems.

**Comment by pgaudet** [comment] 2020-03-30 07:06
Right, it won't fix all problems. I was trying to see if we can fix the most pressing problems, since this is taking longer than expected. 

@alanbridge right now I only fixed a BP term; as far as I know we only link  RHEA reactions to Moecular Functions, right ? 

Thanks, Pascale

**Comment by alanbridge** [comment] 2020-03-30 07:21
Yes that is true, Rhea is for MFs only, but this could also generate a multitude of violations too if later you use Rhea to generate logical definitions for GO MF terms.

All the best, Alan

**Comment by pgaudet** [comment] 2020-03-30 07:26
Not sure what the violations would be but anyway this is a temporary fix.

**Comment by alanbridge** [comment] 2020-03-30 08:33
I thought the issue here was that L-glutamate has role neurotransmitter.

_ChEBI considers L-glumatate a neurotransmitter. I will remove L-glumatate from logical definitions of GO:0015813 L-glutamate transmembrane transport, and check in snapshot if it is still failing taxon checks for E. coli._

wouldn't the same issue arise with MFs? 

Consider this rice protein - https://uniprot.org/uniprot/Q0JKD0. This produces glutamate (annotated with https://www.rhea-db.org/reaction?id=13753). If you created a GO term equivalent to Rhea:13753 and annotated this protein with it, wouldn't you then infer that the function of this rice protein is neurotransmitter biosynthesis (via the ChEBI role)? Or did I misunderstand?

**Comment by cmungall** [comment] 2020-03-30 15:10
I agree. We should never remove a valid logical definition, even temporary. 

We have had the fix for this instance for years - we should *never* be using the CHEBI neurotransmitter class in a logical definition. We have a perfectly good GO class for neurotransmission.

**Comment by pgaudet** [comment] 2020-03-30 15:25
OK, restoring this.

**Closed** 2020-03-30 15:51 UTC
Labels: taxon constraints
