### ISSUE TITLE
pyramidal neuron migration is implicitly mammalian even though it applies to Aves

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#21478] opened 2021-05-20 01:05 UTC
noticed by @balhoff 

```
id: GO:0021852
name: pyramidal neuron migration
namespace: biological_process
def: "The migration of pyramidal a neuron precursor from the ventricular zone to the correct layer of the cerebral cortex." [GO_REF:0000021, GOC:cls, GOC:dgh, GOC:dph, GOC:jid, PMID:12626695]
synonym: "projection neuron migration" RELATED [PMID:12626695]
is_a: GO:0001764 ! neuron migration
***is_a: GO:0021801 ! cerebral cortex radial glia guided migration***
intersection_of: GO:0016477 ! cell migration
intersection_of: results_in_movement_of CL:0000598 ! pyramidal neuron
relationship: part_of GO:0021860 ! pyramidal neuron development
```

Note the highlighted hidden GCI

technically we should obsolete and make 2 new terms

but it may be acceptable to rename this ''cerebral cortex pyramidal neuron migration" and make a more general grouping for pyramidal neuron migration across amniotes

or we could look at having a single concept and generalizing the concept of cerebral cortex layers are their avian homologs, but this is harder

**Comment by balhoff** [comment] 2021-05-20 02:14
Beat you to it: #21476

**Comment by pgaudet** [comment] 2021-05-28 05:40
Duplicate of #21476

**Closed by pgaudet** 2021-05-28 05:40 UTC
