### ISSUE TITLE
NTR: aerial mycelium formation

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12659] opened 2016-09-13 20:45 UTC
A scan of Google search results and publications refer to "aerial mycelium" with "formation" and not "development." Aerial mycelia are distinct from vegetative mycelia. In some fungal species, spores develop from the tips of aerial mycelia.

NTR:  aerial mycelium formation
Def:  Growth of hyphae in an upward or outward direction from the surface of the substrate, and from which propagative spores develop in or on characteristic structures that are distinctive for various fungal species.
PMID:12832397
Note that this term may be used to replace the ambiguous term GO:0043581 mycelium development

**Comment by paolaroncaglia** [comment] 2016-09-22 16:50
Note for self: also see http://wiki.geneontology.org/index.php/Ontology_meeting_2016-09-22#FAO_update and https://github.com/obophenotype/cell-ontology/issues/447

**Comment by paolaroncaglia** [comment] 2016-10-11 14:54
Hi @dianeoinglis ,

Were you planning to add a FAO term for ‘aerial mycelium’, under FAO:0000011 ‘mycelium’?
If yes, I’ll use the new FAO term for the logical definition of GO:NEW 'aerial mycelium formation', see http://wiki.geneontology.org/index.php/Ontology_meeting_2016-09-22#FAO_update.
If not, or if it’s more urgent to have the GO term so @tberardini  can send the obsoletion notice for https://github.com/geneontology/go-ontology/issues/12613, I’ll add the GO term and we’ll define it logically later on.

**Comment by dianeoinglis** [comment] 2016-10-13 09:09
Yes. Good idea. to add "aerial mycelium" to the FAO under "mycelium" as you suggest. 

I need to communicate with @cmungall about editing the FAO-obo on a PC that I'm using while my Mac laptop is in repair. Would it work if I assigned the next FAO term ID and definition in a spreadsheet and formally edit the FAO in the near future?

I think it fine to send out the obsoletion notice for "mycelium development" and include a description of the three terms that can be used as replacements. 

The term "substrate mycelium formation" was requested and approved of by Martin Urban at PhiBase. I will create a NTR for this term asap so that you can include it on the list of proposed replacement terms.

**Comment by cmungall** [comment] 2016-10-13 11:35
On 13 Oct 2016, at 5:09, Diane O Inglis wrote:

> I need to communicate with   @cmungall   about editing the FAO-obo 
> on a PC that I'm using while my Mac laptop is in repair. Would it work 
> if I assigned the next FAO term ID and definition in a spreadsheet and 
> formally edit the FAO in the near future?

I am the worst person to advise on using github with a PC (although 
Protege or OE should work fine). Do we have a backup person? If it's 
just a handful of terms over a short term one of use can add.

**Comment by dianeoinglis** [comment] 2016-10-14 01:07
Hi Chris,

For now just a few terms can be added but after looking at some of the
parentage and definitions there are quite a few terms that should be
updated or modified, or moved under a different parent. I will create
tickets for each proposed change. Those can wait.

Another question...is it best to make a pull request then merge or how is
modification and saving to the repository best handled?

Thanks!
Diane

**Comment by paolaroncaglia** [comment] 2016-10-14 13:15
Hi @dianeoinglis,

I added ‘aerial mycelium formation’ as follows: 

[Term]
id: GO:0097736
name: aerial mycelium formation
namespace: biological_process
def: "The process by which hyphae grow in an upward or outward direction from the surface of the substrate; from there, propagative spores develop in or on characteristic structures that are distinctive of some fungal and bacterial species. The species that form an aerial mycelium develop conidiophores at the ends of the aerial hyphae." [GOC:di, PMID:12832397]
synonym: "aerial hyphal growth" RELATED []
synonym: "fertile mycelium formation" RELATED []
is_a: GO:0019954 ! asexual reproduction
is_a: GO:0048856 ! anatomical structure development
relationship: only_in_taxon NCBITaxon_Union:0000020 ! Fungi or Bacteria

I’m not sure that the parentage is fully correct. 
- [ ] Should ‘aerial mycelium formation’ be is_a ‘anatomical structure formation involved in morphogenesis’ instead of ‘anatomical structure development’?

Also, when you create the FAO term for ‘aerial mycelium’, please post its ID here, and 
- [ ] I will add a logical axiom to GO:0097736 ‘aerial mycelium formation’

Lastly, may I please suggest that discussion on FAO terms themselves and editing practices is moved to a separate repository if there’s one, to avoid confusion? :-)

Thanks,

Paola

**Comment by paolaroncaglia** [comment] 2016-11-25 14:47
Note for self: based on the discussion in https://github.com/geneontology/go-ontology/issues/12745, I think the current parentage of 'aerial mycelium formation' is fine. I am setting this ticket to 'pending' while waiting for the FAO term for ‘aerial mycelium’.

**Comment by paolaroncaglia** [comment] 2016-12-12 17:02
Wrapping up, the only action item left for this ticket is
- [ ] when a FAO term is created for ‘aerial mycelium’, its ID can be used to add a logical axiom to GO:0097736 ‘aerial mycelium formation’.

**Comment by paolaroncaglia** [comment] 2017-02-16 11:49
Hi @ukemi, another one - 
I’ve completed my tasks for this ticket, and the only thing left to do (low priority) is to add a logical definition if/when a FAO term is created (details above). Therefore I will now unassign myself from this ticket. However, since unassigned tickets tend to fall through the cracks when they’re not recent, I will assign it to you (as main ontology editor at this stage), and you can then hand it over to others if and as appropriate. Thanks.

**Comment by ukemi** [comment] 2018-02-26 20:12
@dianeoinglis , I don't see this term either.

**Comment by dianeoinglis** [comment] 2018-03-05 07:44
This GO term is awaiting the creation of the FAO term, 'aerial mycelium.' Will be done soon.

**Comment by pgaudet** [comment] 2018-10-01 19:15
@mah11 an you please add the term in FAO? 

Thanks, Pascale

**Comment by mah11** [comment] 2018-10-02 09:12
watch https://github.com/obophenotype/fungal-anatomy-ontology/issues/11

**Comment by pgaudet** [comment] 2018-11-08 12:14
https://github.com/geneontology/go-ontology/pull/16592

**Closed by pgaudet** 2018-11-08 12:14 UTC
Labels: New term request, development, external dependencies, low priority
