### ISSUE TITLE
NTR: viral predation

### ISSUE THREAD

**Issue by diatomsRcool** [geneontology/go-ontology#17740] opened 2019-08-20 14:59 UTC
I'm not sure if this belongs in GO. Please see discussion here.
https://github.com/EcologicalSemantics/ecocore/issues/45

**Comment by ValWood** [comment] 2019-08-20 15:03
This sounds out of scope. How would you define it (is it the same as infection?)

We have "pathogenesis" but we are not even sure this is in scope.

Is "interaction with host" 
https://www.ebi.ac.uk/QuickGO/term/GO:0051701
or one of the child terms useful?

**Comment by ValWood** [comment] 2019-08-20 15:06
discussion for pathogenesis
https://github.com/geneontology/go-ontology/issues/11057
and others.

**Comment by diatomsRcool** [comment] 2019-08-20 17:20
Pathogenesis sounds interesting. The emphasis on viral predation is the actual death (lysis) of the infected cell.  Just like other types of predation lead to the death of the prey. Maybe this is something that follows pathogenesis? Viral predation is very important in marine planktonic communities. @pbuttigieg this was a term you added. Do you have an opinion?

**Comment by pgaudet** [comment] 2019-08-20 17:36
The closest term might be GO:0019058 viral life cycle? 

http://amigo.geneontology.org/amigo/term/GO:0019058

**Comment by ukemi** [comment] 2019-08-20 17:38
GO:0044659---The killing by a virus of a cell in its host organism by means of the rupture of cell membranes and the loss of cytoplasm. Source: GOC:jl

**Comment by pgaudet** [comment] 2019-08-20 17:43
I am not sure how EcologicalSemantics and GO terms would align. 

What I understand if that this term is meant to capture how a viral gene (or a whole virus) would affect its host; is that right ? 

In GO we do this very differently: we capture what each organism does: the virus infects the cell in order to survive, the cell lyses, but that is not the goal of the infection; the goal of the infection is for the virus to reproduce. 

@cmungall these would not be 'exact' mappings; would they ?

**Comment by diatomsRcool** [comment] 2019-08-20 17:47
> GO:0044659---The killing by a virus of a cell in its host organism by means of the rupture of cell membranes and the loss of cytoplasm. Source: GOC:jl

Hey that's it! Only the definition assumes that the cell that is dying is part of a multi-cellular organism. That is not the case in a planktonic context.

**Comment by ValWood** [comment] 2019-08-20 17:48
Pathogenesis may disappear from GO (if I have my way!), it isn't a process, it's the outcome of processes, and its a "feature" of an organism not a process. An organism can be pathogenic or not pathogenic this is binary.  Pathogenesis is the *ability* of a pathogen to cause disease (i.e. not a process). The extent of disease/pathogenicity is  "virulence" and this can vary from individual to individual.  But virulence is a phenotypes not a processes.

Note that a term referring "cell death of an infected cell" won't be a GO process, because that isn't the 'normal purpose' of the pathogen-host interaction, (unless the necrosis is intentional for example in necrotizing fungi).

I also  think Pascale's suggestion of "viral process" might be closer.

**Comment by pgaudet** [comment] 2019-08-20 17:48
Why do you say it's implies a multicellular organism ?

**Comment by diatomsRcool** [comment] 2019-08-20 17:53
> The killing by a virus of a cell in its host organism by means of the rupture of cell membranes and the loss of cytoplasm.

"of a cell in its host organism" sounds like there are multiple cells in the organism. As opposed to killing the organism, which is what would happen with a single-celled organism. I would write "The killing by a virus of a cell by means of the rupture of cell membranes and the loss of cytoplasm."

**Comment by diatomsRcool** [comment] 2019-08-20 17:56
It's sounding like the answer to my question is that this is out of scope for GO

**Comment by pgaudet** [comment] 2019-08-20 18:22
An organism can be singled-celled.

**Comment by diatomsRcool** [comment] 2019-08-20 18:43
Yes, that's my point.

**Comment by cmungall** [comment] 2019-08-20 18:56
I agree, "cell in a host organism" sounds odd when applied to bacteria. It requires a reflexive reading of "in" which is something only an ontology geek would do. I prefer Anne's definition. Hostness is implicit.

Or we could be explicit "kills single-celled organisms or cells in a multi-cellular organism" but that seems verbose.

Regarding the broader question, with my OBO hat on I don't want to see ecocore mapped to GO, it should be connected via defined relationships. From what I am hearing it sounds like viral predation could be an exact synomnym for "GO:0019058 viral life cycle"? Or is it only a part of the life cycle? For processes we should always have a clear idea of begininning and end (whether on GO or EcoCore)

**Comment by ukemi** [comment] 2019-08-21 14:29
I will modify the def and close this as for the mapping of ecocore, I think that is a separate issue and may well be a separate project.

**Comment by ukemi** [comment] 2019-08-22 16:19
Not the first time @cmungall has referred to me as an ontology geek. Fix is in, if you think we should add a synonym, please reopen.

**Closed** 2019-08-22 16:35 UTC
Labels: multi-species process
