### ISSUE TITLE
Missing parent: lots of mitochondrial transmembrane transport subclass missing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26201] opened 2023-10-02 14:23 UTC
* **GO term ID and label for which you request a new superclass**

mitochondrial ADP transmembrane transport
mitochondrial tricarboxylic acid transmembrane transport (GO:1990546)
mitochondrial S-adenosyl-L-methionine transmembrane transport
mitochondrial magnesium ion transmembrane transport (GO:0045016)
mitochondrial pyruvate transmembrane transport (GO:0006850)
mitochondrial coenzyme A transmembrane transport
mitochondrial guanine nucleotide transmembrane transport (GO:0140140)
mitochondrial thiamine pyrophosphate transmembrane transport (GO:1990545)
mitochondrial phosphate ion transmembrane transport (GO:1990547)
mitochondrial L-ornithine transmembrane transport (GO:1990575)
mitochondrial NAD transmembrane transport (GO:1990549)
mitochondrial isopropylmalate transmembrane transport (GO:1990556)
mitochondrial oxaloacetate transmembrane transport (GO:1990555)
mitochondrial sulfate transmembrane transport (GO:1990557)
mitochondrial ATP transmembrane transport (GO:1990544)
mitochondrial alpha-ketoglutarate transmembrane transport (GO:1990550)
mitochondrial 2-oxoadipate transmembrane transport (GO:1990551)
mitochondrial 3'-phospho-5'-adenylyl sulfate transmembrane transport (GO:1990554)
mitochondrial 5'-adenylyl sulfate transmembrane transport (GO:199
oligopeptide export from mitochondrion (GO:0090374)

* **New superclass (parent) suggested**

All of these used to be subclasses of "mitochondrial transmembrane transport"

These are still:
https://www.pombase.org/term/GO:1990542

**Comment by edwong57** [comment] 2023-10-05 19:47
It looks like this happened because the logical definition of id GO:1990542: mitochondrial transmembrane transport was changed in this issue #25275 so that GO:0160007 | glutathione import into mitochondrion would become a child of GO:1990542. Changing the logical definition  of GO:1990542 back to:
<img width="710" alt="image" src="https://github.com/geneontology/go-ontology/assets/526428/ae946ac1-587e-43d0-9bdc-18c5b4e3026a">

will result in all of the above terms become children when the reasoner is run. The logical definition of GO:016007 would have to be changed for the reasoner to make it a child of mitochondrial transmembrane transport. 

I don't think it makes sense to define the target start and end locations of this term since the term definition says that the solute can go into, out of or, or within a mitochondrion. @ValWood @pgaudet, are there other reasons for keeping the start/end points in the logical definition for this term that I'm not aware of? or is there a better solution?

**Comment by ValWood** [comment] 2023-10-06 07:27
I don't fully understand the logical def construction (Unfortunately! )

**Comment by edwong57** [comment] 2023-10-07 00:11
Ok, I changed the logical definition for GO:1990542 to:
![image](https://github.com/geneontology/go-ontology/assets/526428/8ab154ed-bb88-4d8d-bff6-08f6a4529267)

So, now all the terms are back as children under mitochondrial transmembrane transport. and, the other terms from https://github.com/geneontology/go-ontology/issues/25275 are still there. Before I commit and do a PR request, is this complicated logical definition ok?

**Comment by cmungall** [comment] 2023-10-07 02:06
It looks like there are too many levels of nesting

I don't think the yaml spec for this has the to from or in h relation

**Comment by edwong57** [comment] 2023-10-09 01:40
Ok. The terms above have 'results in transport to from or in' some 'mitochondrion' in the logical definition. mitochondrial 2-oxoadipate transmembrane transport (GO:1990551) for example:
![image](https://github.com/geneontology/go-ontology/assets/526428/14185d15-1e11-4ba5-ac02-4344081a5b89)

**Comment by pgaudet** [comment] 2023-10-09 07:12
We need to define design patterns for transport first. Right now there are many different logical definitions, leading to many inconsistencies in classification all over the transport branch.

**Comment by pgaudet** [comment] 2023-10-09 15:32
@ValWood is this OK with you?

**Comment by ValWood** [comment] 2023-10-10 07:04
I think that could work, at least most are importers. I will double-check today.
But in this case should
mitochondrial tricarboxylic acid transmembrane transport (GO:1990546) -> import too?
I was looking at this yesterday and the couple I looked at had no import version.

**Comment by pgaudet** [comment] 2023-10-10 07:06
The question is, how many versions do we want?? 

- transport
- - import
- - export?? 
It would be nice to know whether both import and export exist before creating all the terms

**Comment by pgaudet** [comment] 2023-10-11 10:14
TO DO: 

- [ ] Create a new term, import into the mitochondrion, with LD: 
transport
 and ('has target start location' some cytosol)
 and ('has target end location' some 'mitochondrial matrix')
 and ('results in transport across' some 'mitochondrial membrane')
**(to be confirmed with @balhoff )**

- [ ] change LD of [mitochondrial transmembrane transport](http://purl.obolibrary.org/obo/GO_1990542)
to 
transport
and ('results in transport across' some 'mitochondrial membrane')

**Comment by balhoff** [comment] 2023-11-30 20:41
@edwong57 those look good to me.

**Comment by edwong57** [comment] 2023-11-30 21:45
I added new import into mitochondrion and export into mitochondrion terms, modified LD for mitochondrial transmembrane transport. Seems like the reasoner moves all the listed terms back under mitochondrial transmembrane transport. I am wondering if we should make the LD of 'import into the mitochondrion' and 'export from the mitochondrion' a little more generic and use 'mitochondrion' rather than 'mitochondrial matrix'? I would expect that 'iron-sulfur cluster export from the mitochondrion' to be a child of 'export from the mitochondrion' and it isn't because the target start location is defined as 'mitochondrion' and not 'mitochondrial matrix.' I haven't committed the PR if you want to take a look - https://github.com/geneontology/go-ontology/pull/26536

**Comment by pgaudet** [comment] 2023-12-01 07:48
To discuss on the next ontology call? 

It doesnt look like we have a design pattern for mitochondrial import/export, or more generally,  import/export into/from organelle. 

Also: @balhoff , did we not say that for transmembrane transport, the genera would be 'transmembrane transport', and not 'transport' (sorry, I know I wrote 'transport' above). 

For the example you give @edwong57, 'iron-sulfur cluster export from the mitochondrion', the LD seems incorrect, I should have added 'start location mitochondrial matrix', if you look at the paper PMID: 31040179 they talk about transcport across the inner membrane into the cytosol. 

It will be really useful to have the design patterns sorted out! 

Thanks, 
Pascale

**Closed** 2023-12-11 19:55 UTC
Labels: protein complex, missing parentage

**Comment by ValWood** [comment] 2023-12-15 13:40
Looks great, everything came back correctly.
v
