### ISSUE TITLE
GO:0036185 13-lipoxin reductase activity has a narrow match RHEA:41592?

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#21879] opened 2021-07-28 23:24 UTC
Is this a good RHEA match for GO:0036185?

GO:0036185 13-lipoxin reductase activity 
Definition: Catalysis of the reaction: 15-oxolipoxin A4 + NAD(P)H + H+ = 13,14-dihydro-15-oxolipoxin A4 + NAD(P)+.

XREF Reactome:R-HSA-2161844 that has
Input: 15-oxolipoxin A4 [ChEBI:63992] + H+ +  NADPH
Output: 13,14-dihydro-15-oxolipoxin A4 [ChEBI:63993] + NADP+

RHEA:41592
15-oxo-(5S,6R)-dihydroxy-(7E,9E,11Z,13E)-eicosatetraenoate + H+ + NADH = 15-oxo-(5S,6R)-dihydroxy-(7E,9E,11Z)-eicosatrienoate + NAD-

15-oxo-(5S,6R)-dihydroxy-(7E,9E,11Z,13E)-eicosatetraenoate is CHEBI:73811 15-oxolipoxin A4(1−) DEF A hydroxy fatty acid anion obtained by deprotonation of the carboxy function of 15-oxolipoxin A4; major species at pH 7.3.
15-oxo-(5S,6R)-dihydroxy-(7E,9E,11Z)-eicosatrienoate is CHEBI:78325) 13,14-dihydro-15-oxolipoxin A4(1−) DEF A hydroxy fatty acid anion obtained by deprotonation of the carboxy function of 13,14-dihydro-15-oxolipoxin A4; major species at pH 7.3.

**Comment by pgaudet** [comment] 2021-07-29 08:58
Hi @raymond91125 

Looking that the one gene experimentally annotated to this term - Pig UniProt:Q29073, this is a prostaglandin reductase, mapped in UniProt to EC:1.3.1.48 (linked to 2 terms, GO:0036132 13-prostaglandin reductase activity and GO:0047522 15-oxoprostaglandin 13-oxidase activity; both also used to annotate prostaglandin reductases)

The reference cited for the creation of the term, PMID:10837478, states that 15-Hydroxyprostaglandin dehydrogenase (15-PGDH) also catalyze the conversion of lipoxin A(4) (LXA(4)). So, according to our rule that the GO term should describe the specificity of the enzyme, I think these 3 GO terms represent a single GO MF - maybe 'icosanoid reductase activity' (CHEBI:23899) - in wikipedia icosanoids group prostaglandins, thromboxanes, leukotrienes, lipoxins, resolvins, and eoxins.
https://en.wikipedia.org/wiki/Eicosanoid 

At the level of the BP it may make sense to distinguish these 6 classes, but at the MF, if there is no specific enzyme, I think our guidelines would be to group them. 

Thanks, Pascale

**Comment by pgaudet** [comment] 2021-07-29 09:01
@nnouspikel any thoughts on this one?

**Comment by nnouspikel** [comment] 2021-08-05 07:45
Hi
According to 
ChEBI Ontology https://www.ebi.ac.uk/chebi/searchId.do?chebiId=78311
15-oxolipoxin A4(1−) (CHEBI:78311) is a hydroxy fatty acid anion (CHEBI:59835)
15-oxolipoxin A4(1−) (CHEBI:78311) is a icosanoid anion (CHEBI:62937)
15-oxolipoxin A4(1−) (CHEBI:78311) is a long-chain fatty acid anion (CHEBI:57560)
*
SwissLipids classification http://swisslipids.vital-it.ch/#/entity/SLM:000389596/
is a SLM:000501318 Lipoxins
is a SLM:000501332 Eicosanoid derivatives
*
in LipidMaps: https://www.lipidmaps.org/databases/lmsd/LMFA03040009?LMID=LMFA03040009
is a eicosanoids
*
EC:1.3.1.48 assigned to Q29073 (PTGR1_PIG):  https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=1.3.1.48
*
possible MF GO terms:
eicosanoid 13-reductase activity
eicosanoid Δ13-oxidoreductase activity
*
Hope it helps
Nevila

**Comment by raymond91125** [comment] 2021-08-05 23:35
I think the enzyme that GO:0036185 refers to is LTB4 12-HD/PGR leukotriene B4 12-hydroxydehydrogenase/15-Oxo-prostaglandin 13-reductase (EC 1.3.1.48, different from 15-PGDH 15-Hydroxyprostaglandin dehydrogenase)
PMID:15007077 says this enzyme catalyzes quite a few reactions in the inactivation pathways of LXA4, LTB4, PGE2 and PGF2alpha(same as that of PGE2).
![image](https://user-images.githubusercontent.com/619520/128432690-58f064d2-0a4f-41de-b3f7-b32f65d76b15.png)

**Comment by pgaudet** [comment] 2021-08-10 13:52
Interesting. EC: 1.3.1.48 is linked to 2 terms: 
GO:0036132 13-prostaglandin reductase activity 
GO:0047522 15-oxoprostaglandin 13-oxidase activity 

There is a comment in GO:0036132: 
'Note that this is the reverse of the reaction described in '15-oxoprostaglandin 13-oxidase activity ; GO:0047522'.' (and likewise in GO:0047522) 

@deustp01 This was requested by Reactome; do we need both reactions? Or is this contrary to our guidelines to only represent non-directional reactions?

**Comment by raymond91125** [comment] 2024-10-28 23:44
GO:0036185 13-lipoxin reductase activity appears to be an EXACT match of RHEA:41592. They share the same reference PMID:10837478.
RHEA:41592 is not linked to EC:1.3.1.48. I think it may be sufficient to add just RHEA:41592 as XREF to GO:0036185, not EC:1.3.1.48. @pgaudet Is that sufficient? Thanks.

**Comment by deustp01** [comment] 2024-10-30 14:30
The issue is whether the reaction is reversible under physiological conditions. Thus the activity of aldolase to cleave glucose 1,6 bisphosphate into triose phosphates, and to synthesize it from two triose phosphates rates a single GO term but separate GO terms are needed for the formation of glucose 6-phosphate from glucose and the formation of glucose from glucose 6-phosphate.
Sometimes an NAD(P)H-mediated reduction is reversible; sometimes it's not. I don't know the chemistry here but it looks like @sjm41 approved of the merger for the analogous reaction pair in https://github.com/geneontology/go-ontology/issues/28134 and I'll happily defer to his judgement here.
The number of reactions in Reactome is not a useful test here because we insist that all reaction instances be unidirectional. If a reaction is reversible, we create two instances, one for each direction even though both reaction instances are enabled by the same gene product and may use the same GO MF term.

**Comment by pgaudet** [comment] 2024-10-30 17:02
I am in favor of taking the same action as we did for  https://github.com/geneontology/go-ontology/issues/28134

@sjm41 OK with you ?

**Comment by raymond91125** [comment] 2024-10-30 17:27
> I am in favor of taking the same action as we did for #28134

Specifically, does that mean merging 3 terms (GO:0036185/GO:0036132/GO:0047522), into a 'new' term called "icosanoid reductase activity" that has 3 narrowMatch RHEA and 1 narrowMatch EC?

**Comment by sjm41** [comment] 2024-10-31 11:04
I'm no expert in this area, but:

- @pgaudet merging GO:0036132 13-prostaglandin reductase activity & GO:0047522 15-oxoprostaglandin 13-oxidase activity makes sense to me (though it looks like this has already happened - GO:0036132  is OBSOLETE with replaced_by: GO:0047522)

- @raymond91125 Yes, adding RHEA:41592 as an exactMatch xref to GO:0036185 13-lipoxin reductase activity looks good (if you navigate from RHEA to the ChEBI entries, the participant names in ChEBI match the names used in the GO def.)

**Closed** 2024-12-03 23:16 UTC
Labels: enzymes, go2rhea
