### ISSUE TITLE
cardiac muscle cell death

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12800] opened 2016-11-16 22:58 UTC
I would like to see "regulation of hydrogen peroxide-induced cardiac muscle cell death” added to the GO ontology under the parent term "regulation of hydrogen peroxide-induced cell death” (GO:1903205).  The definition could be "Any process that modulates the frequency, rate or extent of hydrogen peroxide-induced cardiac muscle cell death."  An example can be found in PMID:26333362.  The positive and negative versions of the new term would also be needed.  Thanks.

**Comment by thomaspd** [comment] 2016-11-16 23:19
I'm not convinced that the terms related to hydrogen-peroxide induced cell death are biological processes in the GO sense; they may instead refer to phenotypes.  Do we think there is a biological program that has evolved to kill a cell in response to H2O2 exposure?  Or do we think, for example, that H2O2 damages a cell and there are programs that protect against H2O2 damage, e.g. GO:0061691 (detoxification of hydrogen peroxide).

**Comment by tberardini** [comment] 2016-11-17 21:24
@paolaroncaglia:  can you weigh in on this please as it pertains to cell death?  The core term is 'cell death in response to hydrogen peroxide' and it looks like it was created for the PARL project (GOC:PARL).

http://amigo.geneontology.org/amigo/term/GO:0036474
(The inferred tree view is quite helpful.)

@slaulederkind : should we consider adding these new terms, it would follow that we'd also want to add the core BP term 'hydrogen peroxide-induced cardiac muscle cell death' or 'cardiac muscle cell death in response to hydrogen peroxide'.   As @thomaspd writes, this potential term does look very much like a phenotype.  

@ukemi - pulling you in too.  I'd appreciate your input.  Thanks.

**Comment by slaulederkind** [comment] 2016-11-17 21:38
Are not most GO terms molecular phenotypes?

**Comment by tberardini** [comment] 2016-11-17 21:42
Well, this one 'cardiac muscle cell death in response to hydrogen peroxide'  is particularly phenotype-y because it includes environmental/experimental conditions.  I realize that 'neuron death in response to hydrogen peroxide' already exists in the ontology.  This is a point where we can reevaluate whether such terms are really useful and within GO's scope.  The answer may be 'yes' but I think it is worth having the discussion.

**Comment by ValWood** [comment] 2016-11-17 21:56
I agree with Paul, these sound like non normal (pathogenic) processes.  A founding principle of GO is to  represents normal processes. I would therefore question the existence of  "regulation of hydrogen peroxide-induced cell death". Sometimes it is difficult to distinguish a phenotype from a process but this seems quite clear cut...

**Comment by ukemi** [comment] 2016-11-17 23:11
I think hydrogen peroxide is used at low levels in the lab to model how cells respond to oxidative stress. I think we used to use it to induce apoptosis. I also believe that it is generated normally by mitochondria and cells respond to it.
PMID:11283020

**Comment by ValWood** [comment] 2016-11-18 07:52
So, if its apoptotic cell death perhaps
"apoptosis" occurs_in "heart muscle cell" happens_during "response to oxidative stress"

but the rationale of this paper is:
In Drosophila, the Hippo signaling pathway negatively regulates organ size by suppressing cell proliferation and survival through the inhibition of Yorkie, a transcriptional cofactor. Yes-associated protein (YAP), the mammalian homolog of Yorkie, promotes cardiomyocyte growth and survival in postnatal hearts. However, the underlying mechanism responsible for the beneficial effect of YAP in cardiomyocytes remains unclear.

and then
To examine the effect of miR-206 upon cell death, CMs were treated with chelerythrine, a known inducer of apoptosis 33. Adenoviral-mediated expression of miR-206 in CMs inhibited chelerythrine-induced cell death as evaluated with the Cell Titer Blue viability assay, caspase-3 cleavage and TUNEL-positive nuclei (Fig. 2F, Online Fig. IVC,D). These results indicate that miR-206 protects against CM death

There seems to be a (negligible) decrease in cell death in the presence of an apotosis inducer when YAP or anti-206 are knocked down. But as YAP is a transcription repressor it  is likely to be suppressing many genes  in a normal cell, but not necessarily regulating apoptosis per. se.

"Protection against death" could be the result of many things (most probably correct development/ muscle structure?), rather than a direct role in apoptosis?  Here apoptosis is a downstream effect when things are not normal (more like a readout?)

I could not find the hydrogen peroxide condition so I might have missed something, I only skimmed the paper. Stan, which experiment is that? But again, isn't this only to induce apoptosis  like chelerythrine?

**Comment by ukemi** [comment] 2016-11-18 12:25
The H2O2 is there and in the supplemental methods. It looks like it is indeed used to model survival in response to oxidative stress. 

I don't think it is during though. It would just mean the two things are happening at the same time with no causality, unless we have changed the meaning of during.

**Comment by paolaroncaglia** [comment] 2016-11-21 17:07
I second @ukemi and @ValWood in the 3 comments above. If the paper shows the cell death mechanisms (is it apoptosis or is it not possible to tell?), then annotate to a programmed cell death term and use annotation extensions. What I can add is: 
Background: most H2O2-death terms were added by Becky Foulger and possibly Paul Denny as part of the Parkinson’s UK project. Becky and Paul have now left the project, but maybe Ruth could chime in. 
Facts: oxidative stress can occur physiologically and can damage cells. Some cells (e.g. neurons) are more sensitive to this type of damage than others because they have reduced capacity to detoxify. Neurons damage and death caused by oxidative stress are relevant in neurodegenerative diseases. In GSEA analysis of Parkinson’s disease patients, we’ve seen enrichment for specific terms in this branch, so they are indeed useful.
Question: is H2O2 present as such in biological systems? Yes, see https://en.wikipedia.org/wiki/Hydrogen_peroxide#Biological_function  
Question: in neuron death in neurodegenerative diseases, does H2O2 cause the damage while present physiologically? Or because it’s used ‘in lieu’ of a macroscopic presence of reactive oxygen species? Can we always and easily tell the difference? That’s a fine line and a tricky one.

**Comment by paolaroncaglia** [comment] 2016-11-21 17:58
@RLovering 
Could you please comment on H2O2-death-related terms in relation to the Parkinson's UK project, see my previous note in this ticket. Many thanks.

**Comment by RLovering** [comment] 2016-11-21 22:40
Hi

I agree that H2O2 does naturally occur in cells (see PMID: 23585717). For example this papers state: moreover, hydrogen peroxide is generated during DA metabolism by monoamine oxidase and is subsequently converted to the highly reactive hydroxyl radical in the presence of transition metal ions [6], contributing to oxidative stress. And: Neurons depend heavily on aerobic respiration for ATP, and hydrogen peroxide and superoxide radicals are normally produced during oxidative phosphorylation as byproducts in the mitochondria. Any pathological situation leading to mitochondrial dysfunction can cause a dramatic increase in ROS and overwhelm the cellular antioxidant mechanisms. Oxidative stress causes peroxidation of the mitochondria-specific lipid cardiolipin, which results in release of cytochrome c to the cytosol, triggering apoptosis.

The problem is in multicellular organisms it is not straightforward to decide what is a normal process and what is pathogenic. Wound healing and immune processes could be argued to be not normal processes. But they are essential processes for humans to survive. I think that mitochondrial dysfunction is something that occurs all the time, which is why there is mitophagy to remove mitochondria that are no longer functioning properly. Whether there needs to be terms that are this specific is more difficult to decide, but there are currently 40 GO terms with H2O2 in the name. So is the suggestion to get rid of all H2O2 terms, or the neuron specific aspect of this? 

Best

Ruth

**Comment by paolaroncaglia** [comment] 2016-11-22 10:39
Thanks @RLovering.
All: Ruth’s comment reinforces me in the opinion that we may want to keep H2O2-related termms in GO, or at least some of them. But I still feel that @slaulederkind’s request for "regulation of hydrogen peroxide-induced cardiac muscle cell death” and children could be captured by using the appropriate term (programmed cell death or apoptosis rather than cell death) and an extension for the cell type.

**Comment by tberardini** [comment] 2016-11-22 17:38
Returning back to the original issue, the addition of Stan's requested regulation term would also require the addition of the core BP of 'hydrogen peroxide-induced cardiac muscle cell death'.  If that is a process that we want to capture for the same reasons that we capture 'hydrogen peroxide-induced neuron death', then I will create it.  Please advise.

**Comment by RLovering** [comment] 2016-11-23 08:54
Can't the cell type be included in the general regulation (or child) terms GO:1903205 regulation of hydrogen peroxide-induced cell death AE (not sure what relation to include here) cardiac muscle cell

**Comment by ukemi** [comment] 2016-11-23 13:52
regulates-o-occurs_in. It is much better done as a LEGO model.

But I see Tanya's point. For the core BP, is the cell-type specific process meaningful? I remember that this came up before in another part of the ontology and we decided the process itself was not, but the regulatory process was different. I suspect that is the case here as well.

**Comment by tberardini** [comment] 2016-11-23 20:53
@slaulederkind : Can you annotate as Ruth suggests?

[positive/negative] regulation of hydrogen peroxide-induced cell death AE _annotation extension_ (not sure what relation to include here) cardiac muscle cell

**Comment by slaulederkind** [comment] 2016-11-28 16:11
Okay, I’ll put the cell type in the note.

Stanley J. F. Laulederkind, Ph.D.
Rat Genome Database
Human Molecular Genetics Center
Medical College of Wisconsin
8701 Watertown Plank Rd
Milwaukee WI 53226
(Phone) 414-955-7513
(Fax) 414-456-6516

**Comment by tberardini** [comment] 2016-11-30 01:16
Thanks, @slaulederkind.  Closing this issue.

**Closed by tberardini** 2016-11-30 01:16 UTC
