### ISSUE TITLE
NTRs: 'toll-like receptor TLR4:TLR6 signaling pathway'-related and 'cellular response to oxidised low-density lipoprotein particle stimulus'.

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13511] opened 2017-05-17 12:22 UTC
Hello,

I am currently annotating PMID:20037584 where Figure 1 demonstrates cooperative signalling of TLR4 and TLR6, which depends on TRIF as well as MyD88.

Atm we have relevant terms in the ontology that are specific to TLR4:
GO:0035667 TRIF-dependent toll-like receptor 4 signaling pathway
GO:0035660 MyD88-dependent toll-like receptor 4 signaling pathway

So I wondered whether corresponding terms should be created for TLR4 and TLR6 working together? These would be:
NTR1: 'TRIF-dependent toll-like receptor TLR4:TLR6 signaling pathway';
NTR2: 'MyD88-dependent toll-like receptor TLR4:TLR6 signaling pathway'.

If these get created I suppose I also ought to request:
NTR3: 'toll-like receptor TLR4:TLR6 signaling pathway'
Because corresponding GO terms for other toll-like receptors currently exist, e.g.
GO:0038123 toll-like receptor TLR1:TLR2 signaling pathway

If the new terms get created please use the DbxRef: GOC:aruk and GOC:bc.

Or are the existing toll-like receptor gene product-specific terms going to be removed, and so I should use the parent terms for annotations? 
GO:0035666 TRIF-dependent toll-like receptor signaling pathway; and
GO:0002755 MyD88-dependent toll-like receptor signaling pathway.

The experiments (in Figure 1 and in the following figure) also show that the TLR4/6 signalling is triggered by oxidised LDL. Consequently could I request a new term:
NTR4: 'cellular response to oxidised low-density lipoprotein particle stimulus' 

Thanks,
Barbara

@RLovering 
DbxRef: ARUK-UCL
GOC:bc

**Comment by pgaudet** [comment] 2017-06-20 13:05
Hi @BarbaraCzub 

I am finally getting around to this. I am a little worried to add the different combinations of TLR because that might be a lot of terms. Did you try making a Noctua model with this ? It may give some insight into how to annotate in a more pre-composed way. 

Pascale

**Comment by BarbaraCzub** [comment] 2017-06-20 15:14
Hi @pgaudet

No, I have not tried making a Noctua model. These annotations are a part of the Alzheimer's Research UK (ARUK)-funded project, and so they need to be attributed to ARUK in bioinformatic resource databases. 

Creating models in Noctua currently results in attributing them generally to Noctua (this is how they are displayed in AmiGO2) rather than specific project/funding bodies. Therefore, I have been using Protein2GO to annotate papers for the ARUK-funded project; these annotations are subsequently displayed as ARUK-UCL in QuickGO and AmiGO2.

I suppose whether or not the specific TLR-related GO terms get created depends on decisions wrt whether or not GO terms specific to gene products should get created. 
@RLovering do you know whether this was discussed (and hopefully decided) at the GO meeting?

Barbara

**Comment by pgaudet** [comment] 2017-06-20 15:37
Hi @BarbaraCzub 

Why are Noctua models attributed to Noctua? Your ORCID is saved in the model, it should be completely traceable. Perhaps this is an issue with the GAF export from Noctua that doesn't export that information? 

Pascale

**Comment by BarbaraCzub** [comment] 2017-06-20 15:52
Hi @pgaudet 

It is certainly possible for GOC members to trace models to specific ORCIDs by using the Noctua annotation tool. But publicly all annotations created using Noctua are displayed as contributed by 'GO_Noctua', e.g. screenshot below:

![screen shot 2017-06-20 at 16 43 06](https://user-images.githubusercontent.com/16541096/27342391-f711c23c-55d7-11e7-84f7-4783263b75dc.png)

So an external user has no option to trace an annotation to the project that it originated from. Because we rely on grants from funding bodies, we need to be able to acknowledge them in the annotations made with their help.

The attribution of Noctua models to specific projects/funding bodies was discussed during the Noctua training at the EBI in Hinxton last year, but I am not aware what decisions have been made with regard to this.

Barbara

**Comment by pgaudet** [comment] 2017-06-22 15:53
Hello @BarbaraCzub , 

Thanks for bringing up the problem to our attention. We have now added your group to the yaml file, so when you log into Noctua there should be a small arrow at the right of your name, that provides a pull down with the list of groups you belong to. This should give the right attribution. 

Can you please give that a try? 

Pascale

**Comment by BarbaraCzub** [comment] 2017-06-23 09:59
Hi @pgaudet 
I have just logged into Noctua and I found the arrow with the dropdown menu in the model view after clicking on 'create Noctua model'. Thank you for bringing this to my attention. So, if I select, e.g. 'ARUK-UCL', how will annotations created as a part of this model be displayed in AmiGO2? Will they be displayed as ARUK-UCL? Or Noctua-ARUK-UCL?
Thanks,
Barbara

CC @RLovering

**Comment by pgaudet** [comment] 2017-06-23 10:57
@kltm can you please answer @BarbaraCzub ?

**Comment by BarbaraCzub** [comment] 2017-06-23 15:08
Hi @pgaudet 
To follow up from the above, I think I am now able to answer my own question. I did a little test, I ticked 'SynGO-UCL' in the drop-down menu, which you indicated; then I saved the model and I downloaded the GPAD file (screenshot below). In GPAD the annotation source is still displayed as GO_Noctua. 

So although you can select a project, when you are working on a model, this selection does not appear to be linked to the GPAD. In addition the project, which I originally selected for this model, did not remain saved with it. When I went back to the model after viewing the GPAD file, and clicked on the drop-down menu again, the project, which was ticked was 'BHF-UCL' (this was the top one on the list, so I suppose the top one is the 'default' one). (When I downloaded the GPAD, it opened in the same window, and the I used the 'go back' arrow in my browser to return to the model view). So, although these functions are available for initial selection, they do not stay selected after you stop viewing a model (even when you save it before moving on), and they are not exported in the GPAD files. 

![screen shot 2017-06-23 at 12 29 48](https://user-images.githubusercontent.com/16541096/27487622-2ac0ddce-582c-11e7-99b8-fd087c78e976.png)

**Comment by pgaudet** [comment] 2017-06-23 15:52
@kltm is this the expected behavior?

**Comment by pgaudet** [comment] 2017-06-23 16:12
Hi @BarbaraCzub 

My understanding is that you need to save a new annotation (or re-save an old annotation, you probably need to change something to be able to save it). Just changing the group will not attribute all the existing annotations. 

Can you try that ? 

Thanks for your patience ! 

Pascale

**Comment by BarbaraCzub** [comment] 2017-06-23 16:47
Hi @pgaudet 

I tried what you suggested. I used a test model, which I created earlier today:
![screen shot 2017-06-23 at 17 34 52](https://user-images.githubusercontent.com/16541096/27491537-bc06dd52-583a-11e7-9f6b-55739f289b0d.png)

This model was originally created with the default BHF-UCL attribution, which I confirmed when I opened the drop-down menu:
![screen shot 2017-06-23 at 17 35 18](https://user-images.githubusercontent.com/16541096/27491651-2ca5a64c-583b-11e7-87fd-c1e02963dd39.png)

I then changed the 'heart process' to another process, changed the attribution to ARUK-UCL, and saved:
![screen shot 2017-06-23 at 17 36 34](https://user-images.githubusercontent.com/16541096/27491667-3af4af72-583b-11e7-884f-9f7e9d5b6573.png)

I then went back to the Noctua landing page, and from there I selected this test model again and checked the attribution in the drop-down menu. BHF-UCL was ticked:
![screen shot 2017-06-23 at 17 37 11](https://user-images.githubusercontent.com/16541096/27491723-658f819e-583b-11e7-8ba9-d6e01ae001c9.png)

So, although I have made a significant change to the model and re-saved, the attribution did not get saved with it. 

I am not sure what else I can do. @RLovering wanted to try this in her account, but she does not even have the drop-down menu options to choose from, so we were not able to do that test.

I will look forward to receiving further instructions.

Thanks,
Barbara

**Comment by cmungall** [comment] 2017-06-23 16:50
Let me clarify the part about what is seen in AmiGO, which is a separate issue from group-level attribution.

Currently it's up to individual groups to take the GPAD output from Noctua and incorporate into their database. So far, only MGI does this. In the future, when people are happy with the GPAD export, we can look at doing this in GO Central.

Btw, we in future it's better to open Noctua issues in the noctua tracker, but let's keep this discussion here for now.

**Comment by BarbaraCzub** [comment] 2017-06-23 16:51
One more issue: I get no annotations from this model at all, when I click 'Export GPAD':

![screen shot 2017-06-23 at 17 49 21](https://user-images.githubusercontent.com/16541096/27491997-73f86b0a-583c-11e7-8049-89257e3d2f02.png)

**Comment by cmungall** [comment] 2017-06-23 16:53
@BarbaraCzub - you need to add evidence to get annotations. In future @dougli1sqrd's checks will inform if there are assertions lacking evidence, for now this is something you just have to know

**Comment by cmungall** [comment] 2017-06-23 16:55
Re:

![image](https://user-images.githubusercontent.com/50745/27492122-e3bee42a-57f9-11e7-8f31-4253286f663a.png)

I am not so sure this is a correct inference about the tool. The tick merely indicates what hat(s) you are wearing, it does not reflect current attribution of either the whole model or the assertions within it (@kltm can confirm). To see model-level attribution go to model->edit annotations and look for "provided by"

**Comment by BarbaraCzub** [comment] 2017-06-23 16:56
Thank you @cmungall for explaining this. So do I understand correctly that once I'm happy with a model and would like it to be attributed to ARUK-UCL, I should just download the GPAD and forward it to @tonysawfordebi ? Or what is the procedure?

As this is a test model it did not occur to me that I was missing the evidence. Thanks @cmungall for pointing this out.

This was originally a new term request, but it has turned into a Noctua issue...

**Comment by cmungall** [comment] 2017-06-23 16:57
> So do I understand correctly that once I'm happy with a model and would like it to be attributed to ARUK-UCL, I should just download the GPAD and forward it to @tonysawfordebi ? Or what is the procedure?

I guess you could but that would be a pretty rubbish pipeline! No, this is all meant to be more intuitive.. I have to get into work now will reply in more detail later

> This was originally a new term request, but it has turned into a Noctua issue...

Yes, it's easy for these to blend together

**Comment by BarbaraCzub** [comment] 2017-06-23 16:58
Ok, I checked "provided by" and it links to our UCL websites (both the one associated with BHF and ARUK annotation projects). So the tool 'memorised' both ticked attributions.

**Comment by BarbaraCzub** [comment] 2017-06-23 17:02
Thank you @cmungall you've already clarified a lot! This was very helpful. Have a good day! (It's almost the weekend here!).

**Comment by pgaudet** [comment] 2017-06-23 17:11
Should we close this then ?

**Comment by RLovering** [comment] 2017-06-24 20:26
Note Barbara has opended as separate github request for https://github.com/geneontology/go-ontology/issues/13712

**Comment by pgaudet** [comment] 2017-06-26 09:31
Closing this and starting work on #13712 
@BarbaraCzub @RLovering , please reopen if this is not resolved. 

Thanks, Pascale

**Closed by pgaudet** 2017-06-26 09:31 UTC
Labels: ARUK-UCL, New term request, signaling
