### ISSUE TITLE
GO:0035064 methylated histone binding and specific children

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#24033] opened 2022-09-20 11:39 UTC
GO:0035064 methylated histone binding
- GO:0061628 H3K27me3 modified histone binding
- GO:0062072 H3K9me3 modified histone binding
- GO:1990889 H4K20me3 modified histone binding

Why these 3 children but not others, for example
H3K4me3 modified histone binding

Or the question, why having these specific children?

In my case I did from PMID:33721015:

Dd sgf29 | GO:0035064 methylated histone binding |  has_input CHEBI:85043 (H3K4Me3) 

Maybe the extension is better for GO-CAM if necessary?

Plus there are specific functions like 'histone H3K4 acetyltransferase activity' if evidence allows it. Does this MF make the specific binding obsolete? However, the binding MF is additional evidence for interaction.

Thanks!

**Comment by pgaudet** [comment] 2022-09-20 12:47
Hi @pfey03 


Thanks for bringing this up. I was hoping to replace this for GO:0140566 histone reader activity, but I'd rather not create all possible modifications. @colinlog mentioned that a few (not sure how many) modifications are more relevant, we need to make that list. 


HOWEVER I dont think using a CHEBI for a protein is good practice; and I am not sure this is compliant with the GO-CAM model/ShEx rules. @vanaukenk @ukemi what is the recommendation, is it to use PRO ?

**Comment by pfey03** [comment] 2022-09-20 15:22
@pgaudet I also noticed CHEBI by far has not many histone modification. Maybe PRO is better?

**Comment by ValWood** [comment] 2022-09-21 18:04
I  opened a ticket about just this:
https://github.com/geneontology/go-ontology/issues/23932

I would always use PRO  to represent the entities (this is necessary to correctly capture the context), and so the. modified histone binding terms seem redundant?

**Comment by pfey03** [comment] 2022-11-04 15:44
@pgaudet 
I'm right now working with PRO adding all Dicty histone modifications. What about the MFs such as
histone H3K4 methyltransferase activity
histone H3K36 methyltransferase activity

will those stay or also used with PRO extensions?

**Comment by pgaudet** [comment] 2022-11-04 15:47
Hi @pfey03 

The activities will stay. I even created several new ones this week, so that we can obsolete the corresponding BPs. 

Thanks, Pascale

**Comment by pfey03** [comment] 2022-11-04 15:51
@pgaudet ok, sounds good, thanks!

**Comment by pgaudet** [comment] 2024-11-29 15:23
Duplicate of https://github.com/geneontology/go-ontology/issues/27427

**Closed by pgaudet** 2024-11-29 15:23 UTC
Labels: binding, chromatin
