### ISSUE TITLE
"protein folding chaperone" synonyms, "protein binding involved in protein folding" term name

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12252] opened 2016-01-27 08:32 UTC
"protein folding chaperone" is a synonym (narrow) of protein binding, even though an exact match
"protein binding involved in protein folding"
exists. "protein folding chaperone" is NOT a synonym of this exact term.

(easy to overlook "protein binding involved in protein folding" in the long protein binding list)

Can the primary term name of
"protein binding involved in protein folding"
be 
"protein folding chaperone"
Its more meaningful for users, can still be defined and placed as a binding term.

That way, I can link it to 
post-chaperonin tubulin folding pathway
and it will look like this
protein folding chaperone has_substrate(beta tubulin), part_of post-chaperonin tubulin folding pathway
rather than 
protein binding involved in protein folding has_substrate(beta tubulin), part_of post-chaperonin tubulin folding pathway

which looks a bit silly...

**Comment by paolaroncaglia** [comment] 2016-01-27 11:02
Hi Val,

I’m afraid I have a couple of uncertainties about your proposed primary name ”protein folding chaperone”.
1) The syntax is confusing to me (makes it sound like a chaperone that does protein folding - which chaperones do, but my point is that the concept as might be mistaken wouldn’t be in scope for GO)
2) "protein binding involved in protein folding" is_a protein binding, part_of protein folding. The label ”protein folding chaperone”, instead, implies is_a protein folding.

Looks like there may have been past discussion on chaperone-containing synonyms.
“protein folding chaperone” was added as (narrow) synonym of protein binding back in 2009 (with dbxrefs pointing to @tberardini , @ukemi  and @mah11 ). “protein binding involved in protein folding” has a dbxref GOC:mtg_cambridge_2009 (and a broad synonym “chaperone activity”). So both terms may have been edited as part of the same work. You may want to check with Midori?

There’s a related ticket from Jim Hu, assigned to @ukemi  (who’s on leave at the moment):
https://github.com/geneontology/go-ontology/issues/10701

Cheers,
Paola

**Comment by ValWood** [comment] 2016-01-27 12:27
I'm confused now because I thought that "protein binding involved in protein folding" was meant to represent a "protein folding chaperone", Why would that be out of scope for GO if that is what the activity of the protein is (I am trying to annotate one of the tubulin  folding and assembly chaperones).

There has been lots of past discussion on chaperones and I thought we agreed to house them as 'protien binding terms' 

I'll let midori comment if she remembers.
I'm also sure that @RLovering will have something to say here ;)

**Comment by ValWood** [comment] 2016-01-27 12:29
I just read Jim's thread. Happy to have a new term to capture this "function" precisely.
We will need some activity to represent this, because  LEGO diagrams depend on "functions".

**Comment by paolaroncaglia** [comment] 2016-01-27 16:41
Note for self: Tanya doesn't remember discussing those synonyms.

**Comment by jimhu-tamu** [comment] 2016-01-28 14:53
commenting just to add myself to the notifications on this item.

**Comment by paolaroncaglia** [comment] 2016-01-29 14:15
Hi Val,
Still waiting to hear if @mah11 , @ukemi or @RLovering have any comments. I know David is away, so I'll label this ticket as 'pending' while we wait if you don't mind.
Cheers,
Paola

**Comment by mah11** [comment] 2016-01-29 14:27
I remember only that many long, draw-out discussions took place a long time ago. I think I'm repressing memory of the content for the sake of my remaining sanity ;)

**Comment by ValWood** [comment] 2016-01-29 14:34
No hurry, but I did look at the annotations to 
"protein binding involved in protein folding" and I believe they are all chaperones (they must be, if a chaperone if a molecule which binds a protein, and assists in folding, but is not part of the final complex). The  ones that aren't do not seem to be anything to do with protein folding at all.

They are P0C045 (an F-box protein), AgBAse
and
CD24 (HLA class II histocompatibility antigen gamma chain) (human).
I'll quicky scan these papers and open disputes if this is the case.

I  still can't think what this term could apply to except for "protein folding chaperones"

**Comment by ValWood** [comment] 2016-01-29 14:35
Yes we talked about this a lot, a lot, a lot. Many meetings. Almost as much as evidence codes, antioxidants and transcription factors.....

**Comment by mah11** [comment] 2016-01-29 14:37
so many worms, so few cans ...

**Comment by ValWood** [comment] 2016-01-29 17:38
checked both of these. I don't see any folding annotation.

reported
P0C045 (an F-box protein), AgBAse

I couldn't report this one:
CD24 (HLA class II histocompatibility antigen gamma chain) (human).
 because I couldn't find the annotation in Uniprot (I checked all 4 entries for this gene product...that is also one of the things that dives me crazy....)
anyway maybe this is already removed?

All the other annotations (experimental at least) appear to be chaperones

**Comment by ValWood** [comment] 2016-04-18 15:25
This is related to one of the discussions at the GO meeting.
We need MF terms to represent these different molecular functions in LEGO.

The problem is that  biologists use the word 'chaperone' in different contexts ( previusly we identified 3 different use cases i) protein folding chaperone ii) protein transport chaperone and iii) metallochaperone. At the time these were considered to be out of scope as GO MF terms. However now we need them for LEGO I think it should be OK to add these as required.

We will need to add  the disambiguation like "protein folding chaperone" and "protein transport chaperone" when referring to these different types of chaperone in GO.

**Comment by paolaroncaglia** [comment] 2016-04-29 12:52
Hi @ValWood ,

This doesn't look like a quick fix to me, as it will need discussion, so I removed the label.
Let's see if @ukemi has any comment/advice on how to strategize this.

Thanks!

**Comment by paolaroncaglia** [comment] 2016-05-05 15:15
Discussed with Val. Will leave this aside for now.

**Comment by RLovering** [comment] 2016-05-06 07:27
Hi
I've tried to follow this thread and I am confused about what the problem is. I remember in one GOC meeting Peter pointed out that an enzyme has to bind a substrate in order to catalyse the reaction. Is the same not true of chaperones (sorry I haven't annotated these)

Plus I don't understand why GO:0061077 chaperone-mediated protein folding hasn't been mentioned in this discussion (definition: The process of inhibiting aggregation and assisting in the covalent and noncovalent assembly of single chain polypeptides or multisubunit complexes into the correct tertiary structure that is dependent on interaction with a chaperone.) And why this term isn't a child of protein binding when the definition states that the folded protein and the chaperone interact. But maybe this is because if you inhibit a chaperone you don't necessarily inhibit protein binding?

Sorry if my comments don't fit with the discussion.

Ruth

**Comment by ValWood** [comment] 2016-05-06 08:05
I’ll summarise and hand back to Paola.

The terms for chaperone are very hard to locate.

If  you search on “chaperone” in QuickGO, you get lots of obsolete terms


At number 15 you get 

“GO:0005515 protein binding”  narrow	protein folding chaperone

So most people might think, Oh, I should use this term.

BUT

further down the list is 
GO:0044183 protein binding involved in protein folding  broad synonym	chaperone activity

which is the correct term to use.

I only had 1 simple request (I thought)

1. The   narrow	“protein folding chaperone” synonym of  GO:0005515  should really  be an exact synonym of 
GO:0044183 protein binding involved in protein folding

So it should be moved.

BUT “protein folding chaperone” is a much more biologist-friendly term name than “protein binding involved in protein folding”
so instead of making it the exact synonym, make it the primary term name.


This will  help curators, and users immensely, to a) locate the term, and b) know  exactly what it means


I didn’t think it would be controversial, but its probably my fault for thinking it was obvious and not explaining  it properly.

Ruth, does this make sense to you? I think it fits with the meaning  and use of these terms. If it doesn’t then most people are using them incorrectly.

(I didn’t mention GO:0061077 chaperone-mediated protein folding because its a process term)

**Comment by RLovering** [comment] 2016-05-06 09:01
Thanks Val

I agree that finding these terms would be helped by your suggestions and apologies for not thinking re function and process,

Best
Ruth

**Comment by paolaroncaglia** [comment] 2016-05-17 11:59
Will arrange discussion with @ValWood and @ukemi in June, about this ticket, the one quoted above and another related one assigned to @ukemi .
I'll set to pending for now, thanks.

**Comment by paolaroncaglia** [comment] 2016-06-08 07:00
Note for self: Val suggested: "Let's leave this until later. The chaperone stuff might need broader discussion. Also I think the chaperones might have slightly different functional roles. I might be able to add some of these to the tickets based on some discussion with Antonia".

**Comment by paolaroncaglia** [comment] 2016-08-03 14:26
Val suggests to discuss this at the Noctua workshop at EBI.

**Comment by paolaroncaglia** [comment] 2016-10-24 10:16
Hi @ValWood ,
In view of our meeting tomorrow: please see this comment from June 8th and following: https://github.com/geneontology/go-ontology/issues/12252#issuecomment-224505750
I'll leave this ticket as 'pending' unless you have any updates. Cheers.

**Comment by paolaroncaglia** [comment] 2016-11-21 09:44
Hi @ValWood ,
Could you please take a look at this ticket when you have a chance, and comment on whether this issue was discussed somewhere else, or should be left as pending, or scheduled for discussion at an annotation call, or may be closed etc? :-) Thanks!

**Comment by ValWood** [comment] 2016-11-21 18:53
I would say pending. 
I'm also happy for you to close it. We can always dig it out when the various  "chaperone functions" become an issue for LEGO modelling, but it will likely be a long time before I am annotating any of these.

**Comment by paolaroncaglia** [comment] 2016-11-21 20:52
The word "close" sounds delightful to me, so I'll go ahead and do just that. I'll leave the labels though, and it could also be retrieved by a search for 'chaperone'. Thanks.

**Closed by paolaroncaglia** 2016-11-21 20:52 UTC
Labels: binding, No_MF_in_GO, Other term-related request, pending, PomBase, required_for_LEGO
