### ISSUE TITLE
GO structural problems with reproduction and sorocarp development etc.

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#12619] opened 2016-08-25 22:32 UTC
In Dicty, reproduction ( 'asexual reproduction', cells feeding and dividing) is strictly separated from development. Dicty sorocarp development is a pure strategy for survival of adverse conditions, and cell division stops as soon as cells starve and then start the developmental program.

Reproduction is defined as: The biological process in which new individuals are produced by either a single cell or a group of cells, in the absence of any sexual process. 

Thus, the is_a link from 'sorocarp development'  via some other developmental processes to 'developmental process involved in reproduction' is wrong. Also, I think the direct part_of 'asexual reproduction' is problematic. This concerns all developmental terms for Dicty and includes the more widely used  'asexual sporulation' , also a direct child of reproduction.

Maybe this needs updating when a lot of that multi- and single cell organismal stuff gets cleaned up.
![sorocarp development](https://cloud.githubusercontent.com/assets/1349602/17988133/e869d140-6ae9-11e6-90d4-3054d294af30.png)

**Comment by pgaudet** [comment] 2016-08-26 07:19
Hi Petra, 

The definition you give: "The biological process in which new individuals are produced by either a single cell or a group of cells, in the absence of any sexual process. " is for asexual reproduction, which is a child of "reproduction" (def: "The production of new individuals that contain some portion of genetic material inherited from one or more parent organisms.", which covers both sexual and asexual reproduction. 

It seems to me dicty spore formation is correctly placed under asexual reproduction. 

Pascale

**Comment by pfey03** [comment] 2016-08-26 15:36
HI Pascale, yeah sorry for pasting the def from the wrong window, but still, Dicty spore formation is not reproductive.  "The production of new individuals that contain some portion of genetic material inherited from one or more parent organisms." As the term suggests, it's "the production of new individuals" that's the problem. 

As you know, Dicty only reproduces as vegetative cells. No single new cell is formed during development (once they starve), they only differentiate. I don't actually know if any other simple organisms have the same strict separation between cell division and cell differentiation (development) as in Dicty. But I think it's misleading and incorrect for Dicty to have any of the development under reproduction. The whole discussion by Diane about obligate and facultative multicellularity reminded me that I saw this before but didn't go so much into it.

Thanks for responding, you are the right GO top person to discuss this with;-)
Petra

**Comment by pgaudet** [comment] 2016-08-26 16:44
Ah ! Sorry - I was focused on the sexual versus asexual ! 

You're right, this is more like bacterial/yeast encapsulation. 

Pascale

**Comment by tberardini** [comment] 2016-08-26 19:56
@pfey03 - if you had to start from scratch, where would you place 'sorocarp development' and what would you remove?

Current parentage:

is_a: GO:0009267 ! cellular response to starvation
is_a: GO:0030582 ! fruiting body development
is_a: GO:0044702 ! single organism reproductive process
is_a: GO:0044767 ! single-organism developmental process
relationship: part_of GO:0019954 ! asexual reproduction

**Comment by pfey03** [comment] 2016-08-26 20:35
The parentage side
sorocarp development (sensu Dicty) is_a cellular response to starvation = TRUE
sorocarp development (sensu Dicty) is_a fruiting body development = TRUE
sorocarp development (sensu Dicty) is_a single organism reproductive process = FALSE
sorocarp development (sensu Dicty) part_of asexual reproduction = FALSE

The term 'sporocarp development involved in sexual reproduction' used for fungi is a child of the sensu Dicty sorocarp development. I guess those links all need to be severed?

I'll look more into this next week regarding starting from scratch, thanks Tanya for taking this on. I also have a longstanding problem with the taxon restriction of 'social behaviour'  (issue 12357) that reaches into the multicellularity discussion. Hope to solve this all by fixing these things and then creating a new term 'social cooperation' or such. Continued on Monday..

**Comment by pfey03** [comment] 2016-08-30 16:57
The problem is with the parent term GO:0030582 fruiting body development, and up. This is what all Dicty people call the Dicty process, so we cannot easily sever the 'sorocarp development is_a fruiting body development link, or we need to create a more taxon specific terms, which I attempt.

The next parent up, GO:0075259 spore-bearing organ development is still true as the def allows it, but I wouldn't care for the term, we would not use it because 'organ' is typically not used for Dicty. Also, the parent of that term  GO:0048513 animal organ development seems NOT true for Dicty, if we agree that it is not an animal and I'm surprised no check caught that so far. 

Finally the link from the spore-bearing organ development to reproduction is the core problem, therefore, we cut the link from Dicty development to that term we wouldn't use, see above. 

Here I try to do a new addition of GO:0030587 sorocarp development (and all it's children). If I forget some things, forgive me and we work it in from here.

GO:0030587 ! sorocarp development (and it's children)
* is_a: GO:0009267 ! cellular response to starvation
* is_a NEW: protozoan fruiting body development
* -  is_a: GO:0048731 ! system development
* - -   is_a: GO:0007275 ! multicellular organism development
* - - -  is_a: GO:0044767 ! single-organism developmental process **

The new term 'protozoan fruiting body development' could be a direct child to 'single-organism developmental process'
Def of new term: A protozoan process whose specific outcome is the progression of the fruiting body over time, from its formation to the mature structure. A fruiting body is a multicellular structure that contains spores.

**The question if the cells that make up the fruiting body to survive adverse conditions are still each an organism (they cannot reverse at this point), or if the fruiting body is then a single organism. This touches on the other discussions i have and is a bit philosophical. 

Let me know if there are questions. I want to also solve the 'social behaviour problem, and after this cleanup might be able to add a new term 'social cooperation' which could be part_of sorocarp development as that other issue doesn't go anywhere. Need then to figure out parentage for such a new term. Sorry for meandering..

Thanks!
Petra

**Comment by tberardini** [comment] 2016-09-08 19:56
The parentage between 'spore-bearing organ development' and 'animal organ development' has been removed week or so ago, though it looks like this hasn't filtered through to QuickGO yet.  

If I understand you correctly, @pfey03, you mean to say that 'sorocarp development' is correctly placed as an is_a child of a term called 'fruiting body development' but the Dicty community and the yeast/fungal community use the word 'fruiting body' to mean different things.  Or perhaps the distinction is that in Dicty, a fruiting body is NOT a reproductive structure but in fungi, a fruiting body IS a reproductive structure.  It may be that we need two terms, then, one for 

'reproductive fruiting body development' (existing term)
'non-reproductive fruiting body development' (new term) - better term name suggestions welcome

**Comment by pfey03** [comment] 2016-09-08 20:26
EBI had this catastrophic breakdown as Tony wrote today about Protein2GO and I guess QuickGo is affected like all their services. Hope it's all back soon.

> Or perhaps the distinction is that in Dicty, a fruiting body is NOT a reproductive structure but in fungi, a fruiting body IS a reproductive structure.

YES

'non-reproductive fruiting body development' (new term) seems ok, we use the child 'sorocarp development' for annotations anyway. In Dicty, people call this the social development cycle, as opposed to a sexual cycle, and the vegetative growth cycle. Maybe you could add, as broad synonym, 'social fruiting body development' (as survival strategy, they have social behavior that leads to the other debate...). 
If you are interested:
http://dictybase.org/Multimedia/DdLifeCycles/index.html

Thanks Tanya!

**Comment by tberardini** [comment] 2016-09-08 22:34
Noting from above:  "The term 'sporocarp development involved in sexual reproduction' used for fungi is a child of the sensu Dicty sorocarp development. I guess those links all need to be severed?"  This link is not present anymore.  Must have been removed.

Ok.  What if we edit the ontology this way:

- [ ] rename 'fruiting body development' as 'reproductive fruiting body development',     GO:0030582
- [ ] create new term 'non-reproductive fruiting body development' as a direct child of 'anatomical structure development'  and 'multicellular organism development'
- [ ] move 'sorocarp development' and child terms from 'reproductive fruiting body development' to under this new term, no more link to reproductive process

**Comment by pfey03** [comment] 2016-09-08 23:26
Sounds good for this part - Thanks Tanya!

Noticed also we cannot use anything under 'asexual sporulation' as this goes directly to 'asexual reproduction'. Need to fix those few annotations as we need to annotate to parent 'sporulation resulting in formation of a cellular spore'. Luckily most are correct.
@rjdodson make sure to pay attention to that

**Comment by tberardini** [comment] 2016-09-09 17:02
@pfey03 : for your comment on 'asexual sporulation', that sounds very much like an annotation recommendation, not one for ontology change.  If I implement my suggested edits, can I close this issue?

**Comment by pfey03** [comment] 2016-09-09 19:18
Yes, Tanya, now that P2GO is back I can make these fixes right away. Thanks for taking care of this!

**Comment by tberardini** [comment] 2016-09-09 19:50
I haven't done the editing yet!

**Comment by tberardini** [comment] 2016-09-09 23:28
Added:

 [Term]
+id: GO:0090702
+name: non-reproductive fruiting body development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of a non-reproductive fruiting body over time, from its formation to the mature structure. A fruiting body is a multicellular structure that contains spores. An example of such a process is found in Dictyostelium discoideum." [GOC:pf]
+is_a: GO:0007275 ! multicellular organism development
+is_a: GO:0048856 ! anatomical structure development
+created_by: tanyaberardini
+creation_date: 2016-09-09T16:14:21Z

and made edits to positioning of 'sorocarp development' and children to move to new places and remove links to 'reproductive' parents.

**Closed** 2016-09-09 23:31 UTC
