### ISSUE TITLE
 NTR: intracellular signal transduction involved in positive regulation of G2/M transition of mitotic cell cycle 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12644] opened 2016-09-07 13:06 UTC
NTR: intracellular signal transduction involved in positive regulation of G2/M transition of mitotic cell cycle 
Any intracellular signal transduction that is involved in positive regulation of G2/M transition of mitotic cell cycle 
ref PMID:15917811

**Comment by ukemi** [comment] 2016-09-07 13:11
I have the same question as on the previous ticket.

There are two possibilities that can be created in TG. one would be 'X involved in (regulation of Y)' and the other would be 'regulation of Y by X'. In the latter case the execution of X is the mechanism by which the process Y is regulated. In the former case, the execution of X contributes to a larger process that regulates Y.

**Comment by ValWood** [comment] 2016-09-07 13:13
Lets sit on this one. Really the entirety of 
"regulation of G2/M transition of mitotic cell cycle" is intracellular signal transduction, so it should really be a parent.

I am (very soon), as I want to switch and get the cell cycle paper done, going to put a very long tread onto the PomBase curation tracker, to try to resolve some of the issues  with G2/M
that Jacky has raised.

I think this will help....

**Comment by ukemi** [comment] 2016-09-07 13:20
In that case it would be the latter case. The signal transduction is the regulation. But if it is the only way that the G2/M is regulated, then we could just make 'regulation of G2/M transition of mitotic cell cycle' a subtype of 'intracellular signal transduction', which is what I think you are saying.

**Comment by ValWood** [comment] 2016-09-07 13:40
> But if it is the only way that the G2/M is regulated, then we could just make 'regulation of G2/M transition of mitotic cell cycle' a subtype of 'intracellular signal transduction', which is what I think you are saying.

I think so based on the discussions with Jacky....but I will need to confirm this...
PomBase has 55 annotation to G2/M, but not all of these are signalling, but they *could* be the sensor at the beginning of the pathways (its multiple pathways which converge on cdc2).
Once we have things in the LEGO model I think it will be easier to assess....

**Comment by ukemi** [comment] 2016-09-07 13:42
So can we close this one for now?

**Comment by ValWood** [comment] 2016-09-07 14:15
I'll take it for now

**Comment by ValWood** [comment] 2016-09-13 11:13
I think you need 2 terms Antonia

intracellular signal transduction involved in positive regulation of re-entry into mitotic cell cycle (BUT I think if the process GO:0000320 Name re-entry into mitotic cell cycle Ontology Biological Process Definition The resumption of the mitotic cell division cycle by cells that were in a quiescent or other non-dividing state.
should be defines as a signalling pathway, which would remove the need for the new term.

Although maybe you need to specify the point of re-entry is G2

intracellular signal transduction involved in positive regulation of G2/M transition of mitotic cell again, regulation of G2/M is a signalling pathway..... I will have a proposal to fix this shortly.
all of this should go in the other ticket.....

2.

BUT, I think that the regulation of G2/M transition, if defined correctly *is * a signalling pathway.

**Comment by ValWood** [comment] 2017-09-05 15:10
We desperately need a way to represent the mechanism of cell cycle control under signalling. Cell cycle control IS_A signalling pathway. I hope this can be a discussion point  at the signalling meeting.

**Comment by pgaudet** [comment] 2018-02-08 11:06
@ValWood 
What do you want to do with this one ?

**Comment by pgaudet** [comment] 2018-02-16 15:59
pinging @ValWood again

**Comment by ValWood** [comment] 2018-02-16 16:20
This is quite a big issue.

The cell cycle transitions are signalling pathways that converge on cdc2. IMO these terms should only be used to annotate the signalling pathways components.
see image in this ticket for G2/M, lots of signalling pathways converge on cdc2)
https://github.com/pombase/curation/issues/1049

Unfortunately many researchers in higher organisms say any cell  cycle block is regulating a cell cycle transition (or perhaps they don't say that, but curators interpret the cell cycle block in this way). These annotations  include anything which, when mutated causes a cell cycle block. In fission yeast this  would be upwards of 500 gene products if we made these annotations, and the cell cycle terms would cease to be useful to cell cycle researchers. 

The genes which when mutated cause a cell cycle block  are not really regulating the transitions at all. They are causing a problem which activates a checkpoint  to block cell cycle progression. Only the checkpoint is involved in regulation of the transition in these cases. These experiments are demonstrating that there is a problem, and the checkpoint is activated.

Midori got  closest to articulatin what has been in my head in this thread https://github.com/pombase/fypo/issues/3172
  whilst we were thinking about this for phenotype terms

So, ideally the G2/M transition term would be a child of 
"signal transduction" it is a signalling pathway.

The problem is that many genes are annotated that  cell cycle researchers would not consider to be regulating  the G2/M transition. This would be difficult to deal with. So, I'm a bit stuck how to fix the problem.....

**Comment by ValWood** [comment] 2018-02-16 16:21
If there are any other tickets that I have  not replied to, pleas re-ping me...I must of had ~8 days where I was not receiving tracker tickets. I sorted my settings out properly this time.
v

**Comment by pgaudet** [comment] 2018-02-16 16:26
Thanks @ValWood 
I'm reassigning this to you - let me know when you're ready ! 

Thanks, Pascale

**Comment by ValWood** [comment] 2018-02-16 16:27
I think I will need to bring the matrix in on this one.....

**Comment by ValWood** [comment] 2018-03-26 16:29
Not yet....It's quite far down my list (a  few months at least as  I'll role it in with other cell cycle stuff)

**Comment by ValWood** [comment] 2018-03-26 16:30
It has implications for lots of cell cylce regulation terms and annotations.

**Comment by ValWood** [comment] 2021-03-05 09:21
willl become obsolete by
https://github.com/geneontology/go-ontology/issues/19985

**Closed** 2021-03-05 09:23 UTC
Labels: New term request, PomBase, cell cycle and DNA processes, mini-project, signaling, waiting for feedback
