### ISSUE TITLE
Large number of relations deleted in go-plus.json - is it correct?

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#14949] opened 2018-01-29 08:17 UTC
Over the weekend, our ontology update pipeline has been failing because one of its safety checks has detected the deletion of a suspiciously large number of relations (3131 in total) from go-plus.json.

When I investigated, I found that they are all is_a relations between regulation terms, for example:

- GO:0060542 (regulation of strand invasion) is_a GO:0000018 (regulation of DNA recombination)
- GO:2000805 (negative regulation of termination of RNA polymerase II transcription, poly(A)-coupled) is_a GO:0000122 (negative regulation of transcription by RNA polymerase II)
- GO:0060633 (negative regulation of transcription initiation from RNA polymerase II promoter) is_a GO:0000122 (negative regulation of transcription by RNA polymerase II)
- GO:0050715 (positive regulation of cytokine secretion) is_a GO:0001819 (positive regulation of cytokine production)
- GO:0051893 (regulation of focal adhesion assembly) is_a GO:0001952 (regulation of cell-matrix adhesion)

I can force our pipeline to accept these deletions, but first I want to confirm that they are genuine, and not the result of a problem with the ontology (in which case I won't do anything until the problem is fixed).

**Comment by ukemi** [comment] 2018-01-29 13:47
Hmm. I wonder if ths is due to #14940. We will investigate and @cmungall, perhaps we need to revert.

**Comment by ukemi** [comment] 2018-01-29 13:53
Maybe not. It looks like that pull request isn't merged yet.

**Comment by cmungall** [comment] 2018-01-29 16:19
@ukemi looks like the effect you'd expect of losing the r o part-of property chain, can you experiment with adding this back in to see if the inferences come back, cc @balhoff

**Comment by balhoff** [comment] 2018-01-29 18:16
I'm reverting all my changes for the time being so that I can do this again more carefully.

**Comment by tonysawfordebi** [comment] 2018-01-30 08:12
Thanks, @balhoff - I've just tried running our update pipeline again, and it looks like your reversion of the changes hasn't found its way into go-plus.json yet.

**Comment by ukemi** [comment] 2018-01-30 12:50
Note this also relates to #13926. The property chain will eventually be problematic as we move on to functional causality in GO-CAM models and will need to be removed at that point. I like the suggestion in this ticket of somehow asserting all the existing (or soon to be re-existing) relations and then removing the property chain.

**Comment by ValWood** [comment] 2018-01-30 14:04
We also lost a lot (~100)  of annotations from our slim last night (or the night before)...could this be the cause?

It affects mainly branches with some relationship to chromosome segregation (but not exclusively). I'll check again tomorrow and see if the issue fixes itself...

**Comment by ValWood** [comment] 2018-01-31 11:53
Our slim is back to normal.

**Comment by tonysawfordebi** [comment] 2018-01-31 12:51
As is our update pipeline.

**Comment by ukemi** [comment] 2018-01-31 14:03
OK. I will close this one then. There is still the outstanding issue in the other ticket.

**Closed by ukemi** 2018-01-31 14:03 UTC
Labels: editors-discussion
