### ISSUE TITLE
Merge nuclear and cytoplasmic versions of identical protein complexes? (location specific versions of the same complex)

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12833] opened 2016-11-29 13:52 UTC
Hi @ukemi and @vanaukenk 
This is a general question that stemmed from an ontology ticket (https://github.com/geneontology/go-ontology/issues/12598) involving @ValWood , @bmeldal and @hattrill .
There is also a second general question, about the appropriateness of having assembly intermediates in GO.
Val tried to bring these up at the last GOC meeting, but there wasn’t a chance for discussion.
Could you please add to the agenda for a future annotation call. I realise this won’t be quick or easy, but I wanted it to be recorded somewhere. Please feel free to move this item to a different tracker if that’s better, thanks.

**Comment by ukemi** [comment] 2016-12-02 01:50
Added to the spreadsheet of ontology issues to discuss on annotation calls.

**Comment by pgaudet** [comment] 2018-08-27 20:41
I'd be if favor of merging - let's discuss at the next editors meeting. 

Thanks, Pascale

**Comment by ValWood** [comment] 2020-09-23 07:43
closing as this is an exact duplicate of
https://github.com/geneontology/go-ontology/issues/20000

**Comment by pgaudet** [comment] 2020-10-20 11:40
I thought this ticket proposed to merge terms such as 
* 'RNA-directed RNA polymerase complex' & 'nuclear RNA-directed RNA polymerase complex'
* 'DNA-directed RNA polymerase complex', & 'cytosolic DNA-directed RNA polymerase complex' (bacterial - single annotation) , and 'nuclear DNA-directed RNA polymerase complex'
* ('mitochondrial DNA-directed RNA polymerase complex' and 'plastid-encoded plastid RNA polymerase complex' would remain)
* 'nuclear ubiquitin ligase complex' & 'ubiquitin ligase complex'

etc

**Comment by ValWood** [comment] 2020-10-20 12:20
I agree.
If it refers to the same complex merge, if it refers to different complexes (i.e. mitochondrial DNA-directed RNA polymerase complex) it remains (if that is what you are saying)

**Comment by pgaudet** [comment] 2020-10-20 12:59
Thanks @ValWood 
@krchristie is that OK for you ?

**Comment by krchristie** [comment] 2020-10-20 17:01
> If it refers to the same complex merge, if it refers to different complexes (i.e. mitochondrial DNA-directed RNA polymerase complex) it remains (if that is what you are saying)

I agree with @ValWood that when a location is used to distinguish different locations of the same complex that we want to merge terms, but that when the location is used as part of name to distinguish different complex that we want to keep the terms.

In looking at the examples @pgaudet listed above, I also see that there are some terms that are grouping terms for child terms that have a specific location. Do we want to have an explicit discussion in the editors call about whether we want grouping terms of this sort?

Here are some specific comments on some of the terms listed above:

`cytosolic DNA-directed RNA polymerase complex` (bacterial - single annotation) - this term is meant to be the term specific for eubacterial RNA polymerases, so it should not be merged, though we could consider renaming it, though be aware that the plastid RNA polymerases are closely related to the eubacterial RNAP, and are thus considered to be of a "bacterial-type" RNAP.

`nuclear DNA-directed RNA polymerase complex` - this is a grouping term to group the various nuclear RNA polymerases present in eukaryotes, distinct from mitochondrial and plastid polymerases that are/may also be present in eukaryotes. We could keep this if we want to keep grouping terms, but it should probably be added to the do_not_annotate subset

`mitochondrial DNA-directed RNA polymerase complex` and `plastid-encoded plastid RNA polymerase complex` would remain) - yes, these should remain as the location is used as part of the name to distinguish a specific complex that is different, rather than a difference in location of a complex that moves around.

`nuclear ubiquitin ligase complex` and its sibling `cytoplasmic ubiquitin ligase complex` - these appear to be grouping terms.

**Comment by bmeldal** [comment] 2020-10-20 17:20
I agree with @krchristie 

Where the location adds value because it has some influence on function (even if the basic function, e.g. adding nts, is the same) we can keep it. Often, these (as in Karen's examples) are small groups of very well defined complexes. But where the function is the same just in a different location it should probably be annotated with an AE for the location, like the ubiquitin ligases. There will also be cases where the same complex is found in different locations but still has the same function and then you would get into a whole new muddle if you made location-specific terms ;-)

Note: plastid-encoded plastid RNA polymerase complex also has 2 children, complexes A and B. Should that one also become do-not-annotate?

**Comment by tberardini** [comment] 2020-10-20 18:16
I would defer to @bmeldal on this one. They are plant terms but her expertise on complexes should take precedence.

**Comment by bmeldal** [comment] 2020-10-21 08:00
> I would defer to @bmeldal on this one. They are plant terms but her expertise on complexes should take precedence.

LOL, there are 0 annotations to the child terms! They are not use in CP either. But they were created in 2003...

So, definitely NO do-not-annotate on the parent or we loose ALL annotations ;-)

**Comment by pgaudet** [comment] 2022-08-24 09:04
@ValWood do you have a list of the complexes that would need to be merged? If not perhaps it's better to close this one until we have more specific actions.

**Comment by ValWood** [comment] 2022-08-24 09:07
OK, I will. open tickets as I see them. A lot have already been fixed.

**Closed by ValWood** 2022-08-24 09:07 UTC
Labels: Other term-related request, PomBase, protein complex, mini-project, GOC meeting
