### ISSUE TITLE
go-basic.obo from June 10, 2024 release has cycles

### ISSUE THREAD

**Issue by tutajm** [geneontology/go-ontology#28164] opened 2024-06-17 19:39 UTC
go-basic.obo was supposed to be acyclic. However, the release from June 10, 2024 contains cyclic relationships.

When we removed part-of relationships between:
 GO:0045258 and GO:0045282
 GO:0045257 and GO:0045281
 GO:0045274 and GO:0045282
 GO:0045273 and GO:0045281
the CC ontology became acyclic again.

The cyclic relationships are causing problems for our ontology tools. Please fix the file.

Thank you,
Marek Tutaj

**Comment by cmungall** [comment] 2024-06-17 23:01
I think this may have been fixed in the source: #27253 --- but it should never have made it into the release!

**Comment by pgaudet** [comment] 2024-06-18 06:07
Right, this should be fixed. 

@balhoff the issue here is that the circularity was caused by a part_of relation. We had something like this: 

- A
-- B (is_a A) 
--- C (is_a B part of A) 

Can we add a check for this? 

Thanks, Pascale

**Comment by balhoff** [comment] 2024-06-18 16:47
I added a check in #28186.

**Comment by ValWood** [comment] 2024-10-25 18:36
@pgaudet, is this out of date?

**Comment by balhoff** [comment] 2024-10-28 13:59
Done.

**Closed by balhoff** 2024-10-28 13:59 UTC
