### ISSUE TITLE
refine defs "barrier septum assembly"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11676] opened 2015-02-10 12:52 UTC
Barrier septum assembly is defined
The assembly and arrangement of a septum that spans the plasma membrane interface between progeny cells following cytokinesis. The progeny cells that form a barrier septum are not able to exchange intracellular material.
is positioned under "mitotic cytokinesis"

However, I just noticed that this term is used for prokaryotes.

Can we make this term generic, move it put from under mitotic cytokinesis but have new
  mitotic cytokinesis specific terms for eukaryotes (we do not have any meiosis specific annotations for this term yet as in fungi cytokinesis is part of sporulation and so its a bit different)

The existing term positive regulation of septation initiation signalling can stay under the new 
"mitotic barrier septum assembly" term, as this is eukaryote specific signalling pathway)

I am not sure if  the descendent "primary cell septum biogenesis"  can apply to non eukaryotes or not.

Suggest after this that all terms  which are descendants of mitotic or meiotic cell cycle get taxon restriction "only in eukaryotes"

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11505](https://sourceforge.net/p/geneontology/ontology-requests/11505)

**Comment by ValWood** [comment] 2016-04-18 14:46
This one is a quick fix.
I don't mind if you make this the generic species agnostic term, and create a new term  under mitotic cytokinesis. We can migrate annotations.
Will become more urgent when taxon restriction added for this branch.

**Comment by jimhu-tamu** [comment] 2016-09-21 01:45
What is the status of this item? I've been trying to go through the closed tracker items related to 
GO:0000935 ! barrier septum 

and

GO:0000917 ! barrier septum assembly

[This item](https://github.com/geneontology/go-ontology/issues/11362) asserts that barrier septa only occur in fungi and apparently a taxon constraint was added that is flagging a bunch of our annotations. But it is not clear to me from the definitions what aspect of the genus-differentia would restrict it to fungi while the parent term is more universal.

Note that aside from the septation that occurs in all cell division, there are bacteria that grow as chains with or without exchange of material across the septa dividing individual cells. For example [in Anabaena there is exchange across septa] (http://www.ncbi.nlm.nih.gov/pubmed/26748968). These would have non-barrier septa, while bacteria that do not exchange cytoplasm across the divisions would have barrier septa.

**Comment by ValWood** [comment] 2016-10-19 13:22
Your student tickets reminded me I had a note to comment on this ticket.
As you spotted there is a problem with this term.

So, we need a way to differentiate septation which occurs as part of mitotic cytokinesis in fungi (possibly other species), and bacterial septation.
(It is currently positioned under mitotic cytokinesis).

I  can't totally remember the history, but I seem to remember that the barrier septum terms were introduced for this reason, but if so they clearly didn't discriminate  adequately...

**Comment by ValWood** [comment] 2016-10-19 13:28
The original request would seem to work as a solution.
Make this term generic, and then create specific terms for
'barrier septum assembly involved in mitotic cytokinesis"

@jimhu-tamu j Do bacteria have primary and secondary septa?

**Comment by jimhu-tamu** [comment] 2016-10-19 15:19
Not sure, but my general rule is never underestimate what is found in bacteria.

**Comment by ValWood** [comment] 2017-11-21 16:51
We need to 

- [ ] 1 remove parent "mitotic citokinesis from
Barrier septum assembly 

-  [ ]  2. create a new term
barrier septum assembly, mitotic
The assembly and arrangement of a septum that spans the plasma membrane interface between progeny cells following mitotic cytokinesis. The progeny cells that form a barrier septum are not able to exchange intracellular material.

**Comment by pgaudet** [comment] 2017-11-22 07:40
Term labels were changed here #14241 

@ValWood Do you want to create the same child terms as for 'division steptum assembly: 
- GO:0000918 division septum site selection
-  GO:0010974 negative regulation of division septum assembly
- GO:0010973 positive regulation of division septum assembly
- GO:0031671 primary cell septum biogenesis (also has regulation terms; do we need this term???? 4 EXP pombase) 
- GO:0032955 regulation of division septum assembly
- GO:1990344 secondary cell septum biogenesis  (also has regulation terms; do we need this term???? 1 EXP pombase) 

Thanks, Pascale

**Comment by ValWood** [comment] 2017-11-22 10:09
* GO:0000918 division septum site selection
This one we do not need the mitosis specific term. In fungi the  septum site is determined by the "cytokinesis, site selection" it isn't a separate process. Please add a taxon restriction "only in prokaryotes"
same for


I would like to keep these:

GO:0031671 primary cell septum biogenesis (also has regulation terms; do we need this term???? 4 EXP pombase)
GO:1990344 secondary cell septum biogenesis (also has regulation terms; do we need this term???? 1 EXP pombase)

These are "substructures" of a fungal septum (different composition), and we have experiments to  differentiate.


GO:0032955 
GO:0010974 negative regulation of division septum assembly
GO:0010973 positive regulation of division septum assembly

regulation of division septum assembly we do need a "mitotic" term for these

**Comment by pgaudet** [comment] 2017-11-22 13:06
Hi Val, 

Is there really a difference between GO:0090529 cell septum assembly and GO:0000917  division septum assembly? 

Division septum assembly 
The assembly and arrangement of a septum that spans the plasma membrane interface between progeny cells following cytokinesis. The progeny cells that form a division septum are not able to exchange intracellular material. Source: GOC:mtg_cell_cycle


Cell septum assembly
The assembly and arrangement of a cellular component that is composed of peptidoglycan and often chitin in addition to other materials and usually forms perpendicular to the long axis of a cell or hypha. It grows centripetally from the cell wall to the center of the cell and often functions in the compartmentalization of a cell into two daughter cells. Source: GOC:mtg_cell_cycle
'Cell septum assembly' does not have any reference to mitosis, so perhaps that's the term that was intended for prokaryotes ? Do we really need two terms? 

Thanks, Pascale

**Comment by ValWood** [comment] 2017-11-22 13:44
Hi

The reason for the more specific term "division septum assembly"
is that most   biologists think of the septum as part of the  fungal division apparatus (it usually is), and it is good to have this term positioned as part of  cytokinesis. It enables us to collect the complete set of proteins involved in cytokinesis  under one term, which is very helpful for 
querying, slimming and QC.

so it is a bit of a fudge  but I think the process for the formation of a fungal hyphal septum might be different (because barrier septum assembly is dependent on the cytokinetic ring, it follows the closing of the aperture during ring constriction).

The more specific annotation captures the "normal" cytokinetic division aspect.

![cell septum](https://user-images.githubusercontent.com/7359272/33130024-dbb0beb8-cf89-11e7-951b-4f4c87921f27.jpg)

So I would prefer to keep it (also needed for prokaryotes)

That said, there are issues with the parent term, because it is not always part of cytokineses, 


there seems to be a lot of  flip-flopping here:

change log
2017-11-08 | Deleted | RELATION | part of GO:0000910 (cytokinesis)
-- | -- | -- | --
2017-05-22 | Added | RELATION | part of GO:0000910 (cytokinesis)
2017-04-06 | Deleted | RELATION | part of GO:0000910 (cytokinesis)
2013-05-09 | Deleted | RELATION | is a GO:0022402 (cell cycle process)
2013-04-26 | Added | SYNONYM | cell septum assembly involved in cell cycle cytokinesis
2013-04-26 | Added | RELATION | is a GO:0022402 (cell cycle process)
2013-04-26 | Added | RELATION | part of GO:0000910 (cytokinesis)
2013-04-26 | Added | SECONDARY | GO:0090530 (cell septum assembly involved in cell cycle cytokinesis)

also
this should not be an exact synonym of GO:0090529
cell septum assembly involved in cell cycle cytokinesis | exact


because  a septum is not always part of cytokineses
 (I would just remove this and check that the logical definitions agree)

**Closed** 2018-11-05 15:46 UTC
Labels: PomBase, cell cycle and DNA processes, quick fix
