### ISSUE TITLE
Revising  definition of Stn1-Ten1 complex & creating a new CST complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11915] opened 2015-06-10 10:31 UTC
Revising  definition of Stn1-Ten1 complex GO:0070188 and creating a new CST complex

Suggestion:

1.  Creating a new CST complex reflecting the three components Stn1, Ten1 and CTC1
Suggested definition of new CST complex:
A complex formed by the association of Cdc13 (CTC1 in mammals) with Stn1 in yeast (OBFC1 in mammals) and Ten1 protein. Binds to single-stranded telomeric DNA, and plays a role in telomere protection.

PMID: 19854130
PMID: 22965356

2. Tighten the definition of  Stn1-Ten1 complex to reflect the two components Stn1 in yeast (OBFC1 in mammals) & Ten1
e.g.
Suggested new definition of Stn1-Ten1 complex G0:0070188:
A complex formed by the association of Stn1 in yeast (OBFC1 in mammals) with Ten1 protein. This complex further associates with cdc13 in yeast (CTC1 in mammals) and single-stranded telomeric DNA, and plays a role in telomere protection.

PMID: 23826127
PMID: 20008938

Current definition of the Stn1-Ten1 complex G0:0070188:
A nuclear telomere cap complex that is formed by the association of the Stn1 and Ten1 proteins with telomeric DNA; in some species a third protein is present.

Thanks

Nancy

Reported by: noonoo25

Original Ticket: [geneontology/ontology-requests/11754](https://sourceforge.net/p/geneontology/ontology-requests/11754)

**Comment by NancyCampbell** [comment] 2015-07-29 08:12
@noonoo25

**Comment by NancyCampbell** [comment] 2015-07-29 08:20
@NancyCampbell

**Comment by NancyCampbell** [comment] 2015-07-29 20:30
@bmeldal

Hi Tanya & Birgit,

I have been trying to find evidence to show in vitro re-constitution of shelterin/telosome without DNA with no luck. So either it does not or no one has tried so we don't know. Based on the evidence that I found, we (probably?) can leave it as a protein/DNA complex (or not). PMID 15383534 uses gel filtration of nuclear extracts to show evidence for the existence of the shelterin proteins complex (so in reality the shelterin can include DNA even if we cannot see it) and the other paper PMID     21852327 uses EMSA, so definitely contains DNA.

Birigt, however, this creates a complex :-) (pun intended) issue, I will try to explain:

The shelterin complex as it stands on IntAct does not contain DNA as a component and thus I am able to annotate it with a DNA binding term GO:0090655 double-stranded/single-stranded junction telomeric DNA binding. If I am to bring this inline with GO then I would have to include the DNA as a component, which means I cannot annotate with a DNA binding term. The problem is this paper shows specifically that shelterin binds to a particular type of telomeric DNA at the double-stranded single-stranded junction in particular which as far as i know no database I know of provides an identifier eg. SO or Ensembl. 

The questions are:
1. should GO and IntAct match?
2. if yes, then is it possible on CP to add a general telomeric DNA term as a component and simultaneously add the DNA binding term as a GO annotation?

Sorry it complicates things.
Thanks.
Nancy

**Comment by bmeldal** [comment] 2015-07-30 07:26
Hi Nancy,

A dilemma indeed. If we want to make it clear what DNA it binds and use the GO terms as complex annotations we can't include the DNA as a participant.

However, we can create an internal molecule in IntAct that describes the DNA (I can show you how to do that if you haven't done it before) and then use it as a participant in the complex (without DNA binding GO annotations). We may be able to add the GO annotations to the internally-created molecule but I don't know where that would filter through. I'd have to ask Sandra or Max (developer) if that would get picked up by a search...

**Comment by tberardini** [comment] 2015-09-11 23:14
Are we waiting on Sandra/Max to figure out what to do with the parentage of GO:0000782 telomere cap complex and all its children?  GO:0043234 protein complex or protein-DNA complex.

I think if the GO complex is defined as having both protein and DNA, it makes sense for IntAct to reflect that.  Like I said, most of the terms under telomere cap complex have DNA as a component in their definitions.  An example is the shelterin complex, this GO term:
http://amigo.geneontology.org/amigo/term/GO:0070187

**Comment by bmeldal** [comment] 2015-09-15 08:46
Hi all,

I asked Sandra for her opinion as she created the original telosome cx: She agrees with Nancy that DNA should be part of the complex, it doesn't really get isolated without. I will ask ChEBI if they can create the junctional term, then we can use that as participant. If not, we'll create an internal interactor.

With regards to Nancy's problem of annotating to DNA binding, I think she can annotate the individual protein to DNA binding, just not the complex.

I think if we fix the complexes with DNA as participant, then we have also aligned this with the GO defs that mention DNA.

I hope that helps,

Birgit

**Comment by tberardini** [comment] 2015-09-15 16:58
Thank you, Birgit, that does help!  Can you go ahead and create the new CST complex term? If you let me know when you've put it into TG, I'll go in and approve it.   I'll then send out the obsoletion email and schedule the replacement of GO:0070188 Stn1-Ten1 complex with this new term.  The parentage of GO:0000782 telomere cap complex and all its children will remain 'protein-DNA complex.'

**Comment by bmeldal** [comment] 2015-09-16 07:29
@NancyCampbell , as you create your own complexes now, could you create the CST in the CP and GO, please? I'll look at the CP complex as soon as it comes to me for checking.

Birgit

**Comment by NancyCampbell** [comment] 2015-09-16 08:48
Birgit, of course no probs. Will do.
Thanks.
Nancy

**Comment by bmeldal** [comment] 2015-09-16 08:54
Thanks, Nancy!

**Comment by tberardini** [comment] 2015-09-18 23:37
Hi Nancy, Please let me know when you've requested the GO cc term through TG.

**Comment by NancyCampbell** [comment] 2015-09-29 08:23
Hi Tanya, 
I don't seem to have access to freeform and I have not used it before. Is it straightforward?
Do you know who I should write to to see if they can allow me access? 
Thanks
Nancy

**Comment by tberardini** [comment] 2015-09-29 16:04
Write to help@go.termgenie.org for TermGenie FreeForm permission.  It's quite straightforward.  For guidance on how to use, I think you've got at least one person in office with you who has permissions, they can guide you through the first few times.  Becky is the most experienced of the current UCL group.  Of course, Birgit has the most experience in creating protein complex terms. Let me know if you have trouble.

**Comment by bmeldal** [comment] 2015-09-29 16:18
Thanks, Tanya.

Nancy, if you are stuck and Rebecca can't help, please ping me, and I'll talk you through it. In fact, the details should be in the long and ridiculously detailed complex curation manual. If you don't have it, I'll email it to you. The only bit missing is that we can now add all the capable_of and capable_of_part_of relationships directly :) [I need to update the manual - one day...]

Birgit

**Comment by NancyCampbell** [comment] 2015-09-30 08:50
Thanks Tanya. I have just written to ask for access right.
Birgit, I have a copy of the manual dated 4Dec2014 and just checked the instructions which seem straightforward. Thanks.

**Comment by NancyCampbell** [comment] 2015-10-20 13:54
Hi Tanya,
Just created the term in TermGenie freeform 
CST complex GO:1990879
Please go ahead with the obsoletion Tanya.
Thanks.
Nancy

**Comment by tberardini** [comment] 2015-10-20 16:46
Hi Nancy,

Has the term been approved?   I don't see it waiting in the approval queue.

Thanks,

Tanya

**Comment by NancyCampbell** [comment] 2015-10-21 09:01
Hi Tanya,
It has been committed. Is that the same as approval? 
Here is the email I received from TermGenie: (Let me know if there is anything else I need to do at this stage). Thanks Tanya.

Your requested term has been committed to the ontology.
GeneOntology TermGenie <help@go.termgenie.org>
16:18 (17 hours ago)
Hello,

after a review the following requested term has been committed to ontology:

[Term]
id: GO:1990879
name: CST complex
namespace: cellular_component
def: "A complex formed by the association of Cdc13 (CTC1 in mammals) with Stn1 in yeast (OBFC1 in mammals) and Ten1 protein (also TEN1 in mammals) with single-stranded telomeric DNA. The CST complex plays a role in telomere protection." [GOC:BHF, GOC:BHF_telomere, GOC:nc, IntAct:EBI-10043724, IntAct:EBI-8801830, IntAct:EBI-8801947, PMID:19854130, PMID:22965356]
subset: termgenie_unvetted
synonym: "Cdc13-Stn1-Ten1 complex" NARROW [GOC:nc]
synonym: "CTC1-OBFC1-TEN1 complex" NARROW [GOC:nc]
is_a: GO:0000783 ! nuclear telomere cap complex
relationship: capable_of_part_of GO:0000723 ! telomere maintenance
created_by: nc
creation_date: 2015-10-20T13:51:07Z

Commit Message:
TermGenie commit for user: nc reviewed by dos
Added GO:1990879 CST complex

**Comment by tberardini** [comment] 2015-10-21 17:05
Alert sent today:

**Comment by tberardini** [comment] 2015-11-05 17:53
Obsoletion and replacement done.

**Closed by tberardini** 2015-11-05 17:53 UTC
Labels: auto-migrated, BHF-UCL, New term request, protein complex

**Comment by bmeldal** [comment] 2015-11-11 14:37
Hi @NancyCampbell,

I have finally tracked down ChEBI and they can create the ds-ss junction telomeric DNA as a molecular which we can then use as an interactor for the complex. I will forward you my initial email to ChEBI but thought I'd record here that we can add the molecule to the complex.

**Comment by cmungall** [comment] 2015-11-11 14:50
Is the request on the CHEBI tracker?

**Comment by bmeldal** [comment] 2015-11-11 18:44
Not yet. Gareth suggested to just email to the chebi ebi address as it'll be him doing it anyway.Would it help you to add it to the chebi tracker?

In any case, these are @NancyCampbell 's terms so I asked her to make the request :)
(strategic delegation!!!)

**Comment by NancyCampbell** [comment] 2015-11-13 10:48
Hi,
Birgit, I have just sent an email to ChEBI requesting this new entry.

**Comment by bmeldal** [comment] 2017-12-19 09:12
@NancyCampbell did we ever get that term from ChEBI?

**Comment by bmeldal** [comment] 2017-12-19 10:28
Found ChEBI ticket and acted upon it, ignore this comment!

**Comment by NancyCampbell** [comment] 2017-12-19 11:56
note: @bmeldal created entry on ChEBI using submittion tool CHEBI:139320

**Comment by pgaudet** [comment] 2017-12-19 15:52
Shouldn't we be using sequence ontology rather than chebi here?

Le 19 déc. 2017 12:56 PM, "NancyCampbell" <notifications@github.com> a
écrit :

**Comment by NancyCampbell** [comment] 2017-12-19 16:04
@pgaudet 
@bmeldal 
As far as I understand, Birgit created the ChEBI ID in this instance for use in the complex portal editor (i.e. not GO). Is that right @bmeldal ?

**Comment by bmeldal** [comment] 2017-12-19 17:06
Yes, we use ChEBI in IntAct or the CP when we need a generic interactor that has no sequence.

**Comment by deustp01** [comment] 2017-12-19 17:28
But, shouldn't PRO be in the business of providing those terms where the required interactor is a whole protein or a protein complex? Is this a scope problem to be sorted out by PRO and ChEBI, or a practical problem, that while the relevant ontology is solidly in scope for PRO, the needed high-leel terms do not exist there so ChEBI gets used as a placeholder?

**Comment by bmeldal** [comment] 2018-01-02 09:59
@deustp01 we use ChEBI for nucleic acids where we can't use a specific sequence. As the shelterin complex assembles on telomeres of different chromosomes there is no specific sequence ID we could use for this complex participant. Somehow, the ChEBI request fell through the cracks and I spend the last few days before the holidays looking at ancient tickets and notes etc to clear some back log and this one was one.

There is no GO action required, I just wanted to close the circle with respect to a comment on this thread from >2 years ago.

**Comment by deustp01** [comment] 2018-01-02 14:38
@bmeldal to be honest, so do we, and for the same reasons, and it works fine. In principle, PRO should create and maintain terms for generic proteins and maybe some kinds of complexes. They should use such terms as parents of their terms for specific proteins, I think, and I think that as part of their mission to create a proper ontology structure to represent proteins and relationships among them they would make this a fairly high priority. In the meantime, however, the ChEBI terms work fine. (Is this adequate to close the circle?)

**Comment by bmeldal** [comment] 2018-01-02 14:43
I think this can be deemed closed :)

I understand what PRO is doing but a generic protein or complex term wouldn't help with the generic **nucleic acid** that's part of this complex.

**Comment by deustp01** [comment] 2018-01-02 14:48
Closed, for sure.

My basic problem here is that I really like an old Michael Ashburner distinction, between encoded molecules - DNA, RNA, protein - and unencoded ones, and think the scope of ChEBI should be the latter. So there's a tension between wanting a well-maintained, responsive source for the annotation terms we need and and wanting scope of ontologies to be well-defined and stable.
