### ISSUE TITLE
another new term for lncRNA 

### ISSUE THREAD

**Issue by rbalakri** [geneontology/go-ontology#12096] opened 2015-10-14 21:50 UTC
HI,

Term name: regulation of synapse organization by regulation of gene expression
Reference: http://www.ncbi.nlm.nih.gov/pubmed/20729808
Annotate Malat1 from this paper to this new term.

Rama

**Comment by tberardini** [comment] 2015-10-14 23:56
@vanaukenk, I'm not sure I want to add this new term.  There are no precedents for terms like 'regulation of X by regulation of gene expression'.  It's so general, even though these are the words of the authors.  I do see terms like 'regulation of gluconeogenesis by regulation of transcription from RNA polymerase II promoter'  so maybe 'regulation of synapse organization by regulation of transcription from RNA polymerase II promoter'?  I can add that by TermGenie but I wanted to run the idea by you first. 

What do you think, Kimberly?

**Comment by vanaukenk** [comment] 2015-10-15 13:03
Hi @tberardini,  I just read the paper and it looks like the most specific experimental finding wrt gene expression is that, using an inducible transgene array, depletion of Malat1 results in decreased localization of pre-mRNA splicing factors to sites of active gene transcription:
"These results show that Malat1 ncRNA modulates the recruitment of SR-type pre-mRNA-splicing factors to/at active transcription sites."

There are then additional experiments, such as microarrays and qRT-PCR experiments, that demonstrate altered expression of genes whose products are involved in nuclear organization and function as well as synapse development.

So....I think if we wanted to create a more specific term than 'regulation of synapse organization by regulation of gene expression', perhaps we could consider terms like 'regulation of synapse organization by posttranscriptional regulation of gene expression' or 'regulation of synapse organization by regulation of pre-mRNA splicing factor localization'?

Let me know what you think.

**Comment by ValWood** [comment] 2015-10-15 13:57
Hi,

I was looking at this and I thought it seemed a little odd. 

 The authors say "this transcript is retained in the nucleus where it is thought to form molecular scaffolds for ribonucleoprotein complexes" .....so it is likely to be some post transcriptional processing role. A later paper also implicates it in ‘gene expression’ but not regulation of transcription from polII
http://cancerres.aacrjournals.org/content/73/3/1180

We should be careful about over interpreting these types of exp as regulation of gene expression of particular sets of genes. Couldn't the synaptic defects could easily be a phenotypic effect caused by an RNA processing defect,  but  which have stronger consequences in some cell types than others,  depending which gene products are normally expressed in that cell rather than real biological regulation? If you look at neurones you will see phenotypes related to neuronal processes/expression....?

Also, is it likely that synapse organization is really directly regulated by splicing factor localization? The localization is a bit of a stretch too  because it is possible that the RNP complexes cannot form correctly  which is why you see a localization defect.  

We see this  type of phenotypic effect a lot.....effects in the splicing machinery can cause problems with replication, cell size, cell division etc...this doesn't mean that the splicing is regulating this process in a normally functioning cell....The authors do say “modulating the expression of genes” but they don’t do experiments to show that this  this is really 'regulatory'  in a normally functioning cell. It is probably just stuffing up an upstream process...... these look like pleiotropic phenotypes. 

(really need a way to capture likely very indirect phenotypes.....)

**Comment by vanaukenk** [comment] 2015-10-15 15:27
Thanks for your thoughts, @ValWood.

Given the experimental observations in this paper, what annotations would you be comfortable making?

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2944070/

**Comment by ValWood** [comment] 2015-10-15 18:05
I'm not sure. We are really fussy though.... and we can capture phenotypes which helps us a lot. I can see the urge to capture the affect on synaptogenesis but it really looks indirect.

- There is enough data to imply it has some role downstream of transcription.

- However, it isn't very clearly "regulating" a specific subset of genes (the GO analysis does not show this, it just shows enrichment of genes across many categories expected in the cell type they are studying if you perturb gene expression generally). If I were reviewing I would have wanted to know how this compared to downregulation of any splicing factor....Maybe more highly spliced genes are more affected? 

- It isn't clearly localization of splicing factors (it affects localization, but it could also be structural). On balance, if we could be sure that all SR proteins are involved in splicing I would go to  "mRNA splicing, via spliceosome". 

- It *could* be that this is part  of a subcomplex which  really is regulating  a specific subset of genes, but I don't get that from this data....

v

**Comment by vanaukenk** [comment] 2015-10-15 18:37
Hi @ValWood,
I agree that there is enough data to imply a role downstream of transcription.
Wrt the specificity of the response, I think the authors try to address this in the experiments described in the last paragraph of the paper, where they look at the expression of six different genes, four neuronal and two housekeeping.  Expression changes are seen for three of the six genes; two show decreased expression and one is either unchanged or increased, depending upon the antisense oligo used.  From these results, as well as the knockdown and overexpression phenotypes also described, the authors conclude:
"Together, these results suggest that in neurons, Malat1 ncRNA regulates the expression efficiency of a subset of genes controlling synapse formation, which consequently results in the regulation of synaptogenesis."
I agree that, within the scope of this paper, the exact mechanistic details are not addressed, but I think if we don't somehow connect Malat1 ncRNA to synaptogenesis, we're not capturing one of the major points of the paper.
I would be okay with a term like:
'regulation of synapse organization by posttranscriptional regulation of gene expression'
since I think it connects the two things the authors wish to connect, but doesn't go so far as to suggest exact mechanism, for which they don't provide detailed evidence.
 --Kimberly

**Comment by ValWood** [comment] 2015-10-15 19:03
The expression level changes seem low (50% reduction?), and could be due to the fact that housekeeping/highly expressed genes genes have fewer introns or are otherwise less affected by mutations in the splicing machinery......We would probably not  curate an equivalent experiment  for gene specific GO process regulation. However, I think we use "regulation" more strictly. We  would not necessarily want to know the mechanistic details, but we would need to be convinced that   this was not only a phenotype caused by a problem with the general splicing machinery. I'm sure that a defect in splicing doesn't not affect all genes equivalently in the same way that a defect in core transcription machinery does not affect all genes equivalently. I can however see the rationale for capturing it this way in the absence of another mechanism to make this connection..... and if you annotate then 'regulation of synapse organization by posttranscriptional regulation of gene expression' is the best suggestion for this.

Val

**Comment by vanaukenk** [comment] 2015-10-15 19:14
@tberardini, if you are okay with a new term: 'regulation of synapse organization by posttranscriptional regulation of gene expression' then let's go with that.

**Comment by tberardini** [comment] 2015-10-15 19:29
Sorry I'm a little late to the party.  Thank you Val and Kimberly for your help.  I like 'regulation of synapse organization by posttranscriptional regulation of gene expression'.  I'll create the term and notify here when TermGenie is back.  Currently not working but should be back soon.

**Comment by tberardini** [comment] 2015-10-15 21:38
after a review the following requested term has been committed to ontology:

[Term]
id: GO:1904739
name: regulation of synapse organization by posttranscriptional regulation of gene expression
namespace: biological_process
def: "A posttranscriptional regulation of gene expression that results in regulation of synapse organization." [GO_REF:0000063, GOC:rb, GOC:TermGenie, PMID:20729808]
synonym: "regulation of synapse development by posttranscriptional regulation of gene expression" EXACT [GOC:TermGenie]
synonym: "regulation of synapse morphogenesis by posttranscriptional regulation of gene expression" RELATED [GOC:TermGenie]
synonym: "regulation of synapse organisation by posttranscriptional regulation of gene expression" EXACT [GOC:TermGenie]
synonym: "regulation of synapse organization and biogenesis by posttranscriptional regulation of gene expression" RELATED [GOC:TermGenie]
is_a: GO:0010608 {is_inferred="true"} ! posttranscriptional regulation of gene expression
is_a: GO:0050807 {is_inferred="true"} ! regulation of synapse organization
intersection_of: GO:0010608 ! posttranscriptional regulation of gene expression
intersection_of: regulates GO:0050808 ! synapse organization
relationship: regulates GO:0050808 {is_inferred="true"} ! synapse organization
created_by: tb
creation_date: 2015-10-15T21:25:46Z

**Closed by tberardini** 2015-10-15 21:38 UTC
