### ISSUE TITLE
change defalt-namespace back to gene_ontology

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12141] opened 2015-10-29 20:05 UTC

**Comment by tberardini** [comment] 2015-10-29 20:38
Edited the file to change namespace back to gene_ontology.  Then opened file in OE, saved out again to see if my settings were introducing the bogus namespace.  I was unable to reproduce the change.  I've committed the fixed version back to the repo.  Changes should percolate through to the public versions with regularly scheduled updates.

-default-namespace: file:/Users/tanyaberardini/go_svn/ontology/extensions/ro_pending.obo
+default-namespace: gene_ontology

**Closed by tberardini** 2015-10-29 20:38 UTC
