### ISSUE TITLE
NTR: substrate mycelium formation

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12742] opened 2016-10-18 02:09 UTC
'Substrate mycelium formation' is an additional specific term, along with 'aerial mycelium formation' (#12659) and 'acquisition of mycelium reproductive competence'  (#12660) that can be used to replace the ambiguous term  'mycelium development' (#12613) which has been proposed for obsoletion.

NTR: 'substrate mycelium formation'
This process of growth occurs in some fungal species that grow as network of invasive thread-like filaments formed from chains of attached cells within a solid or semi-solid substrate.

**Comment by paolaroncaglia** [comment] 2016-10-18 14:31
Hi @dianeoinglis ,
I added as follows, please see below for questions:

 [Term]
+id: GO:0097738
+name: substrate mycelium formation
+namespace: biological_process
+def: "The process by which, in some fungal species, hyphae grow as a network of invasive thread-like filaments formed from chains of attached cells within a solid or semi-solid substrate." [GOC:di]
+is_a: GO:0019954 ! asexual reproduction
+is_a: GO:0048856 ! anatomical structure development
+relationship: only_in_taxon NCBITaxon_Union:0000020 ! Fungi or Bacteria

Questions:

- [ ] Please provide a PMID or other reference

- [ ] Are both is_a parents correct? In particular, should ‘substrate mycelium formation’ be is_a ‘anatomical structure formation involved in morphogenesis’ instead of ‘anatomical structure development’?

- [ ] Is the taxon rule ok as is, or should it be only in Fungi? Based on your suggested definition.

Thanks.

**Comment by paolaroncaglia** [comment] 2016-10-18 14:33
@dianeoinglis 
Lastly, when you create the FAO term for ‘substrate mycelium’, please post its ID here, and

- [ ] I will add a logical axiom to GO:0097738 ‘substrate mycelium formation’.

**Comment by fusarium** [comment] 2016-10-18 15:31
PMID: 10021365 for  ‘substrate mycelium formation’ 

Beneath seems all correct:
+is_a: GO:0019954 ! asexual reproduction
+is_a: GO:0048856 ! anatomical structure development
+relationship: only_in_taxon NCBITaxon_Union:0000020 ! Fungi or Bacteria

**Comment by paolaroncaglia** [comment] 2016-10-18 15:56
Thanks @fusarium

**Comment by paolaroncaglia** [comment] 2016-12-12 16:42
Wrapping up this ticket, the only action item left to do is
- [ ] when a FAO term is created for ‘substrate mycelium’, use its ID to add a logical axiom to GO:0097738 ‘substrate mycelium formation’.

**Comment by paolaroncaglia** [comment] 2017-02-16 11:39
Hi @ukemi,
I’ve completed my tasks for this ticket, and the only thing left to do (low priority) is to add a logical definition if/when a FAO term is created (details above). Therefore I will now unassign myself from this ticket. However, since unassigned tickets tend to fall through the cracks when they’re not recent, I will assign it to you (as main ontology editor at this stage), and you can then hand it over to others if and as appropriate. Thanks.

**Comment by ukemi** [comment] 2018-02-26 20:10
I still don't see this term in the FAO. @dianeoinglis do you know when it will be added?

**Comment by dianeoinglis** [comment] 2018-03-05 07:45
The FAO will undergo a major revision as soon as some basic numbering issues are resolved. Hopefully before end of March 2018.
Thanks!

**Comment by pgaudet** [comment] 2018-10-01 19:12
@mah11 can this term added to FAO ? 

Thanks, Pascale

**Comment by mah11** [comment] 2018-10-02 09:11
it's on the to-do list ...
https://github.com/obophenotype/fungal-anatomy-ontology/issues/12

**Closed** 2018-11-08 12:38 UTC
Labels: New term request, development, external dependencies
