### ISSUE TITLE
GO:0008253 5'-nucleotidase activity should not be linked to  GO:0006470 protein dephosphorylation It could be linked directly to dephosphorylation (GO:0016311)

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12005] opened 2015-08-07 15:37 UTC
From @pgaudet

**Comment by paolaroncaglia** [comment] 2015-08-11 12:54
Closing it as duplicate of https://github.com/geneontology/go-ontology/issues/12003

**Closed by paolaroncaglia** 2015-08-11 12:54 UTC
