### ISSUE TITLE
chitin-based cuticle extracellular matrix

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11952] opened 2015-07-06 20:13 UTC
Hi,
I'd like to request a new term to annotate gene products to the C. elegans pharnygeal cuticle, a chitin-based extracellular matrix.

GO:0005578 proteinaceous extracellular matrix

> GO:new chitin-based cuticle extracellular matrix

Definition: A chitin-based, noncellular structure that is synthesized by an underlying cell layer. An example of this type of cuticle is found in the pharynx of the nematode Caenorhabditis elegans.  The C. elegans pharyngeal cuticle lines the pharyngeal lumen and contains specialized structures that function as sieves and grinders to transport and break down food, respectively.
PMID:25361578
PMID:25262818
PMID:16098962 

It might also be good to broaden the definition of the parent term to be more inclusive:

An extracellular layer consisting of proteins (such as collagens) and carbohydrate-containing molecules (such as proteoglycans or chitin) that forms a sheet underlying or overlying cells such as endothelial and epithelial cells. The proteins are secreted by cells in the vicinity. 

Thanks,
--Kimberly 

Reported by: vanaukenk

Original Ticket: [geneontology/ontology-requests/11791](https://sourceforge.net/p/geneontology/ontology-requests/11791)

**Comment by pgaudet** [comment] 2019-05-30 15:01
@ukemi was this addressed in the work you did on the ECM ?

**Comment by ukemi** [comment] 2019-05-30 15:16
Not specifically, but would this term work?

collagen and cuticulin-based cuticle extracellular matrix GO:0060102?

**Comment by ukemi** [comment] 2019-05-30 15:28
Actually, it looks like the pharyngeal cuticle is different.  It has chitin in it, but do we want to distinguish that or would it be done at the level of the anatomical structure as indicated above? Chitin is not a gene product. @vanaukenk

**Comment by hattrill** [comment] 2019-06-01 21:39
Very timely :) It would be good to distinguish 'cuticle' as a cellular component.

'collagen and cuticulin-based cuticle extracellular matrix' not good for arthopods where collagens are basement membrane components (whereas in C.elegans there are collagens that make up a substantial component of the cuticle). Cuticulin is more of a concept than a thing, I think - tends to belong to the waxy covering of the chitineous cuticle and is prob some lipidy mix.

I think either we would want a simple: cuticle, that would have the basic definition:
cuticle: The cuticle is an apical extracellular matrix. It provides protective, skeletal and structural functions, forming part of the exoskeleton and barrier between tissues and the environment.

Or a separate arthopod/chitin-based cuticle (if composition matters):
chitin-based cuticle: an apical extracellular matrix principally composed of chitin and cuticular proteins. It provides protective, skeletal and structural functions, forming part of the exoskeleton and barrier between tissues and the environment.
Ref:PMID:17628275
PMID:15453918 
PMID:20347980

Note that we have collagen and cuticulin-based cuticle and chitin-based cuticle distinctions in process ontology already:
e.g.
GO:0018996 	molting cycle, collagen and cuticulin-based cuticle 	
GO:0007591 	molting cycle, chitin-based cuticle
ditto for cuticle development, &etc

**Comment by cmungall** [comment] 2019-06-02 00:03
Seems fine but either the AOs would need to cede the label 'cuticle' (renaming to something like 'cuticular covering'...?) or GO should keep the more awkward 'cuticle ECM'

**Comment by ukemi** [comment] 2019-06-03 12:39
I think cuticle fits better as an anatomical structure.

**Comment by hattrill** [comment] 2019-06-03 13:02
As a structural component? how about a combination of EC location, and composition:

-apical ECM
--chitin-based cuticle (which is actually a part of the cuticle not the whole structure - procuticle, but in practice, little emphiasis given to distinguishing)
--collagen and cuticulin-based cuticle

**Comment by ukemi** [comment] 2019-06-03 13:04
It would make sense to me to have an ECM as a cellular component that is part of an anatomical structures that is a cuticle. The question is whether we want to go to the level of chitin-based ECM and how it would differ or group with the existing terms. Do they still all contain collagen?

**Comment by hattrill** [comment] 2019-06-03 14:56
The arthropod cuticle is devoid of collagens, the nematode cuticle is packed full of collagens - they've got tonnes of cuticle-specific collagens. (WormBook says: "It is a highly structured extra-cellular matrix (ECM), composed predominantly of cross-linked collagens, additional insoluble proteins termed cuticlins, associated glycoproteins and lipids.").  
I think I'd have to go through this with Kimberly to get to the bottom of the difference and whether it is worth making the distinction.

**Comment by ukemi** [comment] 2019-06-03 15:00
OK. I'm happy to add the new ECM types if you let me know what to add and where to add them. I still think it would be best to have the terms represent an ECM at the cellular level rather than a cuticle at the gross anatomical level.

**Comment by hattrill** [comment] 2019-06-03 15:06
@vanaukenk do you want to have a chat about this?

**Comment by hattrill** [comment] 2019-06-12 17:23
Hi @ukemi, having mulled this over an done some curation,  would like to request this term:

chitin-based cuticle extracellular matrix 
is_a extracellular matrix GO:0031012
def: Any constituent part of a chitin-based noncellular, hardened, or membranous extracellular matrix secreted from the apical surface of an epithelial sheet.
Ref: PMID:23955854

Thanks

**Comment by ukemi** [comment] 2019-06-12 18:36
HI @hattrill,

Would there ever be a need for a chitin based ECM that is not in the cuticle? That is, would it be better to just make the chitin-based extracellular matrix?

**Comment by ukemi** [comment] 2019-06-12 18:37
I think your def would fit that.

**Comment by ukemi** [comment] 2019-06-12 18:52
Looking back at my old Invertebrate Zoology book (brings back fond memories), I can confirm that the radula of a mollusc is made of chitin. Is it composed of an an ECM? I'm not sure about that but it wouldn't hurt to broaden the term. If you concur I will make it so.

**Comment by hattrill** [comment] 2019-06-13 07:43
There is also the peritrophic matrix or membrane which lines the midgut of most insects (PMID: 30902530). So I am fine with making it "chitin-based extracellular matrix" as it can cover a multitude of things.

**Closed** 2019-06-13 14:11 UTC
Labels: cellular component, time medium (>2 <24h)

**Comment by hattrill** [comment] 2019-06-14 06:20
Thanks!
