### ISSUE TITLE
NTR: negative regulation of cholesterol esterification

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#17643] opened 2019-07-23 14:31 UTC
PMID:21810484 shows that ABCA2 is involved in 'negative regulation of cholesterol esterification'. A GO term like this does not currently exist.

It will be an is_a child of 'GO:0010872 regulation of cholesterol esterification' (and a 'sibling' of 'GO:0010873 positive regulation of cholesterol esterification') and a negatively_regulates child of 'GO:0034435 cholesterol esterification'.

cc @RLovering

**Comment by ValWood** [comment] 2019-07-23 14:46
but isn't this only because mobilization  to the ER is reduced in the mutant? They don't show that this is regulatory in  a normal situation, its just  directly upstream (probably provides input for?).

**Comment by BarbaraCzub** [comment] 2019-07-24 08:33
Hi Val, Ruth and I have discussed this thoroughly several times and we do generally agree with what you are saying. We have considered whether to use a regulation term for this annotation or the acts_upstream_of qualifier (which does feel more appropriate indeed). 
However, the issue is that we do not know/understand what gets exported from GO and goes into enrichment analysis tools. How are the qualifiers considered/used by the analysis tools, if at all?
If the qualifiers are disregarded, or dropped, by analysis tools, then we felt it would be more appropriate to capture the information from this paper using the regulation term (even though it is not direct) than using the qualifier in case it would be disregarded. 
We would not want ABCA2 to become a part of a group of genes _involved_in_ cholesterol esterification (rather than being upstream of it, or regulating it) in any analysis results.
Thanks for your feedback!
Barbara

cc @RLovering

**Comment by ValWood** [comment] 2019-07-24 11:15
There is no evidence in this paper that this is regulatory though?
To me, it seems more of a phenotype (i.e affects cholesterol metabolism ), so the way to curate right now would be to the term itself (not regulation) with 'acts_upstream of'.

I too am confused about the filtering options with these qualifiers, and when to use them. However the use of regulation is quite well defined, it needs to be demonstrated that it is  "control" (or inferrable if there is not a suitable experiment). You can also infer from functions  that are known to be regulatory like kinases, and other signalling molecules, but I don't think you can infer regulation from a transport component. The transporter would need to be demonstrated to be a "sensor" of some sort to be acting as a regulator ? Otherwise the transporter could be constitutively transporting any available substrate (in this case the transporter would not be doing any actual regulating. i.e it isn't necessarily regulating just because it is upstream).

I feel that the best approach is to curate in the correct way (not regulation here) and get GO to 
change tools and educate people about the new syntax.  Otherwise we make a lot more work for ourselves later as we need to fix things.

One option would be for GO to keep annotation with the new qualifiers  like "acts_upstream_ of out of the GO database and AmiGO  until we can can deal with the qualifier and the changes are announced to the community.  This would  prevent problems for analysis  caused by these qualifiers in the interim.

 I share your concerns about analysis and the new qualifiers.  There is also a total lack of understanding of which qualifiers to use when/where  (or maybe that is just me). I don't understand how we can use these  without clearly defined beginnings and ends of processes.
Anyway, ignore my comments if the editors think this is an appropriate term to use. I just think its more work for later...

**Comment by RLovering** [comment] 2019-07-24 16:26
Hi Val
my feeling is that the proteins regulating cholesterol levels work together to maintain the homeostasis. ABCA2 regulates cholesterol homeostasis and one of the ways it does this is by  decreasing the levels of low-density lipoprotein receptor, which leads to a lower level of cholesterol import. 
In a second paper: PMID:24201375 ABCA2 overexpression in N2a neuroblastoma cells was associated with an altered bilayer distribution of the sphingolipid ceramide that inhibited acylCoA:cholesterol acyltransferase (ACAT) activity and cholesterol esterification. 
ACAT is SOAT1 https://www.uniprot.org/uniprot/P35610 and it catalyzes the formation of fatty acid-cholesterol esters, which are less soluble in membranes than cholesterol.
This second paper supports the annotation that ABCA2 negatively regulates cholesterol esterification
Best
Ruth

**Comment by pgaudet** [comment] 2019-07-24 16:57
Why not annotate to 'cholesterol homeostasis' then ?

**Comment by RLovering** [comment] 2019-07-24 17:46
we have

**Comment by ValWood** [comment] 2019-07-24 18:25
"Cholesterol homeostasis" seems a more accurate  annotation  to describe this.

**Comment by RLovering** [comment] 2019-07-25 08:53
well yes but there are 2 downstream processes here:

1. ABCA2 regulates the expression of low-density lipoprotein receptor, which leads to a lower level of cholesterol import. This is part of the process of cholesterol homeostasis

2. ABCA2 regulates the distribution of the sphingolipid ceramide which inhibits acylCoA:cholesterol acyltransferase (ACAT) activity; as ACAT esterifies cholesterol, cholesterol esterification is reduced.
Regulation of cholesterol esterification is a different part of the process of cholesterol homeostasis, than the regulation of the expression of LDLR.

Before reading my rant below please note that I am aware that perhaps examplar cases of GO annotation and how GO-CAM models are being exported to GPAD files do exist and that I have just not been attending the right meetings to appreciate where they are and how to apply these new rules. In which case, I humbly apologise for my rant, and would be very grateful if someone would point me to them so that Barbara and I can improve our GO annotations.

____________________________________________________________________________________________________

I find it very difficult without any real guidance about how the GO-CAM models are going to be converted into GPAD files for many of the GO analysis tools to use, and also with no guidance about how the new qualifiers will be used to create GPAD files. I find this all incredibly demoralising, and now dread asking for new GO terms due to a the continual battles that arise when I/we do. I now choose more general terms and insert the ChEBI ID in the AE field rather than requesting a regulation term for the specific existing term. I no longer feel like I understand what is going to be accepted as an annotation.

Following my previous annotation practice I would annotate ABCA2 as negatively regulating cholesterol esterification. Note that the current definition of almost all regulation terms starts the same, for example: ANY PROCESS that modulates the frequency, rate or extent of cholesterol esterification. There are currently 15 human proteins associated with the GO term regulation of cholesterol esterification, so there is no suggestion of over association of this term with 'every' human protein. 

I think the approaches that are being taken by Pascale, Kimberly and Val to review GO annotations are great, and at UCL we are doing our best to keep up with the revisions that are being requested. But more needs to be done to provide examples of annotating specific processes so that these can be discussed and agreed upon and then used as examplar GO annotation approaches. I could then go back to all the human proteins currently annotated to processes like cholesterol esterification and the regulation of this process and revise these annotations in line with the 'new' system. In fact this might be a great basis for a grant application because reviewing all the annotations associated with human proteins is not a 5 min job. But other than reviewing all annotations I agree with Val that it is important to be trying to create annotations now that won't get deleted in the future. With examplar systems established and promoted we would have more chance of creating new annotations which are following these rules.

@cmungall @judyblake @thomaspd @ukemi @vanaukenk

**Comment by ValWood** [comment] 2019-07-26 11:42
Hi Ruth,

I agree that the guidelines are currently unclear.

My take n regulation is that there needs to be some evidence for "control" i.e activation (via signalling), or a rate limiting step. Not just "affects" by upstream. This is why to me this seems like an acts_upstream_of annotation, rather than regulation.

However, lots of people do use regulation when a mutation affects a process. My understanding is that  acts_upstram_of was to  provide a better way to annotate "upstream of" but not regulating.

I think a lot of the confusion here is that the GO definition of "regulation" is quite vague, as you point out here

"ANY PROCESS that modulates the frequency, rate or extent of cholesterol esterification."

To me, this definition is  a little weak, because it doesn't really exclude any "acts upstream of" 
The word  "modulate"  was used to imply "controlling influence" , possibly wording indicating "control" more explicitly would be an improvement. I have mentioned this before.

I only commented on this ticket because I am interested in the boundaries between "regulation" and acts_upstream_of. At the moment, we seem to have thrown a lot of new annotation syntax into the mix without defining precisely what the differences are.

This paper abstract says
It is important to study the role of ABCA2 in regulating cholesterol homeostasis in neuronal-type cells because ABCA2 has been identified as a possible genetic risk factor for Alzheimer's disease. In this study, the effects of ABCA2 expression on cholesterol homeostasis were examined in mouse N2a neuroblastoma cells. ABCA2 reduced total, free- and esterified cholesterol levels as well as membrane cholesterol but did not perturb cholesterol distribution in organelle or lipid raft compartments.

So "cholesterol homeostasis" seemed appropriate.

Because these experiments are performed in cell lines overexpressing ABCA2 endogenously
(which might change LOTS of levels of all sorts of substrates, but does not necessarily imply that these levels are physiologically controlled by this gene product)

The authors then say
"These results are consistent with the results observed in CHO cells and show that ABCA2 expression results in reduced levels of esterification of lipoprotein-derived cholesterol by ACAT in the endoplasmic reticulum."
But they don't say "regulates" because this would be an over-interpretation of the experiments.

I guess what I am saying is that you can't infer from this particular paper that this is bona fida regulation. Which is why "act_upstream_of" or "provides_substrate_for" seems more appropriate. However,  we are probably pickier  about when we use regulation at PomBase- because such a lot of the work is genetics we see what a large knowdown effect  knockdown or overexpression can have without  being regulatory.

**Comment by RLovering** [comment] 2019-07-26 13:19
Hi Val
I have created a GO-CAM model for this and also revised some of the annotations, by reading the papers through again. Role of ABCA2 in cholesterol esterification gomodel:5d29221b00000268

The annotations that derive from the GO-CAM model do not include any regulation of cholesterol esterification annotations, I added these in the model as causally_upstream_of. In my annotation set (see figure below) I have added regulation of cholesterol esterification with the acts_upstream_of qualifier. I believe that the maintenance of ceramide at the outside of the plasma membrane neg regulates sphingomyelin biosynthesis by restricting the access of the enzymes to the ceramide substrate. I can see that provides substrate for (or prevents providing substrate for) would be appropriate, but I think that the impact of the activity of ABCA2 to the sphingomyelin biosynthesis is close enough to state this is regulating it. Especially now I have discovered that BP terms connected to the model with causally_upstream_of or directly_provides_input_for relations do not get associated with the entity annotated when created in GO-CAM. In the model I have used directly_provides_input_for  and part_of for 2 different 'regulation of a biosynthetic process' terms and only one of them is exported to the annotation file. 

Best

Ruth

**Comment by ValWood** [comment] 2019-07-26 14:03
So I still don't understand if we should use regulation or not here. The acts upstream of seems to cover it for me , so it would be good to get precise guidelines.  @vanaukenk Could we do this one in an annotation call?

Also, I am confused now by the MF term. This  gene products ABCA2 is annotated as a transmembrane transporter  (from other sources), and a "floppase" here.
I'm not aware of any gene products which do both transmembrane transport and intramembrane transport simultaneously.

Which paper gives the experimental evidence for floppase?  (these tend to belong to a very  small set of evolutionarily conserved families which (which to my knowledge doesn't include this family). It would be good to establish this as I was going to create a rule for transporter intersections.

Cheers

Val

**Comment by ValWood** [comment] 2019-07-26 14:10
Found it,
http://europepmc.org/abstract/MED/8898203
I will check the transmembrane annotations

**Comment by RLovering** [comment] 2019-07-26 14:18
Sorry Val
I annotated as a floppase based on https://www.ncbi.nlm.nih.gov/pubmed/?term=24201375 but maybe it should be a transporter. 
Ruth

**Comment by ValWood** [comment] 2019-07-26 16:24
I will look into the transporter. It might be  a terminology issue, I can't figure it out but I will dig in  to the intersections and open a ticket if the families aren't multifunctional. It seems like there was some historical disagreement:

C.F Higgins, M.M Gottesman
Is the multidrug transporter a flippase?
Trends Biochem. Sci., 17 (1992), pp. 18-21

that might be subsequently resolved.

**Comment by ValWood** [comment] 2019-07-26 18:45
I looked at the intersection
https://github.com/geneontology/go-annotation/issues/2567
unfortunately,  although I could resolve most families I was not able to be sure for this particular family as I don't know enough about the mechanism (the flipping could be part of bringing the lipid *through* the membrane, and in this case is it still classed as a flippase? I don't know)

This annotation https://github.com/geneontology/go-annotation/issues/2569 should move to the intermebrane term (this one is intra, although it isn't clear from the GO term)

**Comment by vanaukenk** [comment] 2019-07-29 15:23
Hi @BarbaraCzub @RLovering @ValWood 
I'm just back from vacation and catching up on tickets.  

This is a really interesting discussion and very important for how we think about annotating regulation of processes and functions going forward.  I think we do want to move towards a more restrictive application of regulation terms such that we only use those terms and relations when we understand the mechanism of the regulation.  I also prefer to think of regulation as a proximal, or direct, effect on an MF, although this is definitely an area where we need to discuss more examples to be sure this will accurately capture the important biology.

Here are some more specific thoughts on the cholesterol esterification example, all in the general vein of trying to elucidate what is known about mechanism:

1.  Wrt both conventional annotation and GO-CAM, the best starting point is to think about the MFs for each of the gene products wrt the BP you're trying to model.  In this particular case, then, what is the MF of ABCA2 wrt cholesterol esterification?  Is it a transporter? A floppase? Is it even known?  The function of ACAT seems straightforward.

2. For each MF, where does it occur? Again, here ACAT seems straightforward, but what about ABCA2?  Wrt its effect on cholesterol esterification, is it acting in the plasma membrane? the late endosome? the lysosome?  Is it known?

3. If we can determine the MF and location of that MF for ABCA2, how many steps then are in between the ABCA2 MF and the MF of ACAT?  Can we connect the dots directly, or are there other MFs in between?  If there are other MFs, do we know what they are?

I haven't read through all of the reported experiments in the papers, but from reviewing the results and reading over the discussions, I'm inclined to agree with Val that, right now, the more appropriate annotation for ABCA2 would be 'acts upstream of' (and I would even suggest we include directionality and use 'acts upstream of, negative effect') to 'cholesterol esterification'.  This would be in addition to annotations to 'cholesterol homeostasis' which it sounds like you've already made.  The reason I would choose this qualifier over annotating to a regulation term is that I didn't see exactly where and how the MF of ABCA2 directly effects the MF of ACAT.

The issue of how to handle enrichment analyses with these new qualifiers is extremely important and, as @hattrill reminds us, even consistently applying these qualifiers is still very much a work-in-progress for GO.  So, it's good to discuss these examples (and maybe this ticket should be moved to go-annotation instead), to crystallize our concepts of regulation vs acting upstream (and  how far upstream we think is reasonable to go).  And, in the meantime, we may also want to seriously consider keeping the 'acts upstream of' annotations in a separate GAF or GPAD so users can decide if and how they want to use those annotations.

**Comment by RLovering** [comment] 2019-07-31 10:35
Transferred this discussion to  the annotation tracker
What annotations have value? #2570

**Closed** 2019-07-31 10:35 UTC
Labels: ARUK-UCL, New term request
