### ISSUE TITLE
TPV: ammonium transmembrane transport children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14928] opened 2018-01-25 18:01 UTC
_From @ValWood on January 25, 2018 17:20_

These look odd?
V

GO:1902616    acyl carnitine transmembrane transport | is_a
GO:1903091    pyridoxamine transmembrane transport | is_a
GO:1903711    spermidine transmembrane transport | is_a
GO:1903710    spermine transmembrane transport | is_a
GO:0072489    methylammonium transmembrane transport | is_a
GO:1902603    carnitine transmembrane transport

_Copied from original issue: geneontology/go-annotation#1783_

**Comment by pgaudet** [comment] 2018-01-25 18:01
_From @ValWood on January 25, 2018 17:23_

Also "spermine" has the parent "drug transmembrane transport"

**Comment by pgaudet** [comment] 2018-01-25 18:01
_From @ValWood on January 25, 2018 17:24_

Seems odd since we define 
ammonium transmembrane
Ammonium is the cation NH4+

**Comment by pgaudet** [comment] 2018-01-25 18:01
_From @deustp01 on January 25, 2018 17:32_

The pK of ammonia is about 9, so at pH 7 about 99% of ammonia molecules are protonated - NH4+ - and as pH falls the protonated fraction increases more, so what's actually getting transported is probably that charged entity. I think most of those other molecules that can be described as derivatives of ammonia also have alkaline pKs so they too will be mostly protonated at neutral pH (Not sure whether this helps or not.)

**Comment by pgaudet** [comment] 2018-01-25 18:01
I dont think GO should reason over this.  In ChEBI spermidine is a **derivative** of NH4. However a spermidine transporter is not necessarily an ammonium transporter. The reasoner says that spemidine is a subclass of ammonium, not a derivative. 

I'll add this to the editors call to get more information. 

Thanks, Pascale

**Comment by ukemi** [comment] 2018-01-25 18:39
But as was pointed out in the original ticket, the actual molecule that is being transported is the ion, which as we have said over and over again before is equivalent in GO (PMID:23895341). In ChEBI spermidine (3+) is an ammonim ion. Therefore our reasoning is sound. If we don't think spermidine (3+) should be an ammonium ion, it would need to be changed in ChEBI.

**Comment by ValWood** [comment] 2018-01-25 18:53
I thought it sounded familiar,  but I couldn't find the original ticket

Personally I don't think its good that if you search for "ammonium transporters" you get spermidine  and other polyamine transporters (just because these compounds have an amino group)

https://en.wikipedia.org/wiki/Spermidine
but I don't know what the issue is biochemically

**Comment by ukemi** [comment] 2018-01-25 18:58
again:

The pK of ammonia is about 9, so at pH 7 about 99% of ammonia molecules are protonated - NH4+ - and as pH falls the protonated fraction increases more, so what's actually getting transported is probably that charged entity. I think most of those other molecules that can be described as derivatives of ammonia also have alkaline pKs so they too will be mostly protonated at neutral pH 

Therefore even though we call it spermidine (because biologists often use these names imprecisely, PMID:23895341), what is actually being transported is likely to be spermidine (3+).

**Comment by ValWood** [comment] 2018-01-25 19:57
I can't see the GO logical defs in the term browsers, but is the issue that the 

ammonium transporter links to CHEBI CHEBI:35274- ammonium ion  (generic)
instead of its descendant CHEBI:28938 - ammonium or CHEBI:16134  ammonia  (specific for NH 4 +   or ammonia NH3)


In GO the ammonium transporter textual def is
The directed movement of ammonium into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. Ammonium is the cation NH4+ which is formed from N2 by root-nodule bacteria in leguminous plants and is an excretory product in ammonotelic animals. Source: ISBN:0198506732

There is no way to retrieve ammonium/ammonia transporters that does not include all of these much larger molecules. Im more interested in  the compound than the  conjugate form, since this does not appear to be entirely clear:


"The Amt proteins form a trimer in which each monomer contains 11 transmembrane helices and has an NH 4 +  recruitment site and a narrow hydrophobic pore that allows the passage of NH  but not NH 4 + , leading to the view that AmtB is a gas channel (Khademi  et al . 2004)."

**Comment by pgaudet** [comment] 2018-01-25 20:34
Hi @ukemi 
For me the problem remains - a spermidine transporter does not transport ammonium, even if spermidine contains an ammonium group. Maybe it's OK chemically, but biologically that assertion is misleading. 

Pascale

**Comment by ValWood** [comment] 2018-01-25 20:57
Agreed, I still think a small change to the logical def of ammonia transport/transporters would fix...

**Comment by pgaudet** [comment] 2018-01-31 13:07
Hi @ValWood 
This is how ChEBI defines is: 
spermidine (CHEBI:16610) is conjugate base of spermidine(3+) (CHEBI:57834) 
spermidine(3+) (CHEBI:57834) is a ammonium ion (CHEBI:35274) 

So this is a question for ChEBI. Can you open a ticket there ? https://github.com/ebi-chebi/ChEBI/issues
(and perhaps close this one?) 

Thanks, Pascale

**Comment by ValWood** [comment] 2018-02-08 09:16
https://github.com/ebi-chebi/ChEBI/issues/3420

**Comment by ValWood** [comment] 2018-10-01 13:15
prompted CHEBI

**Comment by pgaudet** [comment] 2019-04-04 09:36
any news ?

**Comment by ValWood** [comment] 2019-04-04 09:39
nope. pinged again.

**Comment by ValWood** [comment] 2019-08-09 17:28
pinged chaebi again
https://github.com/ebi-chebi/ChEBI/issues/3420

I didn't really understand the last comment

**Comment by cmungall** [comment] 2019-08-09 18:52
I responded on the ticket, see my comments there.

This has been open for a while. I think we need to get a faster cycle here. Perhaps as a matter of routine if there are blockers where we are not on the same page we arrange a call/zoom? I invited CHEBI to join one of our ontology calls.

I do think a lot of this would be helped by CHEBI having more obo-like definitions, so we could better understand the intended meaning of a class, which in turn informs whether a classification makes sense (in this case it clearly doesn't and CHEBI needs to turn this into a has-part)

**Comment by cmungall** [comment] 2019-08-09 18:54
@pgaudet: 

> For me the problem remains - a spermidine transporter does not transport ammonium, even if spermidine contains an ammonium group. Maybe it's OK chemically, but biologically that assertion is misleading

exactly. The core problem here is that chebi are not representing this properly, they are conflating has-part and is-a. If they switch the relation to has-part then we no longer get the inference.

**Comment by deustp01** [comment] 2019-08-09 19:09
No, I  don't think that is what ChEBI is doing. Their problem is that two different chemical entities, with two different ChEBI IDs, have the same name, "ammonium".
CHEBI:28938 "ammonium" - "An onium cation obtained by protonation of ammonia" is NH4+, and is the entity that biochemists (and Pascale and Val and I) envision when they hear the word "ammonium"
CHEBI:35274 "ammonium ion" - "Ammonium, NH4+, and derivatives formed by substitution by univalent groups" means, from its definition any of a large collection of molecules formed by substituting various possible chemical entities for one of the hydrogen atoms of ChEBI:28938. The name change between 28938 and 35274 is unhelpful, because every biochemist will point out that NH4+ **_is_** an ion and so will regard "ammonium" and "ammonium ion" as synonyms even though ChEBI means the two names to refer to two clearly different chemical entities. (And spermidine is formally a derivative of biochemist ammonium, formed by substituting other chemical entities for two of the hydrogens of ammonium, so it is correctly classed as a child of ChEBI "ammonium ion".

**Comment by ValWood** [comment] 2019-11-27 17:59
This seemed to be fixed in CHEBI in august, but I still get the incorrect inferences?

**Comment by pgaudet** [comment] 2019-11-28 18:18
@ValWood Do you still see incorrect inferences ?

**Comment by ValWood** [comment] 2019-11-28 21:32
yes 
spermine/spermidine/pyridoxine  transporters still annoated to ammonium
https://www.pombase.org/term/GO:0072488

**Comment by cmungall** [comment] 2019-12-02 13:00
The chebi ticket is still open - it's not clear to me it's been
satisfactorily resolved?

**Comment by pgaudet** [comment] 2019-12-02 15:48
Well I dont know ! It sounded like it may resolve the GO issue but didn't.

**Comment by cmungall** [comment] 2019-12-02 18:18
OK I went back and read what they did on Aug 13. They relabeled the CHEBI:35274 from 'ammonium ion' to 'ammonium ion derivative'. I think they should have obsoleted, or retained CHEBI:35274 for 'ammonium'.

Anyway, the path forward is clear. We should change all cases of

 * CHEBI:35274 ! ammonium ion derivative "A derivative of ammonium, NH4(+), in which one (or more) of the hydrogens bonded to the nitrogen have been replaced with univalent organyl groups. The substituting carbon of the organyl group must not itself be directly attached to a heteroatom (thereby excluding protonated amides, hemiaminals, etc)."

to

 * CHEBI:28938 ! ammonium "An onium cation obtained by protonation of ammonia."

or to

 * CHEBI:16134 ! ammonia "An azane that consists of a single nitrogen atom covelently[sic] bonded to three hydrogen atoms."

(which of the two should not matter as they are in a conjugate base/acid relationship, so transport etc definitions will be equivalent)

Assuming that this is what we mean

overall we need to improve things here. This ticket has been open 2 years. Having an accurate representation of biochemistry is obviously massively important for GO. We need to be faster at communicating with CHEBI to resolve these. We can always invite the CHEBI team onto calls to discuss these issues. Medium to longer term there needs to be a more satisfactory treatment of different protonated forms in CHEBI with clear protonation-neutral superclasses. And there needs to be clarity about what X actually means vs what is an X derivative.

**Comment by pgaudet** [comment] 2020-01-17 11:39
I changed CHEBI:35274 ! ammonium ion to CHEBI:28938 ! ammonium 

@ValWood Please close if that finally fixes the problem. 

Thanks, Pascale

**Comment by ValWood** [comment] 2020-01-21 09:12
not yet, normally it would show by now. But @kimrutherford is on holiday so we may not have daily updates.... will check again

**Comment by ValWood** [comment] 2020-01-21 11:53
@mah11  says the change hasn't made it through the GO pipeline yet.

**Comment by ValWood** [comment] 2020-01-28 13:40
YES!!!!!

**Closed by ValWood** 2020-01-28 13:40 UTC
Labels: external dependencies, targeting and transport
