### ISSUE TITLE
Need checks and constraints for bract development.  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17025] opened 2019-03-12 10:25 UTC
_From @cerivs on March 11, 2019 23:21_

I found a improper zebrafish annotation to bract development GO:0010432 (that I made by accident)  which is showing up on the current data release of amigo.  It looks like there should be error reports  to let us know if there are data issues but I don't think they are running.  Annotation has been in place for at least a couple of years.  
Usage of term should be restricted to phyllome.  If this ticket needs to be moved to a different tracker please do.  

Annotation has been updated so the bad data should go away but we still need a report if we violate the constraint.

![image](https://user-images.githubusercontent.com/2602957/54164250-2eb51000-4419-11e9-8661-37c9b743d948.png)

_Copied from original issue: geneontology/go-annotation#2289_

**Comment by pgaudet** [comment] 2019-03-12 10:25
@cerivs We put these requests in the ontology tracker. I'll move this one. 

Thanks, Pascale

**Comment by ValWood** [comment] 2019-03-12 10:59
When will taxon restrictions be working again?

**Comment by cmungall** [comment] 2019-03-12 13:20
@pgaudet the constraint is there in PO, we'll check what is going on cc @balhoff @dougli1sqrd 

@ValWood not sure what you mean can you open a new ticket?

**Comment by ukemi** [comment] 2019-03-12 13:21
I see an anonymous ancestor for this being only_in Viridiplantae. This looks like it is coming from PO. Not sure why it isn't being used. @balhoff @dougli1sqrd ?

**Comment by pgaudet** [comment] 2019-03-12 13:46
Taxon constraints are reported in the reports but not filtered. 

We would really like to have them filtered in AmiGO, and in the files we produce. 
They would still be in reports, and when submitting groups fix them, they would come back (iunder the correct annotation). 

Thanks, Pascale

**Comment by ValWood** [comment] 2019-03-12 13:49
I thought we were waiting for some new method to be implemented by Jim?

https://github.com/geneontology/go-ontology/issues/16722

**Comment by ValWood** [comment] 2019-03-12 13:51
I agree I saw this when I was trying to track the status
https://github.com/geneontology/go-site/issues/763
should be a hard check, as they are incorrect as they stand. the curator used the wrong term.

**Comment by balhoff** [comment] 2019-03-12 13:56
I commented over on #16722.

**Comment by ukemi** [comment] 2019-03-14 12:50
@balhoff, I'm still not sure why the PO taxon constraints aren't being used.

**Comment by balhoff** [comment] 2019-03-14 13:50
@ukemi where is the problem? Was the taxon violation not in the report? I think the annotation was already fixed, because I can't find it in snapshot.

**Comment by ukemi** [comment] 2019-03-14 17:25
From the comments above, I concluded that the taxon violation was not detected. @ValWood? 

What did you mean by:

> When will taxon restrictions be working again?

**Comment by ValWood** [comment] 2019-03-14 17:37
It's OK, I was under the impression that they were not currently being reported...but it is possible that they are. We can't check because we don't have any examples right now.

**Comment by balhoff** [comment] 2020-04-09 16:11
I confirmed that `'bract development' and 'in taxon' some 'Vertebrata <Metazoa>'` is unsatisfiable, will go ahead and close this.

**Closed by balhoff** 2020-04-09 16:11 UTC
Labels: taxon constraints
