### ISSUE TITLE
add taxon restriction, GO:0016032 | viral process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13940] opened 2017-07-19 16:48 UTC
GO:0016032 | viral process

I don't know how strict you want to be with this  one, since the definition indicates host terms can be annotated to viral processes (I still don't understand how that works!)

but minimally "never in yeast" would work to hide the terms from our users

**Comment by pgaudet** [comment] 2017-07-19 16:51
Hi @ValWood 

This is a duplicate of #13214 
If it's urgent I can add never in yeast for now, until the problem is sorted. 

Thanks, Pascale

**Comment by ValWood** [comment] 2017-07-19 17:37
I forgot about that one. That would work...

**Closed** 2017-07-20 16:26 UTC
Labels: PomBase, Taxon restriction
