### ISSUE TITLE
Add taxon constraints for taxon-specific terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11313] opened 2014-09-08 09:48 UTC
Add taxon constraints for cases where the taxonomic group is cited in the term name e.g. bacterial degradosome, plant-type vacuole, nematode larval development.

Reported by: jl242

Original Ticket: [geneontology/ontology-requests/11136](https://sourceforge.net/p/geneontology/ontology-requests/11136)

**Comment by paolaroncaglia** [comment] 2015-10-27 16:08
Started working on 'Should be only in Bacteria' list above. Done so far:

bacterial-type RNA polymerase regulatory region DNA binding 
transcription from bacterial-type RNA polymerase promoter 
Gram-positive-bacterium-type cell wall 
Gram-negative-bacterium-type cell wall 
bacterial nucleoid 
bacterial nucleoid DNA packaging 
bacterial pre-replicative complex 
bacterial-type DNA replication
Gram-negative-bacterium-type cell wall biogenesis
Gram-negative-bacterium-type cell outer membrane assembly

**Comment by paolaroncaglia** [comment] 2015-10-27 16:11
Hi Tanya @tberardini 

As agreed for the taxonomy JBMS paper, could you please help me with adding taxon rules to plant-related terms if any are missing? The idea is

"Add taxon constraints for cases where the taxonomic group is cited in the term name [or definition, or definition comment] e.g. bacterial degradosome, plant-type vacuole, nematode larval development."

Any question or comment let me know, and thanks again for your help!

Paola

**Comment by paolaroncaglia** [comment] 2015-10-27 16:22
'Should be only in Bacteria' list above: done:

bacterial-type flagellum organization
Actinobacterium-type cell wall biogenesis 
bacterial-type flagellum-dependent cell motility
bacterial-type EF-P lysine modification
bacterial cellulose biosynthetic process
bacterial degradosome

Next up, 'Should be never in Eukaryotes' from list above etc.

**Comment by cmungall** [comment] 2015-10-27 20:07
Some of the gross anatomy related ones should come from PO

E.g.
https://en.wikipedia.org/wiki/Flowering_plant

**Comment by tberardini** [comment] 2015-10-27 20:09
Does PO have taxon constraints? Ah, see the PO issue now.

**Comment by tberardini** [comment] 2015-10-27 20:10
Should we defer to PO then for the TCs for anatomical related stuff and I'll look at other branches of GO?

**Comment by cmungall** [comment] 2015-10-27 20:23
I think anything subcellular would still be the domain of GO, just punt on development of gross structures to PO

**Comment by tberardini** [comment] 2015-10-28 00:27
Which constraint?  Should I be evaluating these on a one-by-one basis by looking in the literature? If any parent term (regardless of is_a, part_of, regulates) has the constraint, do I need to add the constraint to the children terms?

Existing plant-y constraints:

relationship: only_in_taxon NCBITaxon:33090 {id="GOTAX:0000422"} ! Viridiplantae (green plants)
relationship: only_in_taxon NCBITaxon:3398 {id="GOTAX:0000418"} ! Magnoliophyta (flowering plants)

Note that there are various GOTAXI:ids for both Viridiplantae (95 ids) and Magnoliophyta (32 ids), all with the same NCBITaxon:id.  Which one is correct or are they all valid? Why are there so many?

To do list:  (has 'plant' in primary term name) - many of these are already constrained but I haven't checked systematically

name: plant-type vacuole
name: plant-type vacuole lumen
name: plant-type cell wall
name: plant-type hypersensitive response
name: plant-type cell wall organization
name: plant-type vacuole membrane
name: plant-type cell wall modification
name: plant-type cell wall loosening
name: plant-type cell wall modification involved in multidimensional cell growth
name: plant-type cell wall biogenesis
name: plant-type primary cell wall biogenesis
name: plant-type secondary cell wall biogenesis
*name: cell plate formation involved in plant-type cell wall biogenesis
name: regulation of plant-type hypersensitive response
name: negative regulation of plant-type hypersensitive response
name: positive regulation of plant-type hypersensitive response
name: plant-type cell wall cellulose catabolic process
*name: plant-type spore development
name: seed germination on parent plant
name: plantlet formation on parent plant
name: plant-type cell wall cellulose biosynthetic process
name: plant-type cell wall cellulose metabolic process
name: plant-type cell wall assembly
name: plant-type cell wall organization or biogenesis
name: regulation of plant-type cell wall organization or biogenesis
name: plant cell papilla
name: plant epidermis development
name: plant epidermis morphogenesis
name: plant epidermal cell differentiation
name: plant epidermal cell fate specification
name: cysteine-type endopeptidase activity involved in plant-type hypersensitive response
name: plant-type cell wall loosening involved in abscission
name: flavonoid transport from endoplasmic reticulum to plant-type vacuole
name: plant seed peroxidase activity
name: regulation of plant-type cell wall cellulose catabolic process
name: negative regulation of plant-type cell wall cellulose catabolic process
name: positive regulation of plant-type cell wall cellulose catabolic process
name: regulation of plant-type cell wall cellulose biosynthetic process
name: negative regulation of plant-type cell wall cellulose biosynthetic process
name: positive regulation of plant-type cell wall cellulose biosynthetic process

punt to PO:

name: plant-type ovary development
name: plant parenchymal cell differentiation
name: regulation of plant epidermal cell differentiation
name: negative regulation of plant epidermal cell differentiation
name: positive regulation of plant epidermal cell differentiation

**Comment by cmungall** [comment] 2015-10-28 00:39
TCs propagate over most relations (across ontologies too, but we need to fix the import chains). This includes has_part. Helps to think in terms of OWL existential restrictions. X SubClassOf R some Y.

If you accidentally introduce redundancy it's not a big deal. Ideally we'd like a reference for each TC (can't be done in OE). So if there are two separate statements, and one subsumes the other, it can still be useful to have the redundant one, as the evidence for the second may be retracted.

It looks like you only have a handful you need to worry about in the above: vacuoles, cell walls.

You can punt even more to PO: e.g.

```
[Term]
id: GO:0090558
name: plant epidermis development
namespace: biological_process
def: "The process whose specific outcome is the progression of the plant epidermis over time, from its formation to the mature structure." [GOC:tb]
is_a: GO:0009888 ! tissue development
intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of PO:0005679 ! epidermis
relationship: only_in_taxon NCBITaxon:33090 ! Viridiplantae
created_by: tanyaberardini
creation_date: 2014-02-27T15:17:37Z
```

Let's say we didn't have the TC on that. We can assume that we'd get that from PO (maybe with a more specific taxon - I'm guessing the first viridiplantae didn't have an epidermis). But let's leave all existing ones in until we sort out import chains, and get TCs into PO

**Comment by paolaroncaglia** [comment] 2015-10-28 13:10
Thanks Tanya and Chris.
Tanya, in reply to your questions

"Note that there are various GOTAX:ids for both Viridiplantae (95 ids) and Magnoliophyta (32 ids), all with the same NCBITaxon:id. Which one is correct or are they all valid? Why are there so many?"

They are all valid. They used to be created by the 'old' system - one for each TC added.

Cheers,
Paola

**Comment by tberardini** [comment] 2015-11-11 01:26
Plant ones remaining:

name: flavonoid transport from endoplasmic reticulum to plant-type vacuole
name: plant seed peroxidase activity
name: plant cell papilla

name: plant-type cell wall organization or biogenesis
name: regulation of plant-type cell wall organization or biogenesis


name: plant-type hypersensitive response
name: regulation of plant-type hypersensitive response
name: negative regulation of plant-type hypersensitive response
name: positive regulation of plant-type hypersensitive response
name: cysteine-type endopeptidase activity involved in plant-type hypersensitive response

**Comment by tberardini** [comment] 2015-11-11 01:58
Can't commit changes due to the UBERON synonym problem which has caused OE to come to a screeching halt.  Will try again tomorrow.

**Comment by tberardini** [comment] 2015-11-11 17:22
Added TCs.  Back to holiday. :+1:

**Comment by paolaroncaglia** [comment] 2015-12-10 16:38
Added:

archaeal or bacterial-type flagellum-dependent cell motility 
- never in Eukaryotes

archaeal-type flagellum-dependent cell motility
archaeal-specific GTP cyclohydrolase activity
archaeal-type flagellum
- only in Archaea

Next up: look at non-prokaryotic and nematode-related terms; possibly more.

**Comment by paolaroncaglia** [comment] 2015-12-10 17:29
Note for self: will restrict the following to be only in eukaryotes:

eukaryotic 43S preinitiation complex
eukaryotic 48S preinitiation complex
eukaryotic 80S initiation complex
eukaryotic translation elongation factor 1 complex
eukaryotic translation initiation factor 2 complex
eukaryotic translation initiation factor 2B complex
eukaryotic translation initiation factor 3 complex
eukaryotic translation initiation factor 4F complex

eukaryotic elongation factor-2 kinase regulator activity
eukaryotic initiation factor 4E binding
eukaryotic initiation factor 4G binding
eukaryotic initiation factor eIF2 binding
eukaryotic translation initiation factor 2alpha kinase activity
eukaryotic translation initiation factor 3 complex assembly
eukaryotic translation initiation factor 4F complex assembly
sulfurated eukaryotic molybdenum cofactor(2-) metabolic process

**Comment by paolaroncaglia** [comment] 2015-12-10 17:31
Note for self: term names containing 'nematode' are already all taxon-constrained.

**Comment by paolaroncaglia** [comment] 2015-12-11 07:49
Added rules to last set of terms above. Closing now.

**Comment by paolaroncaglia** [comment] 2016-08-05 12:51
Re-opening because it looks like a few plant-related terms may be missing taxon restrictions. I ran across these:
- ‘plant cell papilla’ (Def: “A cell projection that is a short, rounded projection from a plant epidermal cell.” Def comment: ”Part of papilla cell (PO:0025166), which is a shoot epidermal cell (PO:0025165) in plants. Replaces the obsolete term papillae (PO:0002001).”) Weird because @tberardini listed this term in this ticket on Nov 11, 2015. 
- ‘pollination’ 
- ‘pollen wall’

Suggestions for ‘rules’ to catch them all:
Search for ‘plant’ not only in term labels, but also in term definitions; in term comments too?
Search for ‘PO:’ (presumably only in def comments?)
Search for ‘pollen’/‘pollin’ in term labels and definitions
Others?

**Comment by paolaroncaglia** [comment] 2016-08-05 12:52
(Will ask Tanya when she's back from leave)

**Comment by tberardini** [comment] 2016-08-17 01:01
I'm pretty sure I skipped all the ones that had PO xps because I thought that taxon-restrictions would be imposed at the source ontology (PO) and then inherited.

**Comment by paolaroncaglia** [comment] 2016-09-09 14:03
Thanks @tberardini (and sorry for the delay). 

@cmungall : Tanya writes "I thought that taxon-restrictions [for plant terms such as pollination etc, see above] would be imposed at the source ontology (PO) and then inherited.". Is this (still) the case? Is this filed as a ticket somewhere? Many thanks,

Paola

**Comment by cmungall** [comment] 2016-10-07 21:35
From @cooperl09

> The taxon restraint is incorrect for microspore- see https://www.britannica.com/science/microspore

I reverse inferred the PO one from GO:

```
[Term]
id: GO:0009556
name: microsporogenesis
namespace: biological_process
def: "The process in which the microsporocyte undergoes meiosis, giving rise to four haploid microspores." [GOC:mtg_plant, GOC:tb]
synonym: "microspore development" EXACT systematic_synonym []
is_a: GO:0048236 ! plant-type spore development
intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of PO:0020048 ! microspore
relationship: only_in_taxon NCBITaxon:3398 {id="GOTAX:0000141"} ! Magnoliophyta
relationship: part_of GO:0009555 ! pollen development
```

The text definition is suspiciously unlike the OWL definition. cc @tberardini

**Comment by tberardini** [comment] 2016-10-07 23:16
This is going to require more thought. What's giving me the most trouble is the 'from its formation to the mature structure part'. Even applying this def to the parent, 'plant-type spore development' doesn't seem quite right.  I'll consult with Leonore on Monday, while looking at the parentage.

**Comment by tberardini** [comment] 2016-10-12 23:51
After discussion with @lreiser, we will move this term and its children out from the 'anatomical structure development' branch into the 'sexual sporulation' branch.  The taxon restriction is fine.  Will take care of the xps too.

**Comment by tberardini** [comment] 2016-10-18 00:30
Ok. Cleaned up.

**Comment by paolaroncaglia** [comment] 2016-12-14 10:59
@tberardini thanks for taking care of ’microsporogenesis’.

@cmungall: wrapping up, I think we still need to resolve the following (or have I missed some communication?):
The following terms refer to plants but don’t have taxon rules (yet):
plant cell papilla
pollination
pollen wall
There may be more (see my comment here for ideas to search them https://github.com/geneontology/go-ontology/issues/11313#issuecomment-237842225).
Tanya writes "I thought that taxon-restrictions [for plant terms such as pollination etc, see above] would be imposed at the source ontology (PO) and then inherited.". Is this (still) the case? Is this filed as a ticket somewhere? Many thanks.

**Comment by cmungall** [comment] 2016-12-14 18:15
On 14 Dec 2016, at 2:59, paolaroncaglia wrote:

> @tberardini thanks for taking care of ’microsporogenesis’.
>
> @cmungall: wrapping up, I think we still need to resolve the following 
> (or have I missed some communication?):
> The following terms refer to plants but don’t have taxon rules 
> (yet):
> plant cell papilla

we should axiomatize the comment:

```
comment: Part of papilla cell (PO:0025166), which is a shoot epidermal 
cell (PO:0025165) in plants. Replaces the obsolete term papillae 
(PO:0002001).
```

and inherit

> pollination

what would the desired TC be here? We know the species that are 
pollinated. Do we have an exhaustive list of all species that pollinate? 
I read last week that some marine arthropods and worms pollinate 
seagrass. Though there was some controversy as to whether this was true 
pollination.

> pollen wall

and part_of to PO

**Comment by lreiser** [comment] 2016-12-14 19:12
Chris, 
It looks like the GO definition excludes the pollinator aspect of pollination and restricts to the activities that occur exclusively in plants including Gymnosperms and Angiosperms.

"The cascade of biological processes occurring in plants beginning when the pollen lands on the stigma and continuing up to, but not including, fertilization, as defined by sperm-central cell fusion."

Pollination,by most folks definitions, includes the act of transferring pollen to the female reproductive structure (by wind, biological transfer or other method) but I think here in GO it is more restrictive as a means to capture the events that lead up towards fertilization once the pollen lands on the lady parts.

The way this definition is written it would limit to flowering plants (that have stigma). So maybe Angiosperms.

**Comment by cmungall** [comment] 2017-01-06 21:40
@lreiser - good point.

it's classified under these:

```
is_a: GO:0044703 ! multi-organism reproductive process
is_a: GO:0044706 ! multi-multicellular organism process
```

I think "pollination" as defined in GO is actually single-organism, based on this. This will make the angiosperm valid. We can still make it part-of a multi-organism process.

You are right about normal usage as well:

https://en.wikipedia.org/wiki/Pollination
"Pollination is the process by which pollen is transferred to the female reproductive organs of a plant, thereby enabling fertilization to take place"

GO is right to focus on the part occurring in the plant though. I wonder if the GO term should have a more restrictive label.

**Comment by mcourtot** [comment] 2017-02-15 13:28
@tberardini: is it correct to say pollen wall part_of some pollen sac ( http://purl.obolibrary.org/obo/PO_0025277)? Or can you suggest the most appropriate PO term?

**Comment by mcourtot** [comment] 2017-02-15 13:39
Requested papilla cell (PO:0025166).

Re pollination: should the label be updated to "plant pollination"? Other suggestion? I can make it into a single organism reproductive process (GO:0044702) and add the following TX:
relationship: only_in_taxon NCBITaxon:33090 {id="GOTAX:0000422"} ! Viridiplantae (green plants)
relationship: only_in_taxon NCBITaxon:3398 {id="GOTAX:0000418"} ! Magnoliophyta (flowering plants)

**Comment by cooperl09** [comment] 2017-02-16 23:54
@mcourtot 
The pollen wall (GO:0043667) should have a part_of relationship to pollen (PO:0025281), not to pollen sac (PO:0025277).

**Comment by tberardini** [comment] 2017-02-17 00:01
@cooperl09 : Thanks for answering for me!  I can check that off my list now. :)

**Comment by cooperl09** [comment] 2017-02-17 00:02
@mcourtot 
Re: def'n of pollination needs to be expanded to include gymnosperms, or should create another class to encompass that process.  Suggest going with the more generic definition from above- 

The idea to rename "plant pollination" although it is somewhat redundant.

**Comment by cooperl09** [comment] 2017-02-17 00:05
Was there a question or request about papilla cell (PO:0025166)?

**Comment by lreiser** [comment] 2017-02-17 00:16
@mcourtot 
this definition could be made inclusive by eliminating the flowering plant specific term stigma. Also I would think we would want to define fertilization as sperm- egg cell fusion, no?

"The cascade of biological processes occurring in plants beginning when the pollen lands on the stigma and continuing up to, but not including, fertilization, as defined by sperm-central cell fusion."

The cascade of biological processes occurring in plants beginning when the pollen makes contact with the female reproductive structure and continues up, to but not including, fertilization, as defined by sperm-egg fusion.

The need to have gymosperm/angio differentiation would depend on children right- because there are no pollen-pistil interactions there - might be worth a new instance with different children for gymnosperms

**Comment by mcourtot** [comment] 2017-02-17 09:40
(no question about papilla cell, just made a note that it was requested to be imported into GO. I also now requested to import pollen (PO:0025281) - this should take 1-2 days to show up in the GO file after which I can make the changes)

TODO:

- [ ] Update definition of pollination to "The cascade of biological processes occurring in plants beginning when the pollen lands **on the female reproductive organs** of a plant and continuing up to, but not including, fertilization, as defined by **sperm-egg cell fusion**.", to cover cases of gymnosperms that don't have stigma (emphasis mine to highlight modifications)
- [ ] Add taxon constraint relationship: only_in_taxon NCBITaxon:33090 {id="GOTAX:0000422"} ! Viridiplantae 
- [ ] Update logical definition to is_a single organism reproductive process (GO:0044702), part-of multi-multicellular organism process (GO:0044706)
- [ ] On the fence (please comment): update label of "pollination" to "Plant pollination" to make it explicit this term does NOT encompass examples brought forward by @cmungall above: "I read last week that some marine arthropods and worms pollinate seagrass. " I'm leaning towards updating the label as even though redundant it is perhaps clearer.

**Comment by tberardini** [comment] 2017-02-17 17:34
Experimental evidence of pollination in marine flowers by invertebrate fauna
http://www.nature.com/articles/ncomms12980

freaky!

The organism being pollinated is still a plant though (marine angiosperm _Thalassia testudinum_).  I still think it's redundant (and a little odd) to call it 'plant pollination' given the very clear definition.

**Comment by mcourtot** [comment] 2017-02-18 08:56
Happy to defer to the expert :) thanks for the feedback @tberardini!

**Comment by mcourtot** [comment] 2017-02-20 09:04
All done (but as discussed I did *not* update the label of the pollination class). Committed revision 38920.

**Closed by mcourtot** 2017-02-20 09:04 UTC
Labels: auto-migrated, low priority, Taxon restriction, time medium (>2 <24h)
