### ISSUE TITLE
canonical glycolysis (GO:0061621) is part of "phosphorylation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22596] opened 2021-12-18 19:23 UTC
canonical glycolysis (GO:0061621)
has ancestry to "phosphorylation" which seems strange?

phosphorylation events  are a part of glycolysis?

**Comment by deustp01** [comment] 2021-12-19 23:31
True, but only because canonical glycolysis is_a  GO:0006757 "ATP generation from ADP" and any process tagged with GO:0006757 is_a (via several intermediate steps)  GO:0016310 "phosphorylation" process, so this looks like a problem with descendents of phosphoryation, much broader than glycolysis. At the same time, making ATP from ADP does indeed involve phosphorylation so the assertion is factually correct.

This probably takes us back to the unfinished discussion of a couple of years ago about "currency chemicals" (Larry Hunter's term) also know as housekeeping molecules, and how to handle them in a way that recognizes their essential roles in processes without creating odd groupings like this one under phosphorylation.

**Comment by ValWood** [comment] 2021-12-20 08:52
I guess this problem will also go away once we no longer represent modifications in the process ontology.

**Comment by pgaudet** [comment] 2021-12-20 08:53
GO:0006757 "ATP generation from ADP"  has a single child,  GO:0006096 glycolytic process. Maybe it can be obsoleted and the grand-parent ' GO:0006091 generation of precursor metabolites and energy' is sufficient to describe the cellular role of glycolysis?

**Comment by pgaudet** [comment] 2021-12-20 08:58
Anyway GO:0006757 "ATP generation from ADP"  is confusing, it is_a     GO:0006091  generation of precursor metabolites and energy but its 2 direct annotations are to kinases,  Human Adenylate kinase 9 (Q5TCS8) and E. coli ppk (P0A7B1), which, as far as I can tell, are not involved in generating precursor metabolites and energy.

**Comment by deustp01** [comment] 2021-12-20 13:40
> GO:0006091 generation of precursor metabolites and energy' is sufficient to describe the cellular role of glycolysis?

@ukemi @hdrabkin That sounds like a really good parent for canonical glycolysis - are there other downstream consequences of the reorganization we should worry about, that I'm missing because I don't know the details of the process ontology?

**Comment by ukemi** [comment] 2021-12-20 13:47
It makes sense to me that 'generation of precursor metabolites and energy' should be a parent of glycolysis.

**Comment by pgaudet** [comment] 2023-05-17 07:35
Duplicate of  #22596

**Closed by pgaudet** 2023-05-17 07:35 UTC
Labels: metabolism, obsoletion, ready
