### ISSUE TITLE
annotations to 	defense response to fungus, incompatible interaction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18739] opened 2020-02-03 14:34 UTC
There are 16 annotations from

Proteomics of the response of Arabidopsis thaliana to infection with Alternaria brassicicola.

Abstract
We have studied the proteome of the model plant Arabidopsis thaliana infected with a necrotrophic fungal pathogen, Alternaria brassicicola. The Arabidopsis-A. brassicicola host-pathogen pair is being developed as a model genetic system for incompatible plant-fungal interactions, in which the spread of disease is limited by plant defense responses. After confirming that a defense response was induced at the transcriptional level, we identified proteins whose abundance on 2-DE gels increased or decreased in infected leaves. At least 11 protein spots showed reproducible differences in abundance, increasing or decreasing during the progress of the infection. The pathogenesis-related protein PR4, a glycosyl hydrolase, and the antifungal protein osmotin are strongly up-regulated. Two members of the Arabidopsis glutathione S-transferase (GST) family increased in abundance in infected leaves. The spots in which these GST proteins were identified contain additional members of the GST family. Representation of GST family members in several protein spots migrating at similar molecular weight suggests post-translational modifications. The signature of GST regulation may be specific for the type of plant-pathogen interaction. The proteomic view of the defense response to A. brassicicola can be compared with other types of plant-pathogen interactions, and to leaf senescence, identifying unique regulatory patterns. 
PubMed
PMID:19857612

a) this is really just "defense response to fungus" see
https://github.com/geneontology/go-ontology/issues/18738
The "incompatibe interaction" part just means the pathogen is able to detect this specific fungus

b)
using IDA seems a stretch it seems that HDA would be more appropriate?

**Comment by ValWood** [comment] 2020-09-23 08:17
ACTION:
merge 
GO:0009817   defense response to fungus, incompatible interaction
into 
defense response to fungus

(the concept of a compatible (disease)  or incompatible  (no disease) interaction is out of scope for GO)

**Comment by ValWood** [comment] 2020-09-23 08:26
and merge

GO:0009814    defense response, incompatible interaction | 4,138 annotations
-- | --
GO:0009817    defense response to fungus, incompatible interaction | 529 annotations
GO:0009816    defense response to bacterium, incompatible interaction | 652 annotations
GO:0009818    defense response to protozoan, incompatible interaction |  
GO:2000072    regulation of defense response to fungus, incompatible interaction | 138 annotations
GO:1902477    regulation of defense response to bacterium, incompatible interaction | 74 annotations
GO:1902479    positive regulation of defense response to bacterium, incompatible interaction | 25 annotations
GO:1902478    negative regulation of defense response to bacterium, incompatible interaction


into their parents.NO terms in GO should mention "compatible" or "incompatible" interaction.

This ticket also highlights the issue with "response to" terms well. Most of these  annotations would more appropriately be  to  specific  terms in the pathogen-host interaction branch, not just response to x

**Comment by pgaudet** [comment] 2020-11-20 08:58
@tberardini Can you please look at the original comment to make sure this is OK with you - and may any required change (IDA-> HDA?)
https://github.com/geneontology/go-ontology/issues/18739#issue-559123379

Thanks, Pascale

**Comment by pgaudet** [comment] 2020-11-20 09:00
Never mind, this is a duplicate of #18738 where TAIR replied to our questions.

**Closed by pgaudet** 2020-11-20 09:00 UTC
Labels: multi-species process, quick fix
