### ISSUE TITLE
Change logical definitons and asserted subclasses for 'GO:0043299 leukocyte degranulation' children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26204] opened 2023-10-02 17:04 UTC
The asserted parent of children of GO:0043299 leukocyte degranulation' contained is_a cell activation. This causes incorrect assertions, to is_a [localization of cell](http://purl.obolibrary.org/obo/GO_0051674), see 
https://github.com/geneontology/go-ontology/pull/26177

After discussion, we have decided to change that to 'part of' cell activation, rather than is_a activation. Hopefully that will resolve the issue. 

@addiehl hopefully this is correct?

**Comment by pgaudet** [comment] 2023-10-02 17:13
@cmungall 

The logical definitions for 'x degranulation'

  'regulated exocytosis'
   and ('occurs in' some x cell)

also, the parent 'leukocyte degranulation' is asserted. 

Wouldn't it be more consistent with other DP if we had: 
  leukocyte degranulation 
   and ('occurs in' some x cell)

since also   leukocyte degranulation  is_a regulated exocytosis ? 

Thanks, Pascale

**Comment by cmungall** [comment] 2023-10-02 17:24
I think that's fine

**Comment by addiehl** [comment] 2023-10-02 20:30
having 'leukocyte degranulation' as a subclass of 'cell activation' was intended as way capture assay results where degranulation was used by the experimenters as a proxy measure for 'cell activation', particularly when investigating gene products involved in signaling pathways.   However, this has always felt a bit hacky, even though I promoted this.  The hoped for inference is that when there has been an instance of 'leukocyte degranulation' it can be inferred that there has been an instance of 'cell activation'.

'leukocyte degranulation' part of 'cell activation' sort of works, but really something like 'leukocyte degranulation' _'causally downstream of'_ 'cell activation' is probably more biological accurate.

**Comment by deustp01** [comment] 2023-10-02 20:37
@pgaudet Does the current policy on proxy assays (that they are out of scope for GO?) give you a way out of this problem?

**Comment by addiehl** [comment] 2023-10-02 20:55
A huge amount of signaling work in immunology and other fields is based on 'read-out' assays where a downstream process is used to access whether a signaling event has occurred.  I can't imagine we would want to throw out this mass data upon which much of our understanding of cell signaling events is based on.

**Comment by deustp01** [comment] 2023-10-02 21:45
@pgaudet Am I getting this right? We want the GO term to link the biological signal to the biological downstream target, and not to link the biological signal to a proxy target? So then all this work remains fully annotatable but the proxy assay should be represented by something like an evidence code and not as the true target of the signal?

**Comment by cmungall** [comment] 2023-10-02 22:36
> 'leukocyte degranulation' part of 'cell activation' sort of works, but really something like 'leukocyte degranulation' 'causally downstream of' 'cell activation' is probably more biological accurate.

Either of these resolves the isa-overloading issue. Obviously the big difference between these too is whether you expect the genes annotated to the degranulation term to show up in a gene set for the activation term. If we had clearly defined starts and ends we could answer this more definitively. But either works for resolving the immediate problem.

**Comment by addiehl** [comment] 2023-10-02 23:02
Per the proxy/read-out assay issue, there is an annotation at MGI, most probably done by me, based on [PMID:9000133](https://pubmed.ncbi.nlm.nih.gov/9000133/) that annotates [Syk](https://amigo.geneontology.org/amigo/gene_product/MGI:MGI:99515) to ['positive regulation of mast cell degranulation'](https://amigo.geneontology.org/amigo/term/GO:0043306). While I can't get access to the paper online, even with my university's subscription, even reading the abstract you might be able to imagine the kind of data used to make this annotation:
Activation of the high affinity IgE receptor (Fc epsilon RI) of mast cells, a member of the antigen receptor family, leads to the release of allergic mediators, a critical event in the onset of immediate hypersensitivity. **Stimulation of Fc epsilon RI results in the rapid association and activation of the Syk tyrosine kinase. Using Syk-deficient mast cells we show that they fail to degranulate, synthesize leukotrienes and secrete cytokines when stimulated through Fc epsilon RI, conclusively demonstrating an essential role for Syk in Fc epsilon RI signalling.** Furthermore, our data strongly supports a model of Fc epsilon RI engagement leading to the sequential activation of the tyrosine kinases Lyn and then Syk. A similar mechanism is likely to apply to signal transduction through all members of the antigen receptor family.

'positive regulation of mast cell degranulation' positively regulates 'mast cell degranulation'
'mast cell degranulation' is_a 'mast cell activation involved in immune response'
'mast cell activation involved in immune response' is_a 'mast cell activation'

Therefore Syk positive regulates 'mast cell activation', which is a statement that I think the original authors would agree with.

**Closed** 2023-10-03 07:04 UTC
Labels: logical definitions, relations

**Comment by pgaudet** [comment] 2023-10-03 13:04
Hi @deustp01 @addiehl 
Thanks for the feedback. @deustp01 you are right that GO now strives to remove readouts to clarify processes. 

Maybe with all the other ontologies that now exist, it is possible to get this assay information from another source, instead of overloading GO? 

I am closing this ticket, since this was not the aim here, we can rediscuss in another context.
