### ISSUE TITLE
Builds failing due to unknown issue, possibly SSL related (re: handshake alert:  unrecognized_name)

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12998] opened 2017-02-06 10:33 UTC
See http://build.berkeleybop.org/job/release-go/227/console, some issue with ro/annotations.owl

2017-02-06 02:21:24,135 ERROR (CommandRunner:4198) could not parse:http://purl.obolibrary.org/obo/ro.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/ro/annotations.owl> Cause: handshake alert:  unrecognized_name

Looking at http://purl.obolibrary.org/obo/ro.owl, it imports http://purl.obolibrary.org/obo/ro/annotations.owl which does resolve to
https://raw.githubusercontent.com/oborel/obo-relations/master/annotations.owl

Maybe a problem with the namespace declarations?
```
xmlns="&obo;bfo.owl#"
xml:base="&obo;bfo.owl"
```

though the ontology URI seems correct.

**Comment by cmungall** [comment] 2017-02-06 18:48
@kltm has noticed similar issues totally different ontologies, something 
odd is up with owlapi and ssl?

**Comment by kltm** [comment] 2017-02-06 18:48
There seems to be an intermittent failure involving Java and ssl, that we have not been able to isolate; we don't even know which end the problem is occurring at. It may be due to some recent upgrades in ssl libraries on various systems that is causing the issue.

Re-running the job, it seems to have advanced more than before. Closing.

For pipeline issues, it may be better to open tickets on the go-site tracker.

**Comment by kltm** [comment] 2017-02-07 00:04
Lovely, it failed for a different file this time:
http://purl.obolibrary.org/obo/ro.owl

**Comment by kltm** [comment] 2017-02-07 00:20
For reference: https://github.com/owlcollab/owltools/issues/171

**Comment by kltm** [comment] 2017-02-07 00:48
Now it works. I give up. 🙀

**Comment by cmungall** [comment] 2017-02-07 00:48
I think the obo format issue is different.

For the issue holding up the GO release, the exact same command works for me, i.e.

```
owltools --use-catalog http://purl.obolibrary.org/obo/ro.owl --merge-imports-closure ../editors/gene_ontology_write.obo --merge-imports-closure --set-ontology-id http://purl.obolibrary.org/obo/ro.owl -o allrelations.owl
```

so there is something different about grinder, either java version/ssl issue, or something network oriented

**Comment by kltm** [comment] 2017-02-07 00:50
grinder should not have changed in the last few hours. Same machine, same build script.

**Comment by cmungall** [comment] 2017-02-07 00:52
The build succeeded, but it did not attempt to run the same command.

Remember there is a crazy Makefile there that has accrued a lot of complexity we will simplify when moving to github

**Comment by kltm** [comment] 2017-02-07 00:55
Wat? 
Differences I've found so far are:
```
U         editors/go_inferences.obo
U         editors/gene_ontology_write.obo
U         editors/validated.obo
U         editors/go_inferences_difflog.txt
```
Was there sufficient update there? At least that might narrow it down...

**Comment by mcourtot** [comment] 2017-02-07 08:51
If it helps narrow it down, the TG job failed with the same error
```
2017-02-06 17:38:28,440 INFO  (ParserWrapper:82) Finished loading ontology: null from: http://purl.obolibrary.org/obo/po.owl
Exception in thread "main" org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/po/imports/ncbitaxon_import.owl> Cause: handshake alert:  unrecognized_name
```

for build [828](http://build.berkeleybop.org/job/go-termgenie-check/828/changes), but then recovered in build [829](http://build.berkeleybop.org/job/go-termgenie-check/829/changes)

**Comment by mcourtot** [comment] 2017-02-07 10:56
It seems disabling SNI 

`-Djsse.enableSNIExtension=false`

could help: http://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0

**Comment by kltm** [comment] 2017-02-07 19:39
Thank you for the help--sorry we did not loop you in on earlier conversations where we covered options like this.
Digging into the different layers where these actions can be occurring and trying the various options, assuming it's even a client java issue, was weighed to be expensive in the face that the issue is sporadically occurring. It doesn't seem to be a client-only issue given other SSL-realated disruptions that we've had, although that may help in this case.
If we get our hands on an easily repeatable and controllable occurrence of this type of issue we'd probably dig into more.

**Closed by kltm** 2017-02-07 19:39 UTC
Labels: Infrastructure

**Comment by cmungall** [comment] 2017-02-07 21:58
@kltm 
> Wat?

Don't try and analyze it, this pipeline will be dead before long and replaced with a vastly simplified one.

For whatever reason, the same step was not executed in that run of the job

I made a temporary job to test this more deterministically, so far I cannot repeat it, consistent with what you're saying https://build.berkeleybop.org/job/owltools-ssl-test/
