### ISSUE TITLE
please clarify what should be annotated to "protein polymerization" "microtubule polymerization" etc

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11748] opened 2015-03-18 10:51 UTC
The def of 'microtubule polymerization" (for example)
is

"The addition of tubulin heterodimers to one or both ends of a microtubule".

Should tubulin be annotated to this term (we are picking up mappings)
I would not think so because tubulin isn't involved in the assembly per se (liek saying a brick is involved in bricklaying?)
Can anyone clarify before I address the mapping.

I sure there has been previous discussion on this, but I can't locate it.

Thanks,

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11580](https://sourceforge.net/p/geneontology/ontology-requests/11580)

**Comment by paolaroncaglia** [comment] 2017-02-16 13:40
Hi @ValWood ,
I will close this ticket because it is sort of a duplicate of 11269 linked above, and more discussion is recorded there. Cheers.

**Closed by paolaroncaglia** 2017-02-16 13:40 UTC
Labels: auto-migrated, time unknown (external dependencies etc), wrapping up
