### ISSUE TITLE
NTR: 3′to 5′ RNA polymerase activity

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#12812] opened 2016-11-21 21:39 UTC
This is a NTR separated from this (now closed) larger issue (No 3 therein):
https://github.com/geneontology/go-ontology/issues/12756

Here is the parentage to be discussed and / or some issues with existing term(s):
References: 
PMID:22456265 (a 2012 review)
PMIS: 27484477 (recent paper describing distinct targets of 4 Dicty TLPs, all 3'-5' RNA polymerases)

GO_NEW: 3′-5′ RNA polymerase activity
is_a GO:0003968 RNA-directed RNA polymerase activity
This term itself would be true, as the substrate RNAs template this polymerase activity. See EC restriction below.

Parent of above:
is_a GO:0034062 RNA polymerase activity

New term Def: Catalyzes the 3'-to-5' addition of nucleotides to the 5' end of diverse RNA substrates (as examples, the Dicty TLPs and PMID:7484477 can be cited)

Both parent and grant parent term have the problem that they link to EC records (EC/2.7.7.48, EC/2.7.7.6 respectively) and both have this in their description:
"... extension of the 3'-end of an RNA strand by one nucleotide at a time."

Thus, the EC description of both existing parent terms are too restrictive. Thus, maybe we need the corresponding 5' to 3' term as well to clearly distinguish and possibly work with EC to clean it up there. 

Thanks!
Petra

**Comment by paolaroncaglia** [comment] 2016-11-23 16:40
Thanks @pfey03 .
So, checking existing terms and their EC refs first, from the bottom up:

- [ ] GO:0003899 DNA-directed RNA polymerase activity
The definition *does* specify extension of the 3'- end vs. 5’, same as the EC ref. Same for its children terms. So I will rename this term ‘DNA-directed 5’-3’ RNA polymerase activity’, and will keep the existing name as a broad synonym.

- [ ] GO:0003968 RNA-directed RNA polymerase activity
The definition does not specify extension of the 3'- end vs. 5’, but the EC ref does. 32 direct experimental annotations, too many to look at to figure out quickly how the term was used. The term also maps to MetaCyc (which specifies 3’, same as EC), to Reactome (hard to tell), and to 54 InterPro entries (too many to tell, though some specify 3’). Overall, I’d be tempted to rename and redefine GO:0003968 ‘RNA-directed RNA polymerase activity’ as ‘RNA-directed 5’-3’ RNA polymerase activity’, and leave the EC ref as is. If so, I’d need to rename its regulation children too.

- [ ] GO:0034062 RNA polymerase activity
The definition does not specify extension of the 3'- end vs. 5’, but the EC ref does. No mappings other than EC. Only 2 direct annotations, both TAS by Reactome 
Reaction:5696807 TRNT1 polymerizes CCA at the 3' end of pre-tRNA (Homo sapiens)
Reaction:6786881 TRNT1 polymerizes CCA at the 3' end of pre-tRNA (Homo sapiens)
So I’d be tempted to rename and redefine this, too, as ‘5’-3’ RNA polymerase activity’.

If we do all of the above, then we’d need 
- [ ] a new parent term to represent generic ‘RNA polymerase activity’ (no EC mapping; GOC:pf), 
- [ ] a new descendant term for ‘3′-5′ RNA polymerase activity’ (GOC:pf, PMID:22456265, PMID: 27484477),
- [ ] to open a ticket with Rhea to request a corresponding entry for ‘3′-5′ RNA polymerase activity’. If and when the Rhea term is created, we could add its ID as a dbxref to ‘3′-5′ RNA polymerase activity’.

Does this make sense?

**Comment by paolaroncaglia** [comment] 2016-11-23 16:40
@hdrabkin , @ukemi 
Could you please review and let me know if you have any concern with the plan.

**Comment by pfey03** [comment] 2016-11-23 16:54
Thanks Paola,

From my point of view, this plan sounds excellent. Regarding all the annotations to some terms that you'll rename, from my reading of the reviews and papers, I really do think the Jackman group is the first to report the reverse direction of any polymerase activity, thus their emphasis on  3′to 5′ RNA polymerase activity and it's different targets in Dicty.

Thanks again,
Petra

**Comment by krchristie** [comment] 2016-11-23 18:11
Makes sense to me too. I've never come across a 3'-5' RNA polymerase activity either, so renaming the existing terms to specify the 5'-3' direction as matches their EC defs seems appropriate.

-Karen

**Comment by hdrabkin** [comment] 2016-11-23 20:38
When I saw this yesterday I was skeptical. But, after reading the RNA paper,  I guess this is yet another example of a dogma that dies. I might also ask Tom RajBhandary at MIT what he thinks (next week).

**Comment by paolaroncaglia** [comment] 2016-11-24 09:15
Thanks @pfey03 ,@krchristie and @hdrabkin for your feedback.
How about we wait for @hdrabkin to briefly double-check with his colleague early next week before I implement those changes. I expect that @pfey03 won't be annotating over the Thanksgiving break anyway, and as we already have a strategy in place, it will be quick to implement once we're (more) confident that it's the best way to go. Thanks.

**Comment by hdrabkin** [comment] 2016-11-29 15:30
Still waiting; assume back from holiday. I think we should go ahead as you plan; I wanted to get his opinion what he thought of the papers. I'll try his phone again later in the day.

**Comment by paolaroncaglia** [comment] 2016-11-29 15:54
Thanks @hdrabkin .

**Comment by paolaroncaglia** [comment] 2016-12-02 10:20
@pfey03 , FYI
Completed first 3 action items as of https://github.com/geneontology/go-ontology/issues/12812#issuecomment-262566983. More soon.

**Comment by paolaroncaglia** [comment] 2016-12-02 10:56
@pfey03 , here are the new terms (ignore the + signs at start of lines, that's just the svn diff):

 [Term]
+id: GO:0097747
+name: RNA polymerase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: nucleoside triphosphate + RNA(n) = diphosphate + RNA(n+1); the synthesis of RNA from ribonucleotide triphosphates in the presence of a nucleic acid template." [GOC:pf]
+is_a: GO:0016779 ! nucleotidyltransferase activity
+created_by: paola
+creation_date: 2016-12-02T11:48:55Z
+
+[Term]
+id: GO:0097748
+name: 3'-5' RNA polymerase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: nucleoside triphosphate + RNA(n) = diphosphate + RNA(n+1); the synthesis of RNA from ribonucleotide triphosphates in the presence of a nucleic acid template, via extension of the 5'-end." [GOC:pf, PMID:22456265, PMID:27484477]
+is_a: GO:0097747 ! RNA polymerase activity
+created_by: paola
+creation_date: 2016-12-02T11:51:31Z

**Comment by paolaroncaglia** [comment] 2016-12-02 11:19
@pfey,
I opened a request with Rhea to create a new entry for 3′-5′ RNA polymerase, here's the link:
https://sourceforge.net/p/rhea-ebi/reaction-requests-updates/63/
(Note for self: yes their SF tracker seems quite quiet, but a year ago they confirmed it was still in use, and it is indeed linked from their Data Submission page at http://www.rhea-db.org/submit)

I will now set this ticket to pending while we wait for Rhea to respond.
- [ ] The only action item left to do for this ticket is: if and when a new Rhea entry is created for ‘3′-5′ RNA polymerase’, we could add its ID as a dbxref to ‘3′-5′ RNA polymerase activity’.

**Comment by pfey03** [comment] 2016-12-02 16:42
Fantastic @paolaroncaglia, thanks so much, really appreciated!

**Comment by pfey03** [comment] 2016-12-06 23:29
@paolaroncaglia, when will these terms be available/released? Still waiting for Harold's expert?

Thanks,
Petra

**Comment by paolaroncaglia** [comment] 2016-12-07 09:03
Hi @pfey03 ,

GO:0097747 RNA polymerase activity
and
GO:0097748 3'-5' RNA polymerase activity
are already in the ontology. They are also shown in AmiGO (I checked just now), but not yet in QuickGO, presumably because the GO build was broken for some time over the past few days. It was fixed less than 24 hours ago, and it then takes about a day for recent changes to percolate to QuickGO (and, I presume, P2GO). If you still can't use the terms by tomorrow, please contact Tony Sawford (I'll be on leave tomorrow and Friday). Thanks.

**Comment by pfey03** [comment] 2016-12-07 20:55
thanks @paolaroncaglia, will check end of week

**Comment by paolaroncaglia** [comment] 2016-12-12 16:07
@pfey03 
FYI, 
GO:0097747 RNA polymerase activity
and
GO:0097748 3'-5' RNA polymerase activity
are now visible in QuickGO too. 
So, wrapping up, everything you needed from this ticket has been done, and 

- [ ] the only action item left to do for this ticket is: if and when a new Rhea entry is created for ‘3′-5′ RNA polymerase’, we could add its ID as a dbxref to ‘3′-5′ RNA polymerase activity’. See request in Rhea tracker here: https://sourceforge.net/p/rhea-ebi/reaction-requests-updates/63/

**Comment by paolaroncaglia** [comment] 2017-02-16 11:36
Hi @ukemi,
I’ve completed my tasks for this ticket, and the only thing left to do (low priority) is to add a Rhea dbxref if/when a Rhea entry is created (details above). Therefore I will now unassign myself from this ticket. However, since unassigned tickets tend to fall through the cracks when they’re not recent, I will assign it to you (as main ontology editor at this stage), and you can then hand it over to others if and as/when appropriate. Thanks.

**Comment by pgaudet** [comment] 2017-11-21 16:00
Doesn't look like Rhea will add this term. My understanding is that this is outside the scope pf Rhea.

Pascale

**Comment by kaxelsen** [comment] 2018-08-29 08:15
The reaction has now been created in Rhea. It was not out of scope, I was just rather slow moving. 
The new Rhea reaction is RHEA:57528. If it had been out of scope we would have informed you of this fact.

Read more details in https://sourceforge.net/p/rhea-ebi/reaction-requests-updates/63/

Cheers,
Kristian

**Closed** 2018-08-31 15:01 UTC
Labels: New term request, Other term-related request, dictyBase, enzymes, external dependencies etc, low priority, ready
