### ISSUE TITLE
GO:0004843    thiol-dependent ubiquitin-specific protease activity/ rename?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17398] opened 2019-05-26 15:51 UTC
GO:0004843    thiol-dependent ubiquitin-specific protease activity

Can this be named

"ubiquitin-specific protease activity"

the thiol-dependent seems to be mechanistic detail that doesn't belong in the term name?
can be a synonym and it's in the def (there is no thiol-independent term...)

**Comment by pgaudet** [comment] 2019-05-27 07:24
In this case, these terms should merge: 

'ubiquitinyl hydrolase activity'
'thiol-dependent ubiquitinyl hydrolase activity'
'thiol-dependent ubiquitin-specific protease activity'

Or are there different mechanisms ? As far as I know there is always a thiol bond between the ubiquitin and the protein conjugated to it. 

@kaxelsen 

Thanks, Pascale

**Comment by ValWood** [comment] 2019-05-27 07:40
'ubiquitinyl hydrolase activity' might be a grouping term for the ubiquitin and ubiquitin-like terms. I don't remember exactly why it is organized this way, but @ukemi did a thorough job of the ligases/transferases uqite recently. I don't know if hydrolase branch was done at the this time.


We should probably also kill the MF involved in BP terms

GO:1904455    ubiquitin-specific protease activity involved in negative regulation of ERAD pathway | is_a
-- | --
GO:1904454    ubiquitin-specific protease activity involved in positive regulation of ERAD pathway | is_a

I thought all of these were removed already?

**Comment by pgaudet** [comment] 2019-05-27 07:56
> I don't know if hydrolase branch was done at the this time.
 
I don't know either. Last changes to these terms were in 2016; maybe the timing fits ? 

It's a little odd that only GO:0036459 out of the 3 terms has an EC number.

**Comment by ukemi** [comment] 2019-05-29 14:44
We didn't work on the proteases, but based on the definitions and comments on these terms, I would be cautious about modifying the structure of the ontology and merges. 'ubiquitinyl hydrolase activity' has a definition of 'Catalysis of the hydrolysis of ubiquitin from proteins and other molecules.' If I recall correctly, ubiquitin can be added to non-protein substrates. There is also a comment on the term 'There are two main classes of deubiquitinating enzymes: cysteine proteases (i.e., thiol dependent) and metalloproteases.' which suggests that a merge should be done with caution.

**Comment by ukemi** [comment] 2019-05-29 14:57
PMID:23845989

**Comment by ValWood** [comment] 2019-05-29 18:00
Which term is for the  metalloprotease-type?
(since GO:0004843 thiol-dependent ubiquitin-specific protease activity has no sibling?)

Do we need to distinguish this mechanistic detail?

**Comment by kaxelsen** [comment] 2019-06-03 08:44
> Or are there different mechanisms ? As far as I know there is always a thiol bond between the ubiquitin and the protein conjugated to it.

There is always a cysteine (i.e. a thiol group) involved for the E1, E2 and E3 proteins binding  ubiquitin, but the for the target proteins, the ubiquitin can be bound to lysine (i.e. an amino group) or threonine (i.e. a hydroxy group; EC number in progress). so if hydrolases exist for these two latter cases
 
'ubiquitinyl hydrolase activity'
'thiol-dependent ubiquitinyl hydrolase activity'
'thiol-dependent ubiquitin-specific protease activity'

Are not synonyms

**Comment by sjm41** [comment] 2020-05-19 09:26
Hi, I just stumbled into these problematic terms/annotations and found this existing ticket (that looks like it got stuck about a year ago).
Here's my take/proposal, starting from the "ubiquitinyl hydrolase activity" term:

id: GO:0101005
name: ubiquitinyl hydrolase activity
def: "Catalysis of the hydrolysis of ubiquitin from proteins and other molecules." [GOC:mec]
comment: There are two main classes of deubiquitinating enzymes: cysteine proteases (i.e., thiol dependent) and metalloproteases.
synonym: "deubiquitinase activity" EXACT []
synonym: "ubiquitin-specific protease activity involved in negative regulation of retrograde protein transport, ER to cytosol" NARROW []
is_a: GO:0016787 ! hydrolase activity
is_a: GO:0140096 ! catalytic activity, acting on a protein

Which has these direct children:
- thiol-dependent ubiquitinyl hydrolase activity (GO:0036459)
- Lys48-specific deubiquitinase activity (GO:1990380)
- Lys63-specific deubiquitinase activity (GO:0061578)
- ubiquitinyl hydrolase activity, acting on linear ubiquitin (GO:0061815)


Issues here:
1. Def of GO:0101005 suggests this activity acts on proteins "and other molecules". Are there any known examples of non-protein substrates? (PMID:19489724 says it's just proteins.) Moreover, the current term is an is_a child of "catalytic activity, acting on a protein", which is inconsistent with def.  So, remove "and other molecules" from def?

2. Assuming that's all correct, then GO:0101005 should be direct child of 'peptidase activity' (GO:0008233), or probably 'peptidase activity, acting on L-amino acid peptides (GO:0070011)'. This covers both current parents, so they can be removed.  In fact, it should probably be a child of the more specific 'omega peptidase activity' (GO:0008242), following the revisions to that term (see #19473).

3. The comment on GO:0101005 says "There are two main classes of deubiquitinating enzymes: cysteine proteases (i.e., thiol dependent) and metalloproteases.", which is true (see PMID:19489724 for a very relevant review).  The cysteine class are covered by the "thiol-dependent ubiquitinyl hydrolase activity (GO:0036459)" child, but we don't seem to have a term for "metal-dependent ubiquitinyl hydrolase activity". This child should be created and added, also making it a child of metallopeptidase activity (GO:0008237). There are (at least) 6 classes of ubiquitinyl hydrolases (deubiquitinases): 5 are cysteine proteases (UCH, USP, OTU, MJD, MINDY) while the JAMM class are metalloproteases. (see PMID:19489724 & PMID:27392144).  (Any JAMM deubiquitinases currently annotated with the "thiol-dependent ubiquitinyl hydrolase activity (GO:0036459)", eg. human STAMBP (O95630), are wrong and will need retrofitting.)

4. I'm not sure what to do with the other 3 child terms under "ubiquitinyl hydrolase activity".  Ideally, they would go under either the existing 'thiol dependent (cysteine) deubiquitinase' term (GO:0036459) or the new 'metal-dependent deubiquitinase' term, depending on mechasim.  But if that representation is not accurate/possible, then they should stay in their current position and perhaps each have new cysteine- and metal-dependent children of their own?

![Screenshot 2020-05-19 at 10 24 07](https://user-images.githubusercontent.com/16306861/82309368-f31dba80-99ba-11ea-9cbd-6eb75a22b53b.png)

**Comment by ValWood** [comment] 2020-05-19 10:27
Thanks sjm41 !

**Comment by sjm41** [comment] 2020-05-31 14:03
Hi @hdrabkin,

Since you've just researched and closed the related tickets #19473 & #19502, do you mind taking a look at this? Does my proposal here make sense to you?
Thanks, Steven.

**Comment by pgaudet** [comment] 2020-07-01 12:52
Created new parent term to match the ubiquitin ligase counterpart, mentioning ubiquitin-like proteins: 

+[Term]
+id: GO:0140491
+name: ubiquitin-like hydrolase activity
+namespace: molecular_function
+def: "An activity that cleaves ubiquitin or ubiquitin-like proteins (ULP) from target proteins." [PMID:19489724]
+synonym: "ubiquitinyl-like hydrolase activity" EXACT []
+is_a: GO:0016787 ! hydrolase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/17398 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-01T12:37:19Z
+

**Comment by pgaudet** [comment] 2020-07-01 13:32
Created the metal-dependent deubiquitinase activity 

+[Term]
+id: GO:0140492
+name: metal-dependent deubiquitinase activity
+namespace: molecular_function
+def: "Catalysis of the metal-dependent hydrolysis of an ester, thioester, amide, peptide or isopeptide bond formed by the C-terminal glycine of ubiquitin." [PMID:19489724]
+synonym: "metal-dependent ubiquitin-like hydrolase activity" EXACT []
+synonym: "metal-dependent ubiquitinyl-like hydrolase activity" EXACT []
+is_a: GO:0008237 ! metallopeptidase activity
+is_a: GO:0101005 ! deubiquitinase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/17398 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-01T13:14:00Z

**Comment by pgaudet** [comment] 2020-07-01 13:40
For point 1: 
> Def of GO:0101005 suggests this activity acts on proteins "and other molecules".

Removed 'other molecules'. We are not aware of 'other molecules' being ubiquinitated, neither is @kaxelsen 


Point 2: 
> GO:0101005 should be direct child of 'peptidase activity' (GO:0008233)

Moved as suggested.

**Comment by pgaudet** [comment] 2020-07-01 13:48
To do: 

- [ ] Check which terms could go under 'omega peptidase activity' (GO:0008242)
- [ ] Decide whether to create the two classes (metallo /thiol) peptidase for each modifier. We need to look at annotations and see which mechanism is relevant for individual modifications
-- We know that ubiquitin and NEDD8 are hydrolyzed by different enzymes using either of those two mechanisms; not sure for others
- [ ]  Check the mechanisms of  GO:0061578 Lys63-specific deubiquitinase activity and GO:1990380
Lys48-specific deubiquitinase activity, and see if the terms need to be moved
- [ ] Check whether we need a sibling to 'ubiquitinyl hydrolase activity, acting on linear ubiquitin', for branched ubiquitin.

**Comment by sjm41** [comment] 2021-01-29 12:16
@pgaudet Looking at the latest GO, I'm not seeing any of the things I thought we'd actioned back in July, specifically:
- add new "GO:0140491 ubiquitin-like hydrolase activity" term
- add new "GO:0140492 metal-dependent deubiquitinase activity" term
- change def of GO:0101005 to remove 'other molecules'
- make GO:0101005 a direct child of 'peptidase activity' (GO:0008233)
- and I think we also changed term name of "ubiquitinyl hydrolase activity" (GO:0101005) to "deubiquitinase activity"
Did you decide not to action these, or has something gone awry?


Also, looks like we've lost the "ubiquitin-like protein-specific protease activity" parent on  "thiol-dependent ubiquitin-specific protease activity (GO:0004843)" - I think that needs to be re-instated as an additional parent

**Comment by pgaudet** [comment] 2021-02-02 12:54
Hi @sjm41 

Thanks for the reminder ! Apologies for the delay. 

I committed what you have in the previous comment; I do have a few more questions: 

1. Should we change the labels of those terms as well: 
- 'thiol-dependent ubiquitin-specific protease activity' -> thiol-dependent deubiquitinase
-'ubiquitinyl hydrolase activity, acting on linear ubiquitin' -> deubiquitinase, acting on linear ubiquitin

2. Should 'deubiquitinase activity' be a child of 'ubiquitin-like protein-specific protease activity' ? This would be like the 'ligase' branch: 
- 'ubiquitin-like protein ligase activity'
- - 'Atg12 ligase activity'
- - 'FAT10 ligase activity'
- -  etc 
- - 'ubiquitin protein ligase activity'


Thanks, Pascale

**Comment by pgaudet** [comment] 2021-02-02 13:07
I have a third question: 

Do we need metal-dependent and thiol dependent Lys48 and Lys63-specific deubiquitinase activity ? I notice at least pomBase does dual annotations. 

@ValWood 

Thanks, Pascale

**Comment by sjm41** [comment] 2021-02-02 13:21
Thanks @pgaudet 
Q1. Yes, I'd recommend changing all applicable term names in this branch to use 'deubiquitinase'.
Q2. Yes, that makes sense.
Q3. Yes, I think so.  Most fly proteins annotated with those terms are cysteine (thiol)-dependent, but at least two fly proteins annotated with 'Lys63-specific deubiquitinase activity' are metal-dependent (FBgn0039773, FBgn0028694)

**Comment by pgaudet** [comment] 2021-02-02 15:13
@sjm41 

I implemented 1 & 2, will wait for Val for 3. 

I also noticed that the new term ' GO:0140491 ubiquitin-like hydrolase activity' (An activity that cleaves ubiquitin or ubiquitin-like proteins (ULP) from target proteins.) seems redundant with 'GO:0019783 ubiquitin-like protein-specific protease activity' (def: Catalysis of the hydrolysis of peptide or isopeptide bonds within small proteins such as ubiquitin or ubiquitin-like proteins (e.g. APG8, ISG15, NEDD8, SUMO), or between the small protein and a larger protein to which it has been conjugated.)

or is is a different type of cleavage ?

**Comment by sjm41** [comment] 2021-02-02 15:54
I'm going to have to back up a bit....

Looking at QuickGO right now, 'GO:0019783 ubiquitin-like protein-specific protease activity' is a child of 'GO:0008234
cysteine-type peptidase activity'. Is that still the case after your recent edits? If so, they are not redundant - the new term 'GO:0140491 ubiquitin-like hydrolase activity' is agnostic about catalytic type (so needs to be a parent term) whereas GO:0019783 ubiquitin-like protein-specific protease activity' is only for the cysteine-type.  (Maybe put 'cysteine-type' in the term name of GO:0019783 to make this clearer?)

Also, my earlier agreement that 'deubiquitinase activity' should be a child of 'ubiquitin-like protein-specific protease activity may also be wrong - we need 'deubiquitinase activity' as a parent, with the 'cysteine-type deubiquitinases' and 'metal-depedendent deubiquitinases' as children.

Maybe attach a screenshot of how things are currently looking in your ontology editor?

**Comment by pgaudet** [comment] 2021-02-02 16:00
<img width="466" alt="image" src="https://user-images.githubusercontent.com/4782928/106626628-2f5c6f80-6578-11eb-9ea2-9b7fd289b6a9.png">

**Comment by ValWood** [comment] 2021-02-02 17:43
All PomBAse examples of
Lys48-specific deubiquitinase activity (GO:1990380)
Lys63-specific deubiquitinase activity (GO:0061578)
are thiol-dependent.

**Comment by pgaudet** [comment] 2021-02-03 18:00
@ValWood 
For example sst2 is annotated to both, 'thiol-dependent ubiquitin-specific protease' activity by HMP and to 'metallopeptidase activity' by IEA (InterPro) (as well as Lys48-specific deubiquitinase activity and Lys63-specific deubiquitinase activity). Do you think the InterPro is wrong ?  

I haven't looked at the other specific annotations, but according to the Term Matrix there is some overlap: 

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/4782928/106789058-0b6d5c80-6652-11eb-9fed-c983e0c55ff9.png">

**Comment by ValWood** [comment] 2021-02-03 18:04
I will ask the authors of the htp dataset.

**Comment by sjm41** [comment] 2021-02-03 18:10
Pretty sure that's a metal-dependent DUB:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4033627/

**Comment by ValWood** [comment] 2021-02-03 18:34
Yep interpro:IPR000555 is clearly a metallopeptidase and that accounts for the 5  gene products that pombe has annotated to both metallopeptidase and thiol dependent.
I will fix these.

Hoever, I don't know if the  mapping of
GO:0061578 | Lys63-specific deubiquitinase activity | IEA with IPR035299
for  RPN11/PSMD14 is correct ? Does anyone know where that comes from?

**Comment by sjm41** [comment] 2021-02-03 19:01
@ValWood Note that we're adding a new "GO:0140492 metal-dependent deubiquitinase activity" term as part of this ticket so we can accurate annotate these things with one term.

**Comment by sjm41** [comment] 2021-02-03 19:07
Haven't checked if it's correct, but the interpro page (http://www.ebi.ac.uk/interpro/entry/InterPro/IPR035299/) seems to point to PMID: 25389291 for GO:0061578 | Lys63-specific deubiquitinase activity | IEA with IPR035299

**Comment by pgaudet** [comment] 2021-02-03 19:57
@sarach06 @EBI-Hsinyu Does this mapping look OK to you ? 

> GO:0061578 | Lys63-specific deubiquitinase activity | IEA with IPR035299
for RPN11/PSMD14 is correct ? Does anyone know where that comes from?

**Comment by sarach06** [comment] 2021-02-04 16:39
Hi!
As it is mentioned above, PMID: 25389291 supports that mapping but I also found these two articles: PMID: 22909820 and PMID: 19214193. Let me know if you agree and I can add them to this entry.
Best regards,
Sara

**Comment by ValWood** [comment] 2021-02-04 17:03
I can see why we have conflicts in the annotations here.

GO:0004843 thiol-dependent ubiquitin-specific protease activity
has migrated in term name and definition over time. 

2003-03-19 	Updated 	TERM 	ubiquitin-specific protease activity
2013-11-22 	Updated 	TERM 	ubiquitin-specific protease activity

The term name did not change to the current incarnation until 2016,

2016-02-10 	Updated 	TERM 	thiol-dependent ubiquitin-specific protease activity

and the definition was updated in 2013:

2013-12-18	Added	DEFINITION	Catalysis of the thiol-dependent hydrolysis of a peptide bond formed by the C-terminal Gly of ubiquitin.
2013-11-22 	Deleted 	DEFINITION 	Catalysis of the hydrolysis of various forms of polymeric ubiquitin.
2010-03-13	Deleted	DEFINITION	Catalysis of the hydrolysis of various forms of polymeric ubiquitin sequences. Will remove ubiquitin from larger leaving groups.

So really this term should become the more general "ubiquitin-specific protease/ubiquitin " term

**Comment by sjm41** [comment] 2021-07-15 10:21
Hi @pgaudet 

I just noticed that the new(ish) term "metal-dependent deubiquitinase activity (GO:0140492)" is currently being inferred as a child of cysteine (aka thiol) -type peptidase activity (GO:0008234).  I think the problem is that "ubiquitin-like protein-specific protease activity (GO:0019783)" should be a direct child of "peptidase activity (GO:0008233)" rather than "cysteine-type peptidase activity (GO:0008234)"

![Screenshot 2021-07-15 at 11 20 23](https://user-images.githubusercontent.com/16306861/125772503-20a2089b-2134-47a4-bf20-97a922f4ebd7.png)

**Comment by pgaudet** [comment] 2022-01-21 11:49
- [x] ubiquitin-like protein-specific protease activity (GO:0019783)" should be a direct child of "peptidase activity (GO:0008233)" rather than "cysteine-type peptidase activity (GO:0008234)" 
- [x] merge GO:0140491 ubiquitin-like hydrolase activity into ubiquitin-like protein-specific protease activity (GO:0019783)

**Comment by pgaudet** [comment] 2022-01-21 11:57
- [x] GO:0019783 ubiquitin-like protein peptidase activity - change def to "An isopeptidase activity that cleaves ubiquitin or ubiquitin-like proteins (ULP; e.g. ATG8, ISG15, NEDD8, SUMO) from target proteins."
- [x] add comment: While ubiquitin-like proteins can be rarely linked to substrates via bonds other than isopeptide bonds, all known ubiquitin-like peptidases cleave the isopeptide bond.

**Comment by pgaudet** [comment] 2022-01-21 12:08
- [ ] Merge GO:0070138 ubiquitin-like protein-specific isopeptidase activity into GO:0019783 ubiquitin-like protein-specific protease activity

**Comment by pgaudet** [comment] 2022-01-21 12:18
- [ ] Merge  GO:0070140 SUMO-specific isopeptidase activity  into GO:0016929  SUMO-specific protease activity  
- [ ] Change label to deSUMOlyase activity

**Comment by pgaudet** [comment] 2022-01-21 12:20
- [ ] GO:0070139 SUMO-specific endopeptidase activity -> move under endopeptidase activity

**Closed** 2022-01-24 16:32 UTC
Labels: PomBase, FlyBase, enzymes, in progress
