### ISSUE TITLE
prospore membrane biogenesis or assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14712] opened 2017-12-05 14:14 UTC
we have been using 2 terms in different parts of the graph to describe the same process

(assembly/biogenesis of the prospore membrane).

If both are needed (and I'm not sure that they are here),  they wouldneed a relationship between them.

![prospore membrane](https://user-images.githubusercontent.com/7359272/33611470-672d0eec-d9c6-11e7-9c29-3384cfe659ce.jpg)

(we think assembly is part of biogenesis)

**Comment by ValWood** [comment] 2017-12-05 14:16
![logical](https://user-images.githubusercontent.com/7359272/33611607-ebb7614e-d9c6-11e7-8750-e71f62531cd3.jpg)

**Comment by ValWood** [comment] 2017-12-05 14:20
I don't know if we absolutely require both, but the logical def of assembly should place it as a descendant of biogenesis.

**Comment by pgaudet** [comment] 2017-12-05 14:26
Right - I think @vanaukenk is proposing to merge most of these. 

In this particular case we can probably go ahead and merge. 

Thanks, Pascale

**Comment by vanaukenk** [comment] 2017-12-06 15:43
HI @ValWood 

Yes, the idea we're discussing on the editors' calls is to merge, or rename, assembly and biogenesis terms into a corresponding organization term.

From looking at the various types of GO synonyms that exist for assembly and biogenesis terms, as well as the usage of this language in the literature, it seems the terms are often used interchangeably.

In this case, the proposal would be to re-name GO:0099097 to 'prospore membrane organization' and GO:0032210 to 'ascopore-type prospore membrane organization'.  The regulation terms would also be re-named.  

A related issue, of course, is what gene products should actually be annotated to these terms, but we think that streamlining the ontology here will make for more consistency all around.

Thoughts on this idea are welcome!

**Comment by ValWood** [comment] 2017-12-07 07:48
I'd be happy for biogenesis to merge into organization.

So here I will review the 3 annotations to biogenesis to see  if they should stay at organization or move down to "assembly".

Could you make the link between the  existing "assembly term and the soon to be "organization" term?

cheers

Val

**Comment by ValWood** [comment] 2017-12-07 09:15
Actually, I'm not sure now.

Here the biogenesis is more equivalent to the assembly. I would even say that "biogenesis" might be a better term for the process than assembly.


-- | --GO:0032120 - ascospore-type prospore membrane assembly
The process in which the nascent membrane forms at the meiotic outer plaque and grows until closure occurs and forespores, or prospores, are formed.

GO:0099097    prospore membrane biogenesis
A cellular process that results in the biosynthesis of constituent macromolecules, assembly, and arrangement of constituent parts of a prospore membrane.

I really want to capture the "formation/assembly/biogenesis"

but "assembly" doesn't seem the best word for membranes. Would "formation" be better?

**Comment by pgaudet** [comment] 2017-12-07 10:33
Hi @ValWood 
What 'biogenesis' tries to capture is also the synthesis of the precursors; is this really part of the process ? 

I can see an argument to keep organization and assembly distinct in certain cases, but I am not sure about biogenesis. 

Thanks, Pascale

**Comment by ValWood** [comment] 2017-12-07 11:27
In "ribosome biogenesis" the biogenesis also includes transport.

In the prospore case, I agree we don't need  it. BUt I think the existing term


GO:0032120 - ascospore-type prospore membrane assembly
would work better if it were 
"ascospore-type prospore membrane formation"
or
ascospore-type prospore membrane assembly biosynthesis

**Comment by mah11** [comment] 2017-12-07 11:32
> ... but "assembly" doesn't seem the best word for membranes. Would "formation" be better?

How would you define the difference between "formation" and "assembly"?

Seems that's what would be needed to have them as different GO terms ...

**Comment by ValWood** [comment] 2017-12-07 12:05
OK probably "assembly" is OK....

**Comment by vanaukenk** [comment] 2017-12-07 14:49
@ValWood @mah11 

You've touched on the exact same issues we discussed on the editors call on Monday.  What are the essential differences between assembly, biogenesis, formation, morphogenesis, organization, production, etc. in the literature wrt different CCs and, therefore, in GO BP?

In lines 30-37 of this Google spreadsheet, I entered the results of some TextpressoCentral searches of the C. elegans literature for different CCs and the various terms above to see what got used in the literature.  

https://docs.google.com/spreadsheets/d/1gVKFtCZZzr3BR4avU82It1vDb2XJ_gV8cSYJn6Uaatc/edit#gid=0

A couple of things are revealed/suggested by these searches:

1.  Terms that describe the biological process of 'putting something together' are used varying in the literature, but often are referring to the same thing

2.  The same paper will use these different terms to describe the same thing

3.  There does seem to be some preference for using a particular term for a given CC, e.g. mitotic spindle assembly or synapse formation

Also in the top of the spreadsheet is a small sampling of biogenesis and assembly GO terms where synonyms have been applied somewhat inconsistently, but I strongly suspect this just mirrors what curators are seeing in the literature.

We debated the idea of choosing one term for all GO CCs, e.g. organization, and then generally including the other terms as exact synonyms vs the idea of choosing what seemed to be the more common term in the literature, e.g. formation.

There was concern that choosing different terms depending on the CC would be harder to maintain and present an overall inconsistent approach in the ontology, so that's why the current proposal is to just use one term, e.g. organization, for everything.  

The annotation question still holds, though:  what gene products really should be annotated to 'CC organization' terms in GO and with what relation?

**Comment by ValWood** [comment] 2017-12-07 15:16
I think we still need separate terms for  "organization" and "formation/biosynthesis/assembly"

You can organize membranes in multiple ways *after* they are made (via bending invagination etc).

I think this distinction probably holds for other processes too, but it should be fairly clear because these will  usually be siblings of assembly.

For example  spindle assembly, spindle elongation, spindle disassembly.....

**Comment by mah11** [comment] 2017-12-08 15:47
What I recall from back when we tried to impose some order and consistency on the BP terms for processes affecting CCs (umptygazillion years ago, so memory-related caveats apply) is that the distinction between CC organization and CC assembly is that organization is broader - it also encompasses disassembly (maybe not relevant for all CCs, but some do get taken apart in an orderly fashion by gene product actions) and alterations to CCs once they're formed.

I'm a little hazy now about CC morphogenesis, but it seems to me that if it's worth keeping at all, it fits under CC organization.

Because of the disassembly and remodeling processes that exist out there in reality, I don't think "organization" is the correct word to use in the names of terms for putting CCs together, but "assembly" or "formation" ought to work. In the previous round of work we used "formation" in exact synonyms for "assembly" terms because we couldn't pinpoint a way to differentiate the two in text or logical definitions. If someone does come up with a distinction, I'd have no objection to splitting formation from assembly.


That's also when we decided to define biogenesis for GO purposes as (synthesis of parts + assembly). We had intended to include biogenesis terms only for the few CCs where people and literature tend to include "making the parts" when they study and discuss making the CC - off the top of my head, I think the ribosome and fungal cell walls fit the bill. I don't know of CCs other than ribosome and cell wall for which biogenesis terms (as defined above) are useful. For the rest, unless someone makes a specific case for including biogenesis, I would go with just an assembly term, with "biogenesis" in related (not exact) synonyms.

It was never easy to figure out how "biogenesis" terms should relate to organization terms, and I wouldn't try to argue that we necessarily got it right. We might lose a little bit if the ribosome and cell wall didn't have GO terms available for their "make the parts, then put them together" literature, but it might be worth it to reduce confusion and to stop having "biogenesis" terms that don't fit the pattern kicking around. I'm neutral on that point.


tangent: there's something slightly dodgy about the synonyms for GO:0016043 - two pairs identical except for dbxref, and two with wrong scope

**Comment by ValWood** [comment] 2017-12-08 15:55
I don't have any problem with the existing "organization" (in the general sense) . Except here,  where there clearly is a problem, but only a small missing parentage issue. In general, it seems to work fine  as it is....

**Comment by ValWood** [comment] 2020-03-09 17:51
I still think that for the prospore membrane the term should be "formation".

This is because the membrane does not necessarily "form" de novo. It is partly 'remodelled" from existing  membrane.  Assembly just sounds  wrong.

PubMed Search
"prospore membrane formation"  19
"prospore membrane assembly"  0
"prospore membrane biogenesis" 0


Can we call the term
-- | --GO:0032120 - ascospore-type prospore membrane assembly
"ascospore-type prospore membrane formation"  instead

and merge in the biogenesis term?

**Comment by pgaudet** [comment] 2020-03-10 08:47
I changed the term label GO:0032120 - ascospore-type prospore membrane assembly to 
"ascospore-type prospore membrane formation" 
as well as the regulation terms, regulation of ascospore-type prospore membrane assembly and
positive regulation of ascospore-type prospore membrane assembly

and merged "GO:0099097 prospore membrane biogenesis into GO:0032120 ascospore-type prospore membrane formation

What do you want to do with 
"prospore membrane formation" and
"prospore membrane assembly" ? 

Thanks, Pascale

**Comment by pgaudet** [comment] 2020-03-10 08:48
Is it OK that this term is_a 'GO:0003006 developmental process involved in reproduction' ? Shouldn't it be 'part_of'?

**Comment by ValWood** [comment] 2020-03-10 10:42
> Is it OK that this term is_a 'GO:0003006 developmental process involved in reproduction' ? Shouldn't it be 'part_of'?

I'm not sure about that! It is_a developmental process, and it's part_of reproduction !

I guess "prospore" covers non-ascomycete fungi.
I would probably say "formation" here too, if the process is similar, but I really don't know.
@CuzickA @mah11  any opinion?

**Comment by mah11** [comment] 2020-03-16 17:54
> I guess "prospore" covers non-ascomycete fungi.

I don't know whether there's any difference in the vocabulary used for ascomycete vs. other fungi.

Bacterial endospores go through a forespore/prospore stage. It's worth checking whether there's a prospore membrane formation process relevant to them.

> I would probably say "formation" here too ...

I would still struggle to define a distinction between "formation" and "assembly" for membranes or anything else in GO CC. For that reason I don't see a great need to depart from consistency with other "CC assembly" process term names. But I don't feel strongly either way.

>>  Is it OK that this term is_a 'GO:0003006 developmental process involved in reproduction' ? 
>> Shouldn't it be 'part_of'?
> 
> I'm not sure about that! It is_a developmental process, and it's part_of reproduction !

This (is_a developmental process, part_of reproduction) is correct for fungi, as far as I know. I think spore formation is not reproduction in bacteria, but check with someone who would know better!

**Comment by ValWood** [comment] 2020-03-16 19:16
To me:
Assembly is the action of fitting together the components (de novo)
Forming is 'broader' it also includes 'arranging/rearranging'  something pre-existing (so remodelling can also be 'forming').

**Comment by pgaudet** [comment] 2020-03-17 08:14
@ValWood @mah11 

@vanaukenk 's proposal was to use 'x membrane organisation' instead of formation or assembly; what do you thing to rename 'ascospore-type prospore membrane formation' 
-> 'ascospore-type prospore membrane organisation'? 

Thanks, Pascale

**Comment by mah11** [comment] 2020-03-17 09:19
> To me:
> Assembly is the action of fitting together the components (de novo)
> Forming is 'broader' it also includes 'arranging/rearranging' something pre-existing (so remodelling can also be 'forming').

I don't share this view ... tbh, it doesn't even make sense to me. Formation and assembly both build something that wasn't there before. Remodeling something that already exists isn't formation any more than it is assembly. And see below ...

> @vanaukenk 's proposal was to use 'x membrane organisation' instead of formation or assembly; what do you thing to rename 'ascospore-type prospore membrane formation'
> -> 'ascospore-type prospore membrane organisation'?

This would change the meaning as well as the name. That should be safe, as long as the text definition is updated to match, since the new meaning is broader. It also seems to fit Val's thinking about what the process actually is - for the "arranging" or "remodeling" she mentioned, "organization" is the correct GO name.

**Comment by ValWood** [comment] 2020-03-17 10:17
I don't think we could do that.
Organization is broader again and includes  assembly and formation and remodelling dissassembly.


Think chromatin. organization, assembly, remodelling, dissassembly. All different. All required to describe gene products.

**Comment by ValWood** [comment] 2020-03-17 10:43
> Formation and assembly both build something that wasn't there before. 

Yes  they do

>Remodeling something that already exists isn't formation any more than it is assembly.

OK. But the point is that the community  refers to this processes as  "prospore membrane formation"
I assumed (possibly incorrectly) that this is because these structures 'form' from preexisting membrane structures (via membrane trafficking). They don't assemble from 'building blocks'.
But  we should use the wording the community uses preferentially.

If people think that assembly and formation are equivalent  then they can have the same logical definitions but use the appropriate/commonly used labels.

My main issue is to link the 2 terms in  different branches of the graph at the top (and ideally get rid of biogenesis-> organization), using labels used by the community.

**Comment by pgaudet** [comment] 2020-03-17 16:02
The two terms are merged. If 'formation' is OK then this ticket can close. 

@ValWood please confirm.

Thanks, Pascale

**Closed by pgaudet** 2020-03-17 16:02 UTC
Labels: PomBase, term merge

**Comment by ValWood** [comment] 2020-03-17 16:14
close for me.
