### ISSUE TITLE
Add SPARQL check to ensure that no classes reference obsolete classes

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13793] opened 2017-07-03 18:33 UTC
To prevent this: https://github.com/geneontology/go-ontology/issues/13685#issuecomment-312710378

**Comment by pgaudet** [comment] 2017-11-27 20:21
Hi @dougli1sqrd 

Please check if this is a duplicate of #14605 - perhaps the query is already done; the next step would be an update mechanism. 

Thanks, Pascale

**Closed** 2017-12-04 19:26 UTC
Labels: enhancement

**Comment by pgaudet** [comment] 2017-12-04 21:09
Hi ! So, how will error show up--- is there a report we need to look at ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment] 2017-12-04 21:21
Hello!
Yeah there's an error report. It'll be in `src/ontology/reports`

The name of the file will be the same as the name of the sparql query file, but with csv. For example, in src/sparql/ there is the `obsolete-reference-violation.sparql`, this will create a `obsolete-reference-violation.csv` in the report directory.

**Comment by cmungall** [comment] 2017-12-04 21:33
most of the time this will cause a travis fail and people will just see this at the end of their travis report
