### ISSUE TITLE
ntr protein serine/threonine kinase binding

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15218] opened 2018-02-20 16:15 UTC
I would like to see "protein serine/threonine kinase binding” added to the GO ontology under the parent term "protein kinase binding (GO:0019901).  The definition could be "Interacting selectively and non-covalently with a protein serine/threonine kinase.”  Example can be found in PMID:28608965.

**Comment by RLovering** [comment] 2018-02-20 17:26
I have always found it odd that protein tyrosine kinase binding is a term but not protein serine/threonine kinase binding

**Comment by pgaudet** [comment] 2018-03-26 16:59
Discussing at the editor's call. These terms are problematic for annotation, because they require that we we evidence that (1) there is a binding activity and (2) one of the partner is a kinase (or whatever activity the term implies). 

Ideally this should be a query of the type : for protein X, give me binding partners that are kinases (based on MF annotations). If we can do that then we would merge these terms into 'protein binding'. 

@cmungall do you thing it would be possible to do these types of queries ? 
Depending on your answer we'll decide what to do next.

Thanks, Pascale

**Comment by krchristie** [comment] 2019-07-24 00:14
@ukemi - I noticed that this one still had the "editors-discussion" tag, but when we discussed it last year, we concluded that you and @dougli1sqrd were going to do some analysis, so I added you to the assignees for this ticket.

**Comment by ValWood** [comment] 2020-11-06 13:05
Was the decision here that specific protein family binding terms are "out of scope"?

**Comment by RLovering** [comment] 2020-11-06 13:57
From discussions with Pascale about transcription factors I believe that the 'function'-binding terms were being kept and new terms can be approved
@pgaudet

**Comment by ValWood** [comment] 2020-11-06 14:14
For *any* function???

**Comment by pgaudet** [comment] 2020-11-09 17:23
Ontology call - let's do it.

**Comment by pgaudet** [comment] 2020-11-09 17:24
Pascale: add rules in the wiki documentation and/or yaml

**Comment by ValWood** [comment] 2020-11-09 17:32
So what are the rules? Can a binding term be added for any activity?
Why isn't the "with' field sufficient?
What is special about protein kinases (I expected that protein kinase binding would go eventually because it is redundant with the input). GO seem to have different rules on different days.

**Comment by krchristie** [comment] 2020-11-09 19:40
> So what are the rules? Can a binding term be added for any activity?
> Why isn't the "with' field sufficient?
> What is special about protein kinases (I expected that protein kinase binding would go eventually because it is redundant with the input). GO seem to have different rules on different days.

I would say we're going with practicality rather than absolute rules. Yes, we would like to get to a place where we don't have binding terms for specific types of substrates. However, currently we do not have the ability to do useful grouping based on the contents of the with field. Until we do, we feel that this term is reasonable as it represents a grouping of large class of proteins rather than an individual gene product. Are we perfect every time? Of course not, but we're trying to balance current usability with long term goals and we've come to the conclusion that there isn't a good substitute for this term at this time.

**Comment by ValWood** [comment] 2020-11-09 20:35
The thing is, such a term is only useful if it is used for all instances of protein kinase binding that are annotated. 
Pombe has 130 protein kinase which have over 1000 interactions curated so far, all of  these interactors  should move to protein  kinase binding.  Nobody is going to do this, so these terms will be inconsistently annotated. Anything  that is inconsistently annotated isn't really useful. The usefulness only comes when the same things are annotated using the same terms.
Wouldn't it be better to move towards  the  final aim rather than have an incomplete/partial  interim solution which won't really help  users but  will create more work in the long run? Then we could concentrate on the things that are really needed.

If a user really really wants  everything that is kinase binding (which will likely be everything if you think about the phoproteome - because we aren't excluding substrates in these terms?) they can mine the with field with a bit of shell scripting.

**Comment by ValWood** [comment] 2020-11-09 20:38
Fission yeast has 3073 phosphorylated proteins so far.  These (mainly) bind to serine/threonine protein kinases.

The definition is 
Interacting selectively and non-covalently with a protein kinase,
so the terms do not exclude substrates  even if that was the intention.

**Comment by ValWood** [comment] 2020-11-09 20:44
So what I am trying to say is that by adding these terms we are doing the users a diservice, because they would get a better (infinitely more complete) set of genes by mining the "with field"  for  all of the GPs annotated to  "protein kinase activity" and "protein binding"

**Comment by pgaudet** [comment] 2020-11-10 07:43
The issue is there are > 900 children classes to 'protein binding', and quite a few annotations: 
https://docs.google.com/spreadsheets/d/1bSNOQg8FZi8LYdNn047WGwK7ljAb8Nvqgjgx9W046iQ/edit#gid=0

Excluding IntAct, about 1/3 of the protein binding annotations are to **children** of GO:0005515. 
Ideally we would annotate to GO:0005515 with an interactor in the 'with' field, but that's a huge task to tackle right now. So, given this, we decided to leave that project for later and allow the creation of that term. (just 'protein kinase binding and children has 1385 EXP annotations). 

I agree the inconsistency is not ideal but if curators fill in the 'with' field for all those annotations, it will facilitate migration later. 


Thanks, 
Pascale

**Comment by pgaudet** [comment] 2020-11-10 07:43
> The definition is
"Interacting selectively and non-covalently with a protein kinase"
so the terms do not exclude substrates even if that was the intention.

I dont think that was the intention ?

**Comment by ValWood** [comment] 2020-11-10 08:35
OK. PomBase has 2 annotations to protein kinase binding, one annotated and one from PAINT. I'm going to  filter/fix because we can't be consistent.
 
> I don't think that was the intention ?

I don't think that is clear...and sometimes we know binding information before substrate?

and we have things like this:

https://www.pombase.org/gene/SPCC63.05
GO:0051721 | protein phosphatase 2A binding | IBA with 62011 , PTN000101130 
where the nature of the interaction isn't known, so substrate is likely?

**Comment by ValWood** [comment] 2020-11-10 09:01
>I agree the inconsistency is not ideal but if curators fill in the 'with' field for all those annotations,

Is the "with" field mandatory for protein binding children? I don't think it is- but it is mandatory for protein binding.

**Comment by pgaudet** [comment] 2020-11-10 11:39
It is not mandatory because in some cases it is not known. I'm thinking of 'actin binding', maybe this is rather an exception ? We could enforce IPI (which requires a 'with' value), except for those exceptions ?

**Comment by ValWood** [comment] 2020-11-10 12:01
I think that could be useful for later. and warnings. It's a step towards removal.

Presumably  a term where everything has a "with" field can be merged.

**Closed** 2020-11-17 16:59 UTC
Labels: New term request, binding
