### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12854] opened 2016-12-05 11:12 UTC
Seems to be an SVN issue. Same error on previous build, so may not be temporary thus ticket.

+ SVN_SSH='ssh -l jenkins -i /home/jenkins-slave/.ssh/id_rsa.go-commit -o "StrictHostKeyChecking no"'
+ svn commit '-mupdate go-plus.owl' go-plus.owl go-plus.obo
Sending        go-plus.obo
Sending        go-plus.owl
Transmitting file data .svn: E000013: Commit failed (details follow):
svn: E000013: Unable to create pristine install stream
svn: E000013: Can't create temporary file from template '/home/jenkins-slave/workspace/release-go/svn/.svn/tmp/svn-XXXXXX': Permission denied
Build step 'Execute shell' marked build as failure

**Comment by ukemi** [comment] 2016-12-05 17:01
I just made an edit to the ontology and the build failed as well.

**Comment by paolaroncaglia** [comment] 2016-12-05 18:39
Same here.

**Comment by kltm** [comment] 2016-12-05 19:34
In the future, items like this belong in the go-site tracker--mechanism, build, and machine issues are grouped over there, ontology/knowledge issues over here.

**Comment by kltm** [comment] 2016-12-05 19:36
Dupe of geneontology/go-site#280

**Comment by ukemi** [comment] 2016-12-05 19:36
Sounds good. Should we continue to open these even when we get the build/release failure notices, or do automatically respond to those from the e-mails?

**Closed by kltm** 2016-12-05 19:36 UTC
Labels: high priority, Infrastructure

**Comment by kltm** [comment] 2016-12-05 19:41
I'm not sure I'm following. I personally do not get fails emails from most of the jobs on jenkins--it would become a full-time job just sorting through those. for some "critical" jobs, something is usually sent to me or @cmungall , but given the volume of email that passes through us, if something important looks like it has gone down, it is probably best to open a ticket on go-site.

**Comment by ukemi** [comment] 2016-12-05 19:43
That makes sense. Most of the time when the GO-build fails it's due to an error introduced by an editor, so you shouldn't be bothered by those anyways. We will open a ticket if it looks like it is a pipeline problem.
