### ISSUE TITLE
Merge  GO:0036459 thiol-dependent ubiquitinyl hydrolase activity  into GO:0004843 thiol-dependent ubiquitin-specific protease activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19723] opened 2020-07-01 13:58 UTC
GO:0036459 thiol-dependent ubiquitinyl hydrolase activity
and GO:0004843 thiol-dependent ubiquitin-specific protease activity 

seem to only differ by the substrate - ie removal of ubiquitin from a protein (GO:0004843) versus from any molecule ( GO:0036459) - but we cannot find evidence that molecules other than proteins are ubiquitinated (see also https://github.com/geneontology/go-ontology/issues/17398). 

I propose to merge and change the label to 'thiol-dependent deubiquitinase activity' 

@ValWood @deustp01 @ukemi 
OK ? 

Thanks, Pascale

**Comment by ValWood** [comment] 2020-07-01 14:20
I do not see any difference in the  our annotation. Seems to be a completely overlapping set. All thiol-dependent to so is that required in the term name?

**Comment by sjm41** [comment] 2020-07-01 15:51
'Thiol-dependent' is needed here, as we're trying to disentangle/distinguish the thiol-dependent (cysteine-type) deubiquitinases (which are the majority) from the metal-dependent deubiquitinases (the JAMM family) - see #17398.

**Comment by ValWood** [comment] 2020-07-01 15:58
Oh. We have at least some of the JAMMs as thiol-dependent
https://www.pombase.org/gene/SPAC31G5.13
and this was community curated...I will ask about that.

**Comment by sjm41** [comment] 2020-07-01 16:16
As far as I know, all JAMMs are metallopeptidases - see the review mentioned on the linked ticket (PMID:19489724).

I think the problem is/was that we haven't previously had a good term for these metal-dependent deubiquitinases, leading to mis-annotations/assertions  - this is the main point now being addressed in #17398.  May well be more annotations to review depending on how exactly things get fixed...

**Comment by ValWood** [comment] 2020-07-01 16:30
OK, I will fix PomBase when the terms are in place.

**Comment by pgaudet** [comment] 2020-07-14 16:02
Hi @deustp01 

Note that there are Reactome mappings to the term being merged (GO:0036459); those should be moved (automatically I think in the Reactome pipeline) to the new main ID GO:0004843. 

Thanks, Pascale

**Comment by pgaudet** [comment] 2020-07-15 08:42
@sjm41 Are the following parents OK ? 

+is_a: GO:0008242 ! omega peptidase activity
+is_a: GO:0101005 ! ubiquitinyl hydrolase activity

Thanks, Pascale

**Comment by sjm41** [comment] 2020-07-15 08:53
Yep, those parents look good to me.

**Closed** 2020-07-15 12:12 UTC
Labels: term merge
