### ISSUE TITLE
syntax error in go-basic.obo file?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15010] opened 2018-02-02 11:40 UTC
We (FlyBase) have this link on our website that is meant to point users to the latest go-basic.obo file:
purl.obolibrary.org/obo/go/go-basic.obo

This works fine using the Safari browser, but using Firefox we get this error message:

==
XML Parsing Error: syntax error
Location: http://snapshot.geneontology.org/ontology/go-basic.obo
Line Number 1, Column 1:format-version: 1.2
^
==

Perhaps there is an error near the top of this file which causes problems for some browsers?  Or is this just a weird Firefox bug??

Thanks,
Steven

**Comment by ukemi** [comment] 2018-02-02 13:38
Works with Chrome too.

**Comment by cmungall** [comment] 2018-02-02 17:25
This looks similar to https://github.com/geneontology/pipeline/issues/8 but this has been fixed. Note this error message is not telling you there is a syntax error in the obo, it is expecting an XML file and it does not parse as an XML file. The problem is in the web server configuration.

Can you provide a flybase website link thanks.

cc @kltm

**Comment by sjm41** [comment] 2018-02-02 19:09
Thanks Chris - apologies if I mis-diagnosed the problem.
The link is on this FlyBase page:
http://flybase.org/cgi-bin/get_static_page.pl?file=bulkdata7.html&title=Current%20Release
in the 'Ontology Terms ' section -> 'Current live files':

Actually, should the purl be:
purl.obolibrary.org/obo/go/go-basic.obo
or 
purl.obolibrary.org/obo/go-basic.obo
(the latter would match the pattern I see for the owl file purl at: https://www.ebi.ac.uk/ols/ontologies/go )

**Comment by cmungall** [comment] 2018-02-02 20:36
looks like our mime types are still set incorrectly, reopened the pipeline ticket

In general, for any of your ontologies, the canonical PURLs can be found on http://obofoundry.org/

e.g.
http://obofoundry.org/ontology/go.html

For GO specifically, http://geneontology.org/page/download-ontology should always be up to date

**Comment by pgaudet** [comment] 2018-02-07 19:06
There were two in the go-edit.obo file for a while, 
GO:0008381 and GO:0022839, and that never created a problem.

**Comment by balhoff** [comment] 2019-10-04 15:50
I now see `Content-Type: text/obo` for this file, so seems like we can close this. But please reopen if this is continuing to be a problem.

**Closed by balhoff** 2019-10-04 15:50 UTC
