### ISSUE TITLE
Does synaptic vesicle transport occur in the cytoplasm?

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16547] opened 2018-10-31 01:14 UTC
This is an inference we get

See PR #16546

cc @lpalbou

**Comment by ukemi** [comment] 2018-10-31 16:45
The structure is not in alignment with exocytosis. Seems incorrect to say that exocytosis occurs in the cytoplasm, but 'synaptic vesicle exocytosis' is a child of 'synaptic vesicle transport'. Isn't exocytosis more than just transport of the vesicle? I would be ok with it being a 'vesicle-mediated transport' because that refers to the contents as well. I think we need to clean up this are of the ontolgy.

**Comment by ukemi** [comment] 2018-11-01 13:00
Is a cytoplasmic vesicle part of the cytoplasm? Or is it located in but distinct from the cytoplasm?

**Comment by pgaudet** [comment] 2018-11-01 14:33
I was wondering if this is strictly an intracellular process - for example synaptic vesicles are endocytosed, so they exist extracellularly for a time ? 

https://en.wikipedia.org/wiki/Synaptic_vesicle#The_synaptic_vesicle_cycle

**Comment by ukemi** [comment] 2018-11-01 14:45
OK. It fits the definition then. So if a synaptic vesicle is always part of the cytoplasm, then it's transport necessarily occurs in the cytoplasm. I'm not sure the property chain is the problem here.

**Comment by ukemi** [comment] 2018-11-01 14:56
But I don't think the vesicles are endocytosed. I think that the neurotransmitter in the synaptic cleft is endocytosed to form new synaptic vesicles. Clearly we need an expert to comment on this.

**Comment by pgaudet** [comment] 2018-11-01 15:39
I dont know either whether vesicles are endocytosed - however wikipedia states "6. Endocytosis

This accounts for the re-uptake of synaptic vesicles in the full contact fusion model. However, other studies have been compiling evidence suggesting that this type of fusion and endocytosis is not always the case. "

**Comment by BarbaraCzub** [comment] 2019-01-16 17:23
This ticket is possibly related: https://github.com/geneontology/go-ontology/issues/15989

**Comment by BarbaraCzub** [comment] 2019-02-12 18:07
https://github.com/geneontology/go-ontology/issues/15990

**Comment by BarbaraCzub** [comment] 2019-02-12 18:22
According to the Sudhof review of synaptic vesicle cycle (PMID:15217342, Figure 1 and Figure 3), synaptic vesicles always remain inside the cell. Therefore, I think it is correct that they are always a part of the cytoplasm.

During exocytosis synaptic vesicles merge with the plasma membrane to release their contents, so at this stage they are no longer 'vesicles'; and during endocytosis they do the opposite, so will bud off from plasma membrane towards the inside of the cell, at which stage the vesicle will become a part of the cytoplasm. Therefore, this will not be in disagreement with the definition of cytoplasm:
GO:0005737 cytoplasm - "All of the contents of a cell excluding the plasma membrane and nucleus, but including other subcellular structures."

**Comment by BarbaraCzub** [comment] 2019-02-13 14:26
https://github.com/geneontology/go-ontology/issues/15989

**Comment by BarbaraCzub** [comment] 2019-02-13 16:59
Endo- and exocytosis basics:
https://www.thoughtco.com/what-is-endocytosis-4163670
https://www.thoughtco.com/what-is-exocytosis-4114427
Endo- and exocytic vesicles are **intracellular**. During endocytosis they form by invagination and budding from the plasma membrane and during exocytosis, they merge with the plasma membrane.

-----------------------------------------------------------------

Extracellular vesicles include exosomes and microvesicles. 
- Exosomes are released by exocytosis of multivesicular bodies (MVBs). In this case the outermost vesicle is not released but merges with the plasma membrane like during 'regular' exocytosis of non-vesicle contents. The internal vesciles of an MVB become exosomes upon release from the cell.
- Microvesicles are formed by budding off from the plasma membrane towards to outside of the cell.
DOI: 10.1083/jcb.201211138
doi: 10.1080/19336918.2016.1236899

**Comment by BarbaraCzub** [comment] 2019-02-14 12:59
Points to address:
1. 'synaptic vesicle transport' vs. 'vesicle-mediated transport in synapse' and 'synaptic vesicle **cytoskeletal** transport'
![screenshot 2019-02-14 at 11 15 49](https://user-images.githubusercontent.com/16541096/52783783-dfaed180-304a-11e9-8345-60b09b76832e.png)
![screenshot 2019-02-14 at 11 16 25](https://user-images.githubusercontent.com/16541096/52783784-dfaed180-304a-11e9-9d5e-1d38e12f0c9f.png)
![screenshot 2019-02-14 at 11 16 50](https://user-images.githubusercontent.com/16541096/52783785-dfaed180-304a-11e9-8856-9887a062a3d5.png)
**--> If transport of vesicles is powered by molecular motors, then it cannot be vesicle-mediated.** I would remove the relation between 'synaptic vesicle transport' and 'vesicle-mediated transport in synapse.
![vesicle transport vs vesicle-mediated transport](https://user-images.githubusercontent.com/16541096/52783880-387e6a00-304b-11e9-9e2f-b5da2f69ff00.png)

---------------------------------------------

2. **'synapse' should be a child of 'cell-cell junction'** - cc @ftwkoopmans
![screenshot 2019-02-14 at 11 26 15](https://user-images.githubusercontent.com/16541096/52783943-6cf22600-304b-11e9-912f-87fd2b957144.png)
![screenshot 2019-02-14 at 11 26 35](https://user-images.githubusercontent.com/16541096/52783944-6d8abc80-304b-11e9-8dcd-ea5435707298.png)
![synapse](https://user-images.githubusercontent.com/16541096/52784016-a88cf000-304b-11e9-9b41-90c318f7edfd.png)

-------------------

3. **'synaptic vesicle cycle' should be a child of both: 'vesicle-mediated transport in synapse' (is_a) and 'vesicle-mediated intracellular transport' (is_a)**. ('Vesicle-mediate transport in synapse' should _probably (?)_ be a child of 'vesicle-mediated transport' (is_a) to be inclusive of any extracellular vesicles that might get transported across the synaptic cleft (I don't know whether this ever happens, @ftwkoopmans this would be a question to synapse experts).
![screenshot 2019-02-14 at 11 36 41](https://user-images.githubusercontent.com/16541096/52784387-d45ca580-304c-11e9-8342-db45231a5d78.png)
![screenshot 2019-02-14 at 11 16 25](https://user-images.githubusercontent.com/16541096/52783784-dfaed180-304a-11e9-9d5e-1d38e12f0c9f.png)
![screenshot 2019-02-14 at 11 37 57](https://user-images.githubusercontent.com/16541096/52784428-01a95380-304d-11e9-9600-3b6e9b22372f.png)
![synaptic vesicle cycle](https://user-images.githubusercontent.com/16541096/52784519-47feb280-304d-11e9-963c-a3c6c473e58b.png)

------------

4. 'Synaptic vesicle exocytosis' should probably **not** be a child of 'calcium ion regulated exocytosis' (unless this is ok due to the comment about its leakiness? - screenshot below - this is not clear to me. cc @ftwkoopmans), because it itself has the child 'spontaneous exocytosis of neurotransmitter', which is **independent of Ca2+**. 
![screenshot 2019-02-14 at 11 45 44](https://user-images.githubusercontent.com/16541096/52784885-6c0ec380-304e-11e9-8914-518bcce4c593.png)
![screenshot 2019-02-14 at 11 47 04](https://user-images.githubusercontent.com/16541096/52784886-6c0ec380-304e-11e9-9c0c-563146d7217b.png)
![screenshot 2019-02-14 at 11 47 31](https://user-images.githubusercontent.com/16541096/52784887-6c0ec380-304e-11e9-804e-43e507f0ce6c.png)
![synaptic vesicle exocytosis](https://user-images.githubusercontent.com/16541096/52784894-729d3b00-304e-11e9-876a-db96c1f4c1b4.png)

------------

5. 'Sperm entry' should not be a child of 'endocytosis', because it is not vesicle-mediated.
![screenshot 2019-02-14 at 11 50 18](https://user-images.githubusercontent.com/16541096/52785001-c7d94c80-304e-11e9-8b72-749e09694fa5.png)
![screenshot 2019-02-14 at 11 50 37](https://user-images.githubusercontent.com/16541096/52785003-c7d94c80-304e-11e9-93f0-872cd1fd419e.png)
![sperm entry](https://user-images.githubusercontent.com/16541096/52785045-eccdbf80-304e-11e9-940d-a1ba9c40d24b.png)

---------------

6. 'Endocytosis' and 'exocytosis' should probably be children of 'vesicle-mediated **intracellular** transport', because the vesicles, which mediate these processes never actually leave the cell, and at the time when they merge with the plasma membrane they are no longer 'vesicles'. This would be applicable even to exocytosis of multivesicular bodies (MVBs), which results in release of extracellular vesicles (exosomes), because the outermost vesicle of the MVB, _which mediates the transport_, never leaves the cell. (I probably would not have thought so more than a year ago (#14540), but having investigated this question in more depth now, I think this inference is not unacceptable).

---------

These are the major changes, which I suggest should be made. I am attaching a photo of my scribbles with a summary of other relationships that I would consider adding and/or removing.
![20190214_121416](https://user-images.githubusercontent.com/16541096/52787084-b1ce8a80-3054-11e9-80fc-d5475d8917c6.jpg)

--------------

With regard to the original question: 'Does synaptic vesicle transport occur in the cytoplasm?', firstly we need to distinguish between 'synaptic vesicle transport' and 'vesicle-mediated transport in synapse' as I mentioned in point 1. 'Synaptic vesicle transport' describes the transport of a vesicle (mediated by something else, e.g. a molecular motor along a microtubule), whereas 'vesicle-mediated transport in synapse' refers to transport of some other cargo that is mediated by the vesicle. If extracellular vesicles are ever released into the synaptic cleft (I do not know whether this happens (cc @ftwkoopmans)), then 'vesicle-mediated transport in synapse' should **not** be restricted to occurring only in the cytoplasm. 'Synaptic vesicle transport' itself is very vaguely defined, so there is not much that can be inferred, but its child 'synaptic vesicle cytoskeletal transport' is definitely a process occurring in the cytoplasm, so based on this, I would probably answer 'yes' to the original question.

-----------------------------

@ukemi could you please advise how I should proceed with this? cc @RLovering 

This ticket is also related to https://github.com/geneontology/go-ontology/issues/15989: 'transport vesicle' should probably not be limited to the 'constitutive secretory pathway' (also please see Paola's comments from 29 Nov 2017 in https://github.com/geneontology/go-ontology/issues/14540), and https://github.com/geneontology/go-ontology/issues/15990, that @ftwkoopmans has been very helpful with, and which is now closed.

**Comment by BarbaraCzub** [comment] 2019-04-29 14:26
@ukemi and @BarbaraCzub had a call to discuss this on 29th April 2019.

Decisions re:

> Points to address:
> 
> 1. 'synaptic vesicle transport' vs. 'vesicle-mediated transport in synapse' and 'synaptic vesicle **cytoskeletal** transport'
>    ![screenshot 2019-02-14 at 11 15 49](https://user-images.githubusercontent.com/16541096/52783783-dfaed180-304a-11e9-8345-60b09b76832e.png)
>    ![screenshot 2019-02-14 at 11 16 25](https://user-images.githubusercontent.com/16541096/52783784-dfaed180-304a-11e9-9d5e-1d38e12f0c9f.png)
>    ![screenshot 2019-02-14 at 11 16 50](https://user-images.githubusercontent.com/16541096/52783785-dfaed180-304a-11e9-8856-9887a062a3d5.png)
>    **--> If transport of vesicles is powered by molecular motors, then it cannot be vesicle-mediated.** I would remove the relation between 'synaptic vesicle transport' and 'vesicle-mediated transport in synapse.
>    ![vesicle transport vs vesicle-mediated transport](https://user-images.githubusercontent.com/16541096/52783880-387e6a00-304b-11e9-9e2f-b5da2f69ff00.png)

Re 1. @ukemi and @BarbaraCzub agreed that the link between 'synaptic vesicle transport' and 'vesicle-mediated transport in synapse' should be removed.



> 2. **'synapse' should be a child of 'cell-cell junction'** - cc @ftwkoopmans
>    ![screenshot 2019-02-14 at 11 26 15](https://user-images.githubusercontent.com/16541096/52783943-6cf22600-304b-11e9-912f-87fd2b957144.png)
>    ![screenshot 2019-02-14 at 11 26 35](https://user-images.githubusercontent.com/16541096/52783944-6d8abc80-304b-11e9-8dcd-ea5435707298.png)
>    ![synapse](https://user-images.githubusercontent.com/16541096/52784016-a88cf000-304b-11e9-9b41-90c318f7edfd.png)

Re 2. @ukemi and @BarbaraCzub agreed that this should remain unchanged for now.



> 3. **'synaptic vesicle cycle' should be a child of both: 'vesicle-mediated transport in synapse' (is_a) and 'vesicle-mediated intracellular transport' (is_a)**. ('Vesicle-mediate transport in synapse' should _probably (?)_ be a child of 'vesicle-mediated transport' (is_a) to be inclusive of any extracellular vesicles that might get transported across the synaptic cleft (I don't know whether this ever happens, @ftwkoopmans this would be a question to synapse experts).
>    ![screenshot 2019-02-14 at 11 36 41](https://user-images.githubusercontent.com/16541096/52784387-d45ca580-304c-11e9-8342-db45231a5d78.png)
>    ![screenshot 2019-02-14 at 11 16 25](https://user-images.githubusercontent.com/16541096/52783784-dfaed180-304a-11e9-9d5e-1d38e12f0c9f.png)
>    ![screenshot 2019-02-14 at 11 37 57](https://user-images.githubusercontent.com/16541096/52784428-01a95380-304d-11e9-9600-3b6e9b22372f.png)
>    ![synaptic vesicle cycle](https://user-images.githubusercontent.com/16541096/52784519-47feb280-304d-11e9-963c-a3c6c473e58b.png)

Re 3. @ukemi and @BarbaraCzub agreed that 'synaptic vesicle cycle' should be a child of 'vesicle-mediated transport in synapse' (which in turn is a child of 'vesicle-mediated transport'), but it should not become a child of 'vesicle-mediated intracellular transport', because even though the vesicles themselves are intracellular, parts of the process can occur extracellularly.



> 4. 'Synaptic vesicle exocytosis' should probably **not** be a child of 'calcium ion regulated exocytosis' (unless this is ok due to the comment about its leakiness? - screenshot below - this is not clear to me. cc @ftwkoopmans), because it itself has the child 'spontaneous exocytosis of neurotransmitter', which is **independent of Ca2+**.
>    ![screenshot 2019-02-14 at 11 45 44](https://user-images.githubusercontent.com/16541096/52784885-6c0ec380-304e-11e9-8914-518bcce4c593.png)
>    ![screenshot 2019-02-14 at 11 47 04](https://user-images.githubusercontent.com/16541096/52784886-6c0ec380-304e-11e9-9c0c-563146d7217b.png)
>    ![screenshot 2019-02-14 at 11 47 31](https://user-images.githubusercontent.com/16541096/52784887-6c0ec380-304e-11e9-804e-43e507f0ce6c.png)
>    ![synaptic vesicle exocytosis](https://user-images.githubusercontent.com/16541096/52784894-729d3b00-304e-11e9-876a-db96c1f4c1b4.png)

Re 4. @ukemi and @BarbaraCzub agreed that:
- 'synaptic vesicle exocytosis' should not be a child of 'calcium ion regulated exocytosis' (then 'spontaneous exocytosis of neurotransmitter', which is independent of Ca2+, will not be a grandchild of 'calcium ion-regulated exocytosis of neurotransmitter').
- 'calcium ion-regulated exocytosis of neurotransmitter' should become a direct child of 'calcium ion regulated exocytosis'



> 5. 'Sperm entry' should not be a child of 'endocytosis', because it is not vesicle-mediated.
>    ![screenshot 2019-02-14 at 11 50 18](https://user-images.githubusercontent.com/16541096/52785001-c7d94c80-304e-11e9-8b72-749e09694fa5.png)
>    ![screenshot 2019-02-14 at 11 50 37](https://user-images.githubusercontent.com/16541096/52785003-c7d94c80-304e-11e9-93f0-872cd1fd419e.png)
>    ![sperm entry](https://user-images.githubusercontent.com/16541096/52785045-eccdbf80-304e-11e9-940d-a1ba9c40d24b.png)

Re 5. @ukemi and @BarbaraCzub agreed that 'sperm entry' should become a child of its current grandparent 'import into cell', and not 'endocytosis'.
 


> 6. 'Endocytosis' and 'exocytosis' should probably be children of 'vesicle-mediated **intracellular** transport', because the vesicles, which mediate these processes never actually leave the cell, and at the time when they merge with the plasma membrane they are no longer 'vesicles'. This would be applicable even to exocytosis of multivesicular bodies (MVBs), which results in release of extracellular vesicles (exosomes), because the outermost vesicle of the MVB, _which mediates the transport_, never leaves the cell. (I probably would not have thought so more than a year ago (#14540), but having investigated this question in more depth now, I think this inference is not unacceptable).

Re 6. @ukemi and @BarbaraCzub agreed that these processes should remain children of 'vesicle-mediated transport', but should not become children of 'vesicle-mediated intracellular transport', because even though the vesicles themselves are intracellular, parts of the processes can occur extracellularly.



29 April 2019 Discussion Summary:
![190429discussionReSynapticVesicleTicket](https://user-images.githubusercontent.com/16541096/56901090-fd170780-6a9f-11e9-9894-0b649ce21de3.jpg)


cc @RLovering @ftwkoopmans

**Comment by BarbaraCzub** [comment] 2019-04-30 08:54
Logical problem Re 4 

Hi @ukemi 
If the link between 'synaptic vesicle exocytosis' and 'calcium ion regulated exocytosis' is removed (and a direct link is made between 'synaptic vesicle exocytosis' and 'regulated exocytosis') (screenshot 1 below), and if 'calcium ion-regulated exocytosis of neurotransmitter' becomes a direct child of 'calcium ion regulated exocytosis' (screenshot 2 below), then there is a problem with an inference re 'synaptic vesicle cycle' (seen in screenshot 1). 'Synaptic vesicle exocytosis' has been a manually asserted **part_of** child of 'synaptic vesicle cycle'. However, the reasoner inference suggests it should be **is_a** (screenshot 3 furthest down shows the reason why).

Screenshot1
<img width="1057" alt="Re4 a logicalproblem" src="https://user-images.githubusercontent.com/16541096/56950292-d27b8c00-6b3d-11e9-8e6c-751cec80be51.png">

Screenshot2
<img width="1065" alt="Re4 b" src="https://user-images.githubusercontent.com/16541096/56950333-e6bf8900-6b3d-11e9-98ca-89130e4a9546.png">

Screenshot3
<img width="867" alt="Re4 a expl" src="https://user-images.githubusercontent.com/16541096/56950400-0fe01980-6b3e-11e9-9026-edf70cc6ebf6.png">


Exocytosis is one of the steps in the synaptic vesicle cycle, therefore, I think we should keep the part_of relationship. But exocytosis is also a type of vesicle-mediated transport, and actually so is synaptic vesicle cycle, hence the reasoner's inference. Should I amend the relationships manually in the 'subclass of' field instead of adding the logical definition in the 'equivalent to' field to avoid the _is_a synaptic vesicle cycle_ inference? Or would you rather suggest another solution? Should we perhaps discuss this during an ontology call?

Thanks,
Barbara

cc @RLovering

**Comment by BarbaraCzub** [comment] 2019-04-30 09:11
Re 5. 'sperm entry' should become a child of its current grandparent 'import into cell', and not 'endocytosis'.

Hi @ukemi it appears that the 'sperm entry' term was intended for Drosophila only. Please see the definition:

"An endocytosis process that results in penetration of the egg shell through the micropyle (a specialized anterior opening in the vitelline envelope) and entry of the entire sperm, including the surrounding plasma membrane and the sperm tail, into the egg cytoplasm. This step in fertilization is seen in Drosophila, where a plasma membrane fusion event between the sperm and the egg does not occur. PMID:9630751."

However, the applied taxon constraint is for all eukaryotes, which is too broad. So instead of changing the parentage, I think we should probably restrict the usage of this term to Droshophila only? I would also consider making the GO term name more specific, e.g. 'vesicle-mediated sperm entry'? What do you think?

Thanks,
Barbara

**Comment by ftwkoopmans** [comment] 2019-04-30 10:10
> 'Synaptic vesicle exocytosis' should probably *not* be a child of
'calcium ion regulated exocytosis' (unless this is ok due to the comment
about its leakiness? - screenshot below - this is not clear to me. cc
@ftwkoopmans <https://github.com/ftwkoopmans>), because it itself has the
child 'spontaneous exocytosis of neurotransmitter', which is *independent
of Ca2+*.

correct, not all SV exocytosis is calcium regulated (eg; spontaneous
release).

Best,
Frank

**Comment by BarbaraCzub** [comment] 2019-04-30 10:33
Thanks @ftwkoopmans

**Comment by ukemi** [comment] 2019-04-30 12:31
Hi @BarbaraCzub,

The logical definition of synaptic vesicle cycle is not sufficient. There are types of vesicle-mediated transport that occur in the presynapse that are not the synaptic vesicle cycle. I would suggest removing the equivalence axiom and asserting the relationships instead.

**Comment by BarbaraCzub** [comment] 2019-04-30 13:52
Thanks for clarifying this @ukemi. I'll follow your suggestion.

**Closed** 2019-05-13 16:50 UTC
