### ISSUE TITLE
NTR: lateral pseudopodium retraction

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#21600] opened 2021-06-11 19:57 UTC
Please provide as much information as you can: 

* **Suggested term label: lateral pseudopodium retraction**

* **Definition The myosin-based contraction and retraction of the lateral pseudopodium**

* **Reference, in format PMID:12953059, PMID:15483055, PMID:17623773 and several more if needed**

* **Parent term(s)GO:0031270 pseudopodium retraction**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED) RELATED: lateral pseudopodium suppression**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pfey03** [comment] 2021-06-22 20:24
I hope this is easy to add and makes sense, please add whenever possible.

**Comment by krchristie** [comment] 2021-06-23 22:30
@pgaudet - for your records, this looked super easy so I claimed it today

**Comment by krchristie** [comment] 2021-06-23 22:40
@pfey03 - Do you think that **'pseudopodium retraction'** could be considered a type of **'cellular component disassembly'**?

If you think this is true, I could make a logical definition for **'pseudopodium retraction'** similar to this one for **'cilium dissasembly'**, which might make sense since they are both **'plasma membrane bounded cell projections'**

> 'cellular component disassembly'
 and ('results in disassembly of' some cilium)

**Comment by pfey03** [comment] 2021-06-24 01:02
no pseudopodium in ameba are different as lateral pseudopodia when they move so I'd love to have this term to distinguish as researchers do. Thanks @krchristie !

**Comment by pfey03** [comment] 2021-06-24 01:04
ah sorry @krchristie yes it should both be a 'cellular component disassembly' Thanks

**Comment by pgaudet** [comment] 2021-06-24 07:59
Yeah I didn't assign it because I though this was negatively regulating incorrectly formed pseudopods, so I wasn't sure how different it was from 'GO:0031276 negative regulation of lateral pseudopodium assembly' (which it seems I have requested a long time ago). 

Just didn't want to create equivalent terms. Based on annotated paper, these 2 terms seem very similar. 

@pfey03 can you confirm both these terms are needed? 

Also, the 'regulation' and 'positive regulation' are probably incorrect (to be confirmed, I didn't have time to check in detail). One rat paper to 'regulation' mentions cancer cells. 


Thanks, Pascale

**Comment by pfey03** [comment] 2021-06-24 15:46
@pgaudet I don't like negative regulation when the regulation is not exactly known. 

GO:0031276 negative regulation of lateral pseudopodium assembly doesn't seem so useful. Maybe my term can  be added as narrow synonym so for phenotypes I can at least keep it and GO, will see how it will be in GO CAM eventually with the regulation term.

**Comment by krchristie** [comment] 2021-06-24 16:30
I already added the term for "lateral pseudopodium retraction". Sorry for jumping on this @pgaudet, it just seemed really similar to the cilium assembly and dissassembly terms so it didn't seem controversial to me.

 If we don't think the regulation terms are very useful, perhaps we should consider obsoleting them.

Also, if there is a difference between a leading (?correct word) pseudopodium and a lateral pseudopodium, do we need component terms to distinguish them? At the moment, I would be able to make a logical definition for "pseudopodium retraction", but not for "lateral pseudopodium retraction" as there is a term for "pseudopodium", but not for "lateral pseudopodium". My understanding is that certain vertebrate immune cells move as amoebae, so these terms would be broadly useful to other organisms that have cells with amoeboid movement.

**Comment by pfey03** [comment] 2021-06-24 16:48
when cells move, I don't think it can only be Dicty, what about macrophages, lateral pseudopodia are surpassed / retracted as the cell has a direction to travel. For Dicty, e.g. PTEN has been identified to play a role in the retraction:
https://pubmed.ncbi.nlm.nih.gov/17623773/

**Comment by pfey03** [comment] 2021-06-24 16:52
And thanks @krchristie , for creating the term.

in migrating cells there is a difference between general pseudopodia and lateral. In any amoeboid cell when not stimulated they extend pseudopodium here and there and move randomly, but when stimulated to migrate, they form front pseudopodia and rear uropod and suppress the lateral pseudopodia

**Comment by krchristie** [comment] 2021-06-24 16:54
> when cells move, I don't think it can only be Dicty, what about macrophages, lateral pseudopodia are supressed / retracted as the cell has a direction to travel. For Dicty, e.g. PTEN has been identified to play a role in the retraction:
> https://pubmed.ncbi.nlm.nih.gov/17623773/

To make it clear, I'm agreeing with you, that these amoeboid movement terms are generally useful for vertebrate amoeboid cells as well as dicty.

**Comment by pgaudet** [comment] 2021-06-24 18:11
> Sorry for jumping on this @pgaudet, it just seemed really similar to the cilium assembly and dissassembly terms so it didn't seem controversial to me.

No problem! It's great to deal with NTR rapidly. 

I think the difference with a cilium is that once its forms, it's a rather permanent structure, while pseudopods kind of form all over the cell, and the cell retracts those that go in the wrong direction (and at the end of the cell) so that the cell does move in the correct direction. So - I dont think lateral pseudopod is a real cellular component? 

> If we don't think the regulation terms are very useful, perhaps we should consider obsoleting them.

Possibly - I am not sure there is a a clear distinction between lateral pseudopod retraction and (negative) regulation of lateral pseudopod formation. Is there?

**Comment by krchristie** [comment] 2021-06-25 03:28
> > Sorry for jumping on this @pgaudet, it just seemed really similar to the cilium assembly and dissassembly terms so it didn't seem controversial to me.
> 
> No problem! It's great to deal with NTR rapidly.
> 
> I think the difference with a cilium is that once its forms, it's a rather permanent structure, 

Actually, in many cases the cilium is not a permanent structure. In cells that continue to divide, the cilium is disassembled in preparation for cell division, and the basal bodies may become the centrioles for cell division. In many cell types this cycle persists for many generations. As membrane bound structures that assemble and disassemble, I think there are many parallels between cilia and pseudopodia. 

As there is clearly a way for the cell to distinguish between front pseudopodia and lateral pseudopodia, there may be a utility for having these child terms. It would definitely allow logical definitions. It might turn out that there are differences in components as well.

while pseudopods kind of form all over the cell, and the cell retracts those that go in the wrong direction (and at the end of the cell) so that the cell does move in the correct direction. So - I dont think lateral pseudopod is a real cellular component?
> 
> > If we don't think the regulation terms are very useful, perhaps we should consider obsoleting them.
> 
> Possibly - I am not sure there is a a clear distinction between lateral pseudopod retraction and (negative) regulation of lateral pseudopod formation. Is there?

**Comment by pgaudet** [comment] 2021-06-29 15:45
We will obsolete the regulation terms.

**Closed by pgaudet** 2021-06-29 15:45 UTC
Labels: New term request, dictyBase

**Comment by krchristie** [comment] 2021-07-06 22:25
I added an equivalence axiom for "pseudopodium retraction" to related it to "cellular component disassembly".

`'cellular component disassembly'
 and (results_in_disassembly_of some pseudopodium)`

I can't make an equivalence axiom for "lateral pseudopodium retraction" unless we decide to make a specific CC term for "lateral pseudopodium".

**Comment by pgaudet** [comment] 2021-07-07 05:45
I dont think we should create term just to make equivalence axioms, so unless "lateral pseudopodium" can be defined as being a different structure from  "pseudopodium", we can live without an EA.

**Comment by krchristie** [comment] 2021-07-08 04:53
> I dont think we should create term just to make equivalence axioms, so unless "lateral pseudopodium" can be defined as being a different structure from "pseudopodium", we can live without an EA.

I agree; that's why I didn't create a term for "lateral pseudopodium". :)
